### PR TITLE
misc: fix resource leaks

### LINKED ISSUE #5735: misc: resource leak problems
`fclose(fileh_std) ` should be put before Line 83?
https://github.com/pmodels/mpich/blob/94b1cd6f060cafbf68d6d83ea551a8bcc8fcecd4/src/mpi/romio/test/external32.c#L89-L98

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
Fix a few places where we neglected to close file handles and free memory upon errors.

Thank @ryancaicse for reporting.

Fixes #5735

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

File: src/pm/util/rm.c [hunk 1]
```diff
@@ -374,7 +374,20 @@ MachineTable *MPIE_ReadMachines(const char *arch, int nNeeded, void *data)
...
     mt->nHosts = nFound;
+
+  fn_exit:
+    fclose(fp);
     return mt;
+
+  fn_fail:
+    if (mt->desc) {
+        MPL_free(mt->desc);
+    }
```
Comment (raffenet) [inline src/pm/util/rm.c:385]: won't this cause a potential NULL dereference?

Comment (hzhou) [reply src/pm/util/rm.c:385]: You are right.

Comment (hzhou) [reply src/pm/util/rm.c]: fixed

**Review by raffenet — APPROVED** [review]
