### PR TITLE
pm/hydra: fix kvsname collision when using multiple mpiexecs

### LINKED ISSUE #2619: Adding hostname in PMI kvs name.
The PMI kvsname currently consists of only `pid` and `kvsnum`, which may not be unique if processes are spawned by multiple mpiexec on different node. It should really have the hostname as well, as the comment in function `fPMIKVSAllocate` in file src/pm/util/pmiserv.c.

### PR DESCRIPTION
**Pull request by gcongiu**
Now hydra kvsname also contains a random
generated number and the hostname

@raffenet

### CODE REVIEW

**Comment by wesbland** [comment]
Can you please update the commit message to use pmodels/mpich#2619 so it doesn't collide with other projects (like us)?

File: src/pm/hydra/pm/pmiserv/common.c [hunk 1]
```diff
@@ -122,11 +122,27 @@ char *HYD_pmcd_pmi_find_token_keyval(struct HYD_pmcd_token *tokens, int count, c
...
+    gethostname(hostname, MAX_HOSTNAME_LEN);
+    
+    gettimeofday(&tv, NULL);
+    ptm = localtime(&tv.tv_sec);
+    msec = (unsigned int)ptm->tm_hour * 3600000 +
+           (unsigned int)ptm->tm_min  * 60000   +
+           (unsigned int)ptm->tm_sec  * 1000    +
+           (unsigned int)(tv.tv_usec  / 1000);
+    srand(msec);
+    rnd = rand();
```
Comment (wesbland) [inline src/pm/hydra/pm/pmiserv/common.c]: Might I suggest using `srandom_r` and `random_r` instead of `srand` and `rand` here so these don't mess with the user's random number generator? They're also multithreading safe. We use them in `ch4r_symheap.h`.

**Comment by wesbland** [comment]
I wasn't as concerned about the name of the pull request, I was more concerned about the commit message itself since that will auto-close the issue. Can you change that too?

File: src/pm/hydra/pm/pmiserv/common.c (hunk 1 above)
Comment (gcongiu) [reply src/pm/hydra/pm/pmiserv/common.c]: @wesbland thank you for the hint.

**Comment by wesbland** [comment]
BTW, you don't have to close the PR to push an updated commit. Just force push your new patches to the same remote branch and GitHub will automatically update the PR and we won't lose the comments and context.

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

File: src/pm/hydra/pm/pmiserv/common.c (hunk 1 above)
Comment (raffenet) [reply src/pm/hydra/pm/pmiserv/common.c]: @wesbland Those aren't available on OSX. Also, this is happening in `mpiexec` so I'm not sure there is cause for concern about the user here.

Comment (wesbland) [reply src/pm/hydra/pm/pmiserv/common.c]: Oh ok. I saw pmi and missed the pmiserv. I thought this was on the client side. 👍

Comment (gcongiu) [reply src/pm/hydra/pm/pmiserv/common.c]: Ok so it seems rand() and srand() would work just fine for this particular case. Any comment on the seed generation? There are several options available (two of which follow):
1) microseconds in second: there would be P(collision) = 10^(-12) at any second of the day
2) milliseconds in day: there would be P(collision) = 1/(24*3600000)^2 = 1.34 * 10^(-16) at any day. This would reduce depending on the distance two mpiexecs are launched within the same day (e.g., in the same second P(collision) would only be 10^(-6)); thus microseconds in minute (2.7 * 10(-16)) would probably be better considering that mpiexecs will be unlikely to be launched in the same second and maybe not even in the same minute.

We also had some discussion about using the MAC address of the interface as seed but maybe time would be more than enough.

Comment (raffenet) [reply src/pm/hydra/pm/pmiserv/common.c]: IMO, MAC would be better if it's not too much trouble vs time.

**Comment by gcongiu** [comment]
I have added preprocessor checks in pm/hydra/pm/pmiserv/common.c to either select clock_gettime() for nanosecond precision in the random number generator's seed or gettimeofday() for microsecond precision (whenever clock_gettime() is not available).

@pavanbalaji 
@raffenet

**Comment by raffenet** [comment]
BTW, Wesley's comment was about your reference to the issue in the commit message. It should read - ```Fixes pmodels/mpich#2619``` so we avoid accidentally closing issues in any MPICH repos besides this one.

**Comment by gcongiu** [comment]
Ok, I also fixed the corresponding documentation in the wiki

File: src/pm/hydra/pm/pmiserv/common.c [hunk 2]
```diff
@@ -122,11 +122,30 @@ char *HYD_pmcd_pmi_find_token_keyval(struct HYD_pmcd_token *tokens, int count, c
 HYD_status HYD_pmcd_pmi_allocate_kvs(struct HYD_pmcd_pmi_kvs ** kvs, int pgid)
 {
     HYD_status status = HYD_SUCCESS;
+    char hostname[MAX_HOSTNAME_LEN];
+#ifdef MPL_HAVE_CLOCK_GETTIME
+    struct timespec ts;
+#else
+    struct timeval tv;
+#endif
```
Comment (pavanbalaji) [inline src/pm/hydra/pm/pmiserv/common.c]: Can you use `MPL_time_t` instead of the ifdefs?

File: src/pm/hydra/pm/pmiserv/common.c [hunk 3]
```diff
@@ -122,11 +122,30 @@ char *HYD_pmcd_pmi_find_token_keyval(struct HYD_pmcd_token *tokens, int count, c
...
     HYDU_FUNC_ENTER();
 
+    gethostname(hostname, MAX_HOSTNAME_LEN);
+#ifdef MPL_HAVE_CLOCK_GETTIME
+    MPL_wtime(&ts);
+    seed = (unsigned int)ts.tv_nsec;
+#else
+    gettimeofday(&tv, NULL);
+    seed = (unsigned int)tv.tv_usec;
+#endif
```
Comment (pavanbalaji) [inline src/pm/hydra/pm/pmiserv/common.c]: I think it would be cleaner to only use MPL, and convert it to double-precision seconds.  Then you can convert it to microseconds and cast to `unsigned int`.

**Comment by gcongiu** [comment]
test:jenkins/ch3/tcp

File: src/pm/hydra/pm/pmiserv/common.c (hunk 3 above)
Comment (gcongiu) [reply src/pm/hydra/pm/pmiserv/common.c]: I have modified this to use MPL_time_t as you have suggested.

**Comment by pavanbalaji** [comment]
Looks good to me.
