### PR TITLE
hydra/proxy: prevent double resetting exit_status

### LINKED ISSUE #7057: hydra: mpiexec sometimes fail to capture exit code
Using the following trivial code:

```cpp
#include <mpi.h>
#include <unistd.h>

int main(int argc, char ** argv) {
    MPI_Init(&argc, &argv);
    _exit(3);
}
```

I observe that `mpiexec` sometimes exits with code 0. I'm launching it like this:

```
$ mpiexec -print-all-exitcodes -launcher fork -n 2 -verbose standalone__exit ; echo $?
...
[proxy:0@uk-eellis12-l] Sending PMI command:
    cmd=barrier_out
[proxy:0@uk-eellis12-l] Sending PMI command:
    cmd=barrier_out
[proxy:0@uk-eellis12-l] got pmi command from downstream 0-0:
    cmd=get kvsname=kvs_2973158_0_481767593_uk-eellis12-l key=-allgather-shm-1-0
[proxy:0@uk-eellis12-l] Sending PMI command:
    cmd=get_result rc=0 value=0200B675AC1AF1A80000000000000000 found=TRUE
[proxy:0@uk-eellis12-l] got pmi command from downstream 0-1:
    cmd=get kvsname=kvs_2973158_0_481767593_uk-eellis12-l key=-allgather-shm-1-1
[proxy:0@uk-eellis12-l] Sending PMI command:
    cmd=get_result rc=0 value=0200AFE9AC1AF1A80000000000000000 found=TRUE
[proxy:0@uk-eellis12-l] Sending upstream hdr.cmd = CMD_EXIT_STATUS
[mpiexec@uk-eellis12-l] Exit codes: [uk-eellis12-l] 0,0
0
```

Most of the time, one or other of the "Exit codes" shows as non-zero, and the `mpiexec` exit code is non-zero, but often at least one is zero, and sometimes both are, leading to `mpiexec` exiting with a non-zero code.

This is using:

```
HYDRA build details:
    Version:                                 4.2.2
    Release Date:                            Wed Jul  3 09:16:22 AM CDT 2024
    CC:                              gcc      
    Configure options:                       '--disable-option-checking' '--prefix=/out/install_Linux_4.2.2_2024-07-08_070147' '--with-hwloc=embedded' '--with-device=ch4:ofi:tcp,shm' '--enable-shared' '--with-libfabric=embedded' '--disable-fortran' '--disable-cxx' '--cache-file=/dev/null' '--srcdir=.' 'CC=gcc' 'CFLAGS= -O2' 'LDFLAGS=' 'LIBS=' 'CPPFLAGS= -DNETMOD_INLINE=__netmod_inline_ofi__ -I/tmp/mpich-2024-07-08_070147.b0wvSj/mpich-4.2.2/src/mpl/include -I/tmp/mpich-2024-07-08_070147.b0wvSj/mpich-4.2.2/modules/json-c -I/tmp/mpich-2024-07-08_070147.b0wvSj/mpich-4.2.2/modules/hwloc/include -D_REENTRANT -I/tmp/mpich-2024-07-08_070147.b0wvSj/mpich-4.2.2/src/mpi/romio/include -I/tmp/mpich-2024-07-08_070147.b0wvSj/mpich-4.2.2/src/pmi/include -I/tmp/mpich-2024-07-08_070147.b0wvSj/mpich-4.2.2/modules/yaksa/src/frontend/include -I/tmp/mpich-2024-07-08_070147.b0wvSj/mpich-4.2.2/modules/libfabric/include'
    Process Manager:                         pmi
    Launchers available:                     ssh rsh fork slurm ll lsf sge manual persist
    Topology libraries available:            hwloc
    Resource management kernels available:   user slurm ll lsf sge pbs cobalt
    Demux engines available:                 poll select
```

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
Under the default auto_cleanup mode, when one process exit abnormally, hydra will kill all other processes by pre-setting the exit_status to 0. Sometimes two or more processes exit abnormally before the latter one being killed. This resulting in double presetting the exit status which resulted in all exit code for all processes being 0.

Fixes #7057 

[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch3/tcp
test:mpich/ch4/ofi

File: src/pm/hydra/proxy/pmip_cb.c [hunk 1]
```diff
@@ -981,11 +984,6 @@ static HYD_status launch_procs(struct pmip_pg *pg)
                 MPL_free(str);
             }
 
-            if (pg->hostname) {
-                status = HYDU_append_env_to_list("PMI_HOSTNAME", pg->hostname, &force_env);
-                HYDU_ERR_POP(status, "unable to add env to list\n");
-            }
```
Comment (raffenet) [inline src/pm/hydra/proxy/pmip_cb.c:987]: bad rebase?

Comment (hzhou) [reply src/pm/hydra/proxy/pmip_cb.c:987]: Good catch! I will reset this after the current testing finish.

**Review by raffenet — APPROVED** [review]
