### PR TITLE
op: replace predefined datatype on input

### LINKED ISSUE #1769: bug: datatypes created by MPI_Type_create_f90_real not usable in MPI operations
**Originally by _klimach_ on 2012-12-19 16:03:57 -0600**

---

I installed MPICH2 3.0rc1 using GCC 4.7.2 and found a problem with MPI_Type_create_f90_real.
It is very similar to the problem I reported in OpenMPI under: https://svn.open-mpi.org/trac/ompi/ticket/3432

Running the following program:

```
program test_mpi
use mpi
implicit none

integer, parameter :: rk_prec = 15
integer, parameter :: rk = selected_real_kind(rk_prec)

integer :: rk_mpi
integer :: iError
real(kind=rk) :: a_real
real(kind=rk) :: res

call MPI_Init(iError)
call mpi_type_create_f90_real(rk_prec, MPI_UNDEFINED, rk_mpi, iError)
write(*,*) 'MPI_REAL8:', MPI_REAL8
write(*,*) 'MPI_DOUBLE_PRECISION:', MPI_DOUBLE_PRECISION
write(*,*) 'type_create_f90_real:', rk_mpi
a_real = 1.0
call MPI_Reduce(a_real, res, 1, rk_mpi, MPI_MIN, 0, MPI_COMM_WORLD, iError)
call MPI_Finalize(iError)

end program test_mpi
```

Results in the following output and error:

```
MPI_REAL8:  1275070505
MPI_DOUBLE_PRECISION:  1275070495
type_create_f90_real: -1946157049
Fatal error in PMPI_Reduce: Invalid MPI_Op, error stack:
PMPI_Reduce(1217)........: MPI_Reduce(sbuf=0x7fff43637108, rbuf=0x7fff436370f8, count=1, dtype=USER<f90_real>, MPI_MIN, root=0, MPI_COMM_WORLD) failed
MPIR_MINF_check_dtype(71): MPI_Op MPI_MIN operation not defined for this datatype
```

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

We are supposed to support operations on some predefined datatype, such
as those from MPI_Type_create_f90_xxx. However, those types are in fact
derived types wraps around a basic type. Check and replace the input
datatype with the basic type if that is the case so the reduction can
work. Since the datatype in these case are all input only parameters,
there shouldn't be any side effects replacing them.

Fixes #1769 

[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

File: src/mpi/coll/op/oputil.c [hunk 1]
```diff
@@ -86,3 +86,25 @@ const char *MPIR_Op_builtin_get_shortname(MPI_Op op)
...
+        MPIR_Datatype *dt_ptr;
+        MPIR_Datatype_get_ptr(datatype, dt_ptr);
+
+        if (dt_ptr && dt_ptr->contents) {
+            int combiner = dt_ptr->contents->combiner;
+            if (combiner == MPI_COMBINER_F90_REAL ||
+                combiner == MPI_COMBINER_F90_COMPLEX || combiner == MPI_COMBINER_F90_INTEGER) {
+                if (MPI_SUCCESS == (*MPIR_OP_HDL_TO_DTYPE_FN(op)) (dt_ptr->basic_type)) {
+                    alt_dt = dt_ptr->basic_type;
+                }
```
Comment (raffenet) [inline src/mpi/coll/op/oputil.c:105]: Is there any reason not to use `MPIR_Datatype_get_basic_type` instead of checking the combiner?

Comment (hzhou) [reply src/mpi/coll/op/oputil.c:105]: `basic_type` will not tell us whether it is one of the predefined F90 types, right?

Comment (raffenet) [reply src/mpi/coll/op/oputil.c:105]: I think so. Wasn't totally aware of these "predefined" types in the standard. Calls into question some of the code that identifies predefined datatypes in MPICH, but that's a separate story.

**Review by raffenet — APPROVED** [review]
