### PR TITLE
mpir: check reference count before freeing built-in comm

### LINKED ISSUE #6584: issue: Inconsistent communication between nodes
Hi there,

I am a developer of [Modin](https://github.com/modin-project/modin) and [unidist](https://github.com/modin-project/unidist). We use MPI as a backend in unidist, and mpich can be used as one of the implementations in that backend. Modin uses unidist to distribute computation.

We have been looking at one of our benchmarks recently. The benchmark is [HM](https://github.com/intel-ai/timedf/tree/97024b05ff15a8779036a99a49674b3e8847dad1/timedf_benchmarks/hm_fashion_recs#intro), which has to do with data processing and uses Modin for this purpose. Modin distributes computation with unidist on MPI.

We have checked the benchmark in a single node with mpich, Open MPI and Intel MPI. Everything works well. Then, we tried running the benchmark in a cluster consisting of two nodes. Open MPI and Intel MPI work well, but mpich fails.

How does unidist work? We have Root process (rank 0) and multiple workers (rank 1, ..., N), which sit in infinite while loop and wait for 
tasks to execute. Root sends out tasks to workers that start executing them. Workers themselves can communicate with each other to send/recv necessary data for task execution.

How does the HM fails? Root process goes up to the end of the benchmark, sends out a termination signal to workers, and ends up execution. Workers themselves have asyncronous pending requests got from `Isends` during the flow. Once workers receive the termination signal, they gradually finish all remaining tasks, particularly, call `Wait` on every request to make sure there is no pending isend operation, as well as call recv and irecv to receive/cancel communication. However, all of a sudden, a worker on one node receives wrong data from other worker from other node. We see the error in the workers.

I tried using mpich from conda and got the error on unidist side because mpi.recv returns wrong data, i.e., we expect to receive other data. Also, there is the following output from mpi internals

```
Abort(409119631) on node 1 (rank 1 in comm 0): Fatal error in internal_Wait: Other MPI error, error stack:
internal_Wait(89).............: MPI_Wait(request=0x7f31971a5910, status=0x1) failed
MPIR_Wait(948)................:
MPIR_Wait_state(886)..........:
MPID_Progress_wait(335).......:
MPIDI_progress_test(158)......:
MPIDI_OFI_handle_cq_error(625): OFI poll failed (ofi_events.c:627:MPIDI_OFI_handle_cq_error:Input/output error)
```

I also tried mpich built from source and only get the error on unidist side because mpi.recv returns wrong data, i.e., we expect to receive other data. There is no any output from mpi internals.

I would really appreciate if you could help handle the issue. Maybe there has already been a similar issue in internode communication using isend.

Thanks in advance.

### LINKED ISSUE #6592: regression: stdout get unexpected lines with traces pointing to PMI code.
```
======================================================================
FAIL: testSuccess (__main__.TestRunCommand.testSuccess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/mpi4py-testing/mpi4py-testing/mpi4py/demo/test-run/test_run.py", line 246, in testSuccess
    self.assertEqual(stderr, '')
AssertionError: '[0] 680 at [0x55a35136b7e0], src/util/mpir_pmi.c[303]\n' != ''
- [0] 680 at [0x55a35136b7e0], src/util/mpir_pmi.c[303]
```
Full logs can be found [here](https://github.com/mpi4py/mpi4py-testing/actions/runs/5549556381/jobs/10137798614).
Are those memory leaks? 
Maybe a regression from #6580?

PS: I'm surprised MPICH's own test suite did not catch this issue before. Could it be that the issue is actually on mpi4py side?

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
Before this PR, we do not check pending requests before freeing builtin communicators and exit. It may leave remote process hanging, for example, due to not completing a rndv protocol. This PR adds reference checking and will continue poll progress until reference clears before freeing the communicator.

Also cherry picked PR #6513 so we check for inactive persistent request as well before finalizing.

Fixes #6584
Fixes #6592 ([mpir: fix memory leak in mpir_hwtopo.c](https://github.com/pmodels/mpich/pull/6591/commits/ab8eb7dbabb70bc7f28ab566573c8406a89a3d07))
[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by hzhou** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by hzhou** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by hzhou** [comment]
Example output from running the `pt2pt/rqfree` test:
```
[1] WARNING: Builtin communicator 44000000 has pending 2 references, polling progress until all references clears. 
[0]  No Errors                                                                                                     
[0] WARNING: freeing inactive persistent request ac000001 on communicator 44000000.                                
```

**Comment by hzhou** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by hzhou** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by hzhou** [comment]
ucx-asan crashed -
test:mpich/ch4/ucx

**Comment by hzhou** [comment]
test:mpich/ch4/ucx

File: test/mpi/runtests [hunk 1]
```diff
@@ -946,6 +946,9 @@ sub TestNormal {
         if (/^\s*No [Ee]rrors\s*$/ && $found_noerror == 0) {
             $found_noerror = 1;
         }
+        elsif (/^WARNING: .*/) {
+            # skip WARNING messages (e.g. from MPICH finalize)
+        }
```
Comment (raffenet) [inline test/mpi/runtests:951]: I'm slightly concerned this could permit warnings when we do not expect them. Would it fit better in one of the other `resultTest` implementations?

**Review by raffenet — COMMENTED** [review]
a few comments, but otherwise a good direction 👍

File: src/mpi/comm/builtin_comms.c [hunk 2]
```diff
@@ -127,7 +127,18 @@ static int finalize_builtin_comm(MPIR_Comm * comm)
         comm->errhandler = NULL;
     }
 
-    mpi_errno = MPIR_Comm_release_always(comm);
+    MPIR_Comm_free_inactive_requests(comm);
+
+    int ref_count = MPIR_Object_get_ref(comm);
+    if (ref_count != 1) {
+        printf
```
[the remark this answers is not in the document]
Comment (hzhou) [reply src/mpi/comm/builtin_comms.c]: fixed.

File: src/mpi/comm/commutil.c [hunk 3]
```diff
@@ -1364,3 +1340,37 @@ int MPII_Comm_is_node_balanced(MPIR_Comm * comm, int *num_nodes, bool * node_bal
...
+    return MPI_SUCCESS;
+}
+
+int MPIR_Comm_free_inactive_requests(MPIR_Comm * comm)
+{
+    MPIR_Request *request, *tmp;
+    MPID_THREAD_CS_ENTER(VCI, comm->mutex);
+    HASH_ITER(hh, comm->persistent_requests, request, tmp) {
+        if (!MPIR_Request_is_active(request)) {
+            printf("WARNING: freeing inactive persistent request %x on communicator %x.\n",
```
[the remark this answers is not in the document]
Comment (hzhou) [reply src/mpi/comm/commutil.c]: fixed.

File: test/mpi/runtests (hunk 1 above)
Comment (hzhou) [reply test/mpi/runtests:951]: Let me make a separate PR for `resultTest` refactor, and then rebase this PR on top of it.

**Comment by hzhou** [comment]
test:mpich/ch4/most

File: test/mpi/runtests (hunk 1 above)
Comment (hzhou) [reply test/mpi/runtests]: https://github.com/pmodels/mpich/pull/6591/commits/9b2f76d5efce04cbe160de32ea5dcc08b3bb57db

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch4/most
