### PR TITLE
mpl/gpu/ze: fix issue when using whole device in ZE_AFFINITY_MASK

### LINKED ISSUE #6958: [4.2.0] Assert in mpl_gpu_ze.c:466 when ZE_AFFINITY_MASK set to second device
### Issue
Running MPI programs on systems with Intel(R) Data Center GPU assert when ZE_AFFINITY_MASK is set to use a second device.
### Environment
O/S: SLES 15.5
CPU: 2x Intel(R) Xeon(R) Gold 6336Y CPU @ 2.40GHz
GPU: 2x Intel(R) Data Center GPU Flex 170
MPI: MPICH 4.2.0 configured with --enable-debuginfo --enable-shared, no libdrm present
### Reproducer
Save the following trivial MPI program e.g. as `mpitest.c`:
```
#include <mpi.h>

int main(int argc, char** argv)
{
    MPI_Init(&argc, &argv);
    MPI_Finalize();
    return 0;
}
```
Build it as follows:
```mpicc -g -O0 -o mpitest mpitest.c```

Run it with the affinity mask set to the second device:
```ZE_AFFINITY_MASK=1 MPIR_CVAR_CH4_IPC_ZE_SHAREABLE_HANDLE=pidfd mpirun -n 1 ./mpitest```

Observe assertion failure:
> mpitest: mpich-4.2.0/src/mpl/src/gpu/mpl_gpu_ze.c:466: int MPL_gpu_init_device_mappings(int, int): Assertion `local_dev_id == local_ze_device_count' failed.

### PR DESCRIPTION
**Pull request by abrooks98**
## Pull Request Description

`mask_contents` uses signed integers and sets initial values to -1. Since `get_max_dev_id` was modified in #6929 to take unsigned integers, without converting during the comparison, `max_subdev_id` is assigned the incorrect value, causing an assertion failure when using whole device ids in `ZE_AFFINITY_MASK`.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by abrooks98** [comment]
Despite not being relevant to #6958, this does still fix a bug present in main

File: src/mpl/src/gpu/mpl_gpu_ze.c [hunk 1]
```diff
@@ -1186,9 +1186,9 @@ static void get_max_dev_id(uint32_t *max_dev_id, uint32_t *max_subdev_id)
 
     /* Values based on ZE_AFFINITY_MASK */
     for (int i = 0; i < mask_contents.num_dev; ++i) {
-        if (mask_contents.dev_id[i] > *max_dev_id)
+        if (mask_contents.dev_id[i] > (int) *max_dev_id)
```
Comment (hzhou) [inline src/mpl/src/gpu/mpl_gpu_ze.c:1189]: Wait, the issue is `max_dev_id` need go to `-1` and it is wrongly typed to `uint32_t`, and the solution is to cast? Shouldn't we fix the parameter types in `get_max_dev_id` (and fix the types in calling sites as well)?

Comment (abrooks98) [reply src/mpl/src/gpu/mpl_gpu_ze.c:1189]: No the problem is that `mask_contents.dev_id[i]` can be -1, and because `max_dev_id` is unsigned, the comparison is treated as unsigned, so it incorrectly evaluates the branch as true (i.e. `UINT_MAX > 0`). I tested this independently:

```
#include <stdio.h>
#include <stdint.h>

int main(int argc, char **argv) {
    int dev_id = -1;
    uint32_t max_dev_id = 0;

    if (dev_id > max_dev_id) {
        max_dev_id = dev_id;
    }
    fprintf(stderr, "%lu\n", max_dev_id);

    dev_id = -1;
    max_dev_id = 0;

    if (dev_id > (int) max_dev_id) {
        max_dev_id = dev_id;
    }
    fprintf(stderr, "%lu\n", max_dev_id);
}
```

output:

```
> gcc -g -O0 -o convert convert.c
> ./convert
4294967295
0
```

Comment (abrooks98) [reply src/mpl/src/gpu/mpl_gpu_ze.c:1189]: To your original suggestion though, I would be okay to instead change everything to `signed` (including the types)

Comment (abrooks98) [reply src/mpl/src/gpu/mpl_gpu_ze.c:1189]: Reverted back to `int` parameters for `get_max_dev_id` and changed `max_dev_id` and `max_subdev_id` to `int`

Comment (hzhou) [reply src/mpl/src/gpu/mpl_gpu_ze.c]: Thank you for the explanation. Yeah, I think using `int` is more robust.

**Review by hzhou — APPROVED** [review]
Approved. @abrooks98 merge at your discretion
