### PR TITLE
request: fix start of MPI_Send_init to MPI_PROC_NULL

### LINKED ISSUE #5053: MPI_*_init() functions do not support MPI_PROC_NULL
None of the MPI_Send_init(), MPI_Recv_init(), etc functions support use with MPI_PROC_NULL. The functions return successfully, and MPI_Start() returns, but then MPI_Wait() hangs. This is because MPID_Startall() skips over any request with MPI_PROC_NULL. When MPI_Wait() later sees the request, it's still marked as incomplete but nothing is being done with it.

### PR DESCRIPTION
**Pull request by travisk1154**
## Pull Request Description
There was an error in ch4_startall.h at L21 in which MPIDIG_REQUEST was being used. This was incorrect and was swapped to MPIDI_PREQUEST.

## TODO
* [x] Confirm user reported bug
* [x] Implement Fix
* [x] Create Tests

Fixes #5053 

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [x] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] You or your company has a signed contributor's agreement on file with Argonne
* [x] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by hzhou** [comment]
>  Commit message is of the form: module: short description and follows good practice

**Comment by hzhou** [comment]
Do not put debugging code into commits, at least not to the PR

File: test/mpi/pt2pt/inactivereq.c [hunk 1]
```diff
@@ -79,6 +79,52 @@ int test_recv_init(int src_rank, const char *test_name)
...
+    MPI_Wait(&r, &s);
+
+    MPI_Send_init(buf, 10, MPI_INT, MPI_PROC_NULL, tag, MPI_COMM_WORLD, &r);
+    MPI_Start(&r);
+    MPI_Wait(&r, &s);
+
+    flag = 0;
+    s.MPI_TAG = 10;
+    s.MPI_SOURCE = 10;
+    MPI_Test(&r, &flag, &s);
```
Comment (hzhou) [inline test/mpi/pt2pt/inactivereq.c:103]: You already ran `MPI_Wait` on the request, which sets the request to `MPI_REQUEST_NULL`. What's the point of `MPI_Test` and `MPI_Wait` on it again?

**Review by hzhou — CHANGES_REQUESTED** [review]
Please squash the last two commits (and rebase to `main` branch).

File: test/mpi/pt2pt/inactivereq.c (hunk 1 above)
Comment (raffenet) [reply test/mpi/pt2pt/inactivereq.c]: Persistent requests become inactive after completion with `MPI_TEST` or `MPI_WAIT`. They are not set to `MPI_REQUEST_NULL`.

File: src/mpid/ch4/src/ch4_startall.h [hunk 2]
```diff
@@ -18,7 +18,7 @@ MPL_STATIC_INLINE_PREFIX int MPID_Startall(int count, MPIR_Request * requests[])
     for (i = 0; i < count; i++) {
         MPIR_Request *const preq = requests[i];
         /* continue if the source/dest is MPI_PROC_NULL */
-        if (MPIDIG_REQUEST(preq, rank) == MPI_PROC_NULL)
+        if (MPIDI_PREQUEST(preq, rank) == MPI_PROC_NULL)
```
Comment (raffenet) [inline src/mpid/ch4/src/ch4_startall.h:21]: This fix is good, but (you'll hear this from me a lot) the commit message needs to be improved. It only describes what you did. You should describe **why** you did it. In this case, there was a user-observable bug #5053.

FWIW, I was able to write a test program that hung on this bug when it shouldn't have:
```
#include <mpi.h>
#include <stdlib.h>
#include <stdio.h>

int main(void) {
    MPI_Init(NULL, NULL);

    MPI_Request request = MPI_REQUEST_NULL;
    MPI_Recv_init(NULL, 0, MPI_INT, MPI_PROC_NULL, 0, MPI_COMM_WORLD, &request);
    MPI_Start(&request);
    MPI_Wait(&request, MPI_STATUS_IGNORE);
    MPI_Request_free(&request);

    MPI_Finalize();

    return 0;
}
```

**Comment by raffenet** [comment]
Please see this link for tips on formatting good commit messages: https://chris.beams.io/posts/git-commit/. The short story is limit subject lines to ~50 characters and put the rest in the body (wrapped at 72 characters). Many editors have a git commit mode that can help with this.

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Review by hzhou — APPROVED** [review]
Looks good to me.

**Review by raffenet — APPROVED** [review]
LGTM. Thanks for taking care of the commit message!

**Comment by travisk1154** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

File: test/mpi/pt2pt/inactivereq.c [hunk 3]
```diff
@@ -79,6 +79,27 @@ int test_recv_init(int src_rank, const char *test_name)
...
+
+    MPI_Recv_init(buf, 10, MPI_INT, MPI_PROC_NULL, tag, MPI_COMM_WORLD, &r);
+    MPI_Start(&r);
+    MPI_Wait(&r, &s);
+    MPI_Request_free(&r);
+
+    MPI_Send_init(buf, 10, MPI_INT, MPI_PROC_NULL, tag, MPI_COMM_WORLD, &r);
+    MPI_Start(&r);
+    MPI_Wait(&r, &s);
+
```
Comment (hzhou) [inline test/mpi/pt2pt/inactivereq.c:99]: Why extra new line here? Not critical but nice to have a consistent code style.
