### PR TITLE
Fix Argobots support

### LINKED ISSUE #4422: test/mpich/threads: MTest_init_thread_pkg() is not called.
### Problem

In MPICH multithreaded tests, `MTest_init_thread_pkg()` should be called in `MTest_Init_thread()` but it is not. This causes an uninitialized error when underlying threads require initialization (which is now applies to Argobots). In fact, it breaks tests with Argobots (see #4421).

### Reason

The following part is expected to initialize `MTest_init_thread_pkg()`, but it is ignored since `mtest.o` is compiled without `-DMTEST_USE_THREAD`.
https://github.com/pmodels/mpich/blob/master/test/mpi/util/mtest.c#L85-L87

Note that other thread-dependent calls are defined in `mtest_thread.c` (and compiled into `mtest_thread.o`)
https://github.com/pmodels/mpich/blob/master/test/mpi/util/mtest_thread.c

This was introduced by 28b3059 in order to split single-threaded `mtest` (`mtest.o`) and multithreaded `mtest` (`mtest_thread.o`). I believe the root cause of this issue is that `mtest.o` calls a thread-related feature and `mtest_thread.o` is considered an additional object that adds functionalities on top of `mtest.o`. Note that the current linking is as follows:
```
Multithreaded tests are linked to mtest.o and mtest_thread.o
Single-threaded tests are linked to mtest.o
```

### How to fix

There are several ways to fix it. I list some reasonable ones. Personally I like the solution 0.

#### 0. Remove `MTest_init_thread_pkg()`
  - Right now only Argobots has this restriction. Argobots can solve it internally in `mtest_thread_abt.h` (by checking initialization in every thread-function calls).

#### 1. Define `MTest_Init_thread()` and `MTest_Finalize()` in `mtest_thread.o`.
  - Put common implementation in a header (say, `mtest_common.h`) and both `mtest.c` and `mtest_thread.c` implement `MTest_Init_thread()` and `MTest_Finalize()`. `mtest_thread.c` does not rely on `mtest.c`
```
Multithreaded tests are linked to mtest_thread.o
Single-threaded tests are linked to mtest.o
```
#### 2. Create single-threaded `MTest_init_thread_pkg()`
  - This can remove `#ifdef MTEST_USE_THREAD` in `mtest.c`.
```
Multithreaded tests are linked to mtest.o and mtest_thread.o
Single-threaded tests are linked to mtest.o and mtest_single.o
```

#### 3. Create another wrapper function (say, `MTest_Init_thread_with_thread_pkg()`)
  - `MTest_Init_thread_with_thread_pkg()` is implemented in `mtest_thread.c`
  - This needs to change all the tests in `test/mpi/threads/`.
```
Multithreaded tests are linked to mtest.o and mtest_thread.o
Single-threaded tests are linked to mtest.o
```

#### 3.b. Use a macro trick.
 - Similar to 3 but use a macro trick to avoid rewriting tests in `test/mpi/threads/`
```c
// in mtest_thread.h
#define MTest_Init_thread(...) \
do {                           \
  MTest_init_thread_pkg(...);  \
  MTest_Init_thread(...);      \
while (0)
```

#### * Dirty solutions:
- Define `MTest_init_thread_pkg()` as a weak symbol.
- Use `__attributes__((constructor))` (initialize a thread package in program initialization).

Any suggestions are welcome.

### PR DESCRIPTION
**Pull request by shintaro-iwasaki**
## Pull Request Description

This PR fixes Argobots support.

1. Fix `mpl/include/mpl_thread_argobots.h`
This change will not affect the default Pthreads behavior.

2. Call `MPID_Thread_init()` in `MPI_T_init_thread()`
Any `MPID_Thread_` operations should be called after `MPID_Thread_init()`. This will not affect the default Pthreads behavior since the Pthreads version does nothing in `MPID_Thread_init()`.
   - Note `MPI_T_init_thread()` can be called before `MPI_Init_thread()`, so `MPI_T_init_thread()` needs its own `MPID_Thread_init()`.

3. Add `yield()` to a busy loop in `test/mpi/threads/comm/idup_deadlock`
Nonpreemptive threads (e.g., Argobots threads) can cause a deadlock if there is a busy loop. This PR adds a new yield function (`MTest_thread_yield()`) and inserts it into a busy loop in `test/mpi/threads/comm/idup_deadlock`.
This will not affect the default Pthreads behavior since the Pthreads version does nothing in `MTest_thread_yield()`.

### Note

Regarding `3. MTest_thread_yield()`, there are many options.
1. Add yield
  1.a. [What this PR does] Add `MTest_thread_yield()`, which calls `yield()` only when the underlying thread is nonpreemptive.
  1.b. Add `MTest_thread_scheduling_point()` (instead of `MTest_thread_yield()`). The functionality is the same as that of 1.a.
  1.c. Add `MTest_thread_yield()`, which calls `yield()` even with Pthreads (e.g., `pthread_yield()`).
2. Add another synchronization method that has a scheduling point when the underlying thread is nonpreemptive (e.g., `MTest_thread_lock()`).

## Expected Impact

No performance difference for the default Pthreads version.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
        Fixes #4422.
* [ ] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by shintaro-iwasaki** [comment]
test:jenkins/ch3/tcp

**Comment by shintaro-iwasaki** [comment]
test:jenkins/ch4/argobots

**Comment by shintaro-iwasaki** [comment]
test:jenkins/ch4/argobots

**Comment by shintaro-iwasaki** [comment]
test:jenkins/ch4/argobots

**Comment by shintaro-iwasaki** [comment]
test:jenkins/ch4/ofi

File: src/mpl/include/mpl_thread_argobots.h [hunk 1]
```diff
@@ -50,9 +50,9 @@ typedef void (*MPL_thread_func_t) (void *data);
 void MPL_thread_create(MPL_thread_func_t func, void *data, MPL_thread_id_t * idp, int *errp);
 
 #define MPL_thread_exit()
-#define MPL_thread_self(id_) ABT_thread_self_id(id_)
-#define MPL_thread_join(id_) ABT_thread_join(id_)
-#define MPL_thread_same(id1_, id2_, same_)  ABT_thread_equal(id1_, id2_, same_)
+#define MPL_thread_self(idp_) ABT_thread_self(idp_)
+#define MPL_thread_join(idp_) ABT_thread_free(idp_)
+#define MPL_thread_same(idp1_, idp2_, same_)  ABT_thread_equal(*idp1_, *idp2_, same_)
```
Comment (hzhou) [inline src/mpl/include/mpl_thread_argobots.h]: Are these corresponding to a recent argobots API changes?

File: src/include/mpitimpl.h [hunk 2]
```diff
@@ -1192,6 +1192,8 @@ extern MPID_Thread_mutex_t mpi_t_mutex;
     do { \
         int err_; \
         MPIR_T_THREAD_CHECK_BEGIN \
+        MPID_Thread_init(&err_); \
```
Comment (hzhou) [inline src/include/mpitimpl.h]: Can argobot init be called multiple times?

File: src/include/mpitimpl.h [hunk 3]
```diff
@@ -1203,6 +1205,8 @@ extern MPID_Thread_mutex_t mpi_t_mutex;
         MPIR_T_THREAD_CHECK_BEGIN \
         MPID_Thread_mutex_destroy(&mpi_t_mutex, &err_); \
         MPIR_Assert(err_ == 0); \
+        MPID_Thread_finalize(&err_); \
+        MPIR_Assert(err_ == 0); \
```
Comment (hzhou) [inline src/include/mpitimpl.h]: Same question, and this is trickier. We can't really finalize the thread until it is absolutely the last one. I guess we'll need keep a counter inside the MPL wrapper to ensure the balance.

File: src/mpl/include/mpl_thread_argobots.h (hunk 1 above)
Comment (shintaro-iwasaki) [reply src/mpl/include/mpl_thread_argobots.h]: Thanks for taking a look at this PR!

The join change (`MPL_thread_join()`)  was made by this commit: https://github.com/pmodels/mpich/commit/5d3ec442461f576768c6cfae943a1d8808208cfe
In Argobots, join takes a thread descriptor, not a thread ID. In the Argobots case, a thread descriptor can be used as an ID, so I replaced it.

File: src/include/mpitimpl.h (hunk 2 above)
Comment (shintaro-iwasaki) [reply src/include/mpitimpl.h]: Yes. It is okay to call it multiple times (internally there's a refcount).
If it wouldn't be the case, `MPL_thread_init()` will take care of it.

File: src/include/mpitimpl.h (hunk 3 above)
Comment (shintaro-iwasaki) [reply src/include/mpitimpl.h]: Thank you! There's an internal refcount in Argobots, so in the case of Argobots, it works fine.

Currently Pthreads and Windows threads do nothing in `MPL_thread_init()` and `MPL_thread_finalize()`, but since other threading layers might be added in the future, it is a good idea to keep a counter inside the MPL wrapper.

If this change is okay, I will add a new wrapper to keep a counter as you suggested.

**Comment by shintaro-iwasaki** [comment]
I added `test: use refcount to initialize/finalize Argobots runtime`, which addresses #4422 by adopting the solution 0 (removing `MTest_init_thread_pkg()` from Argobots).

**Comment by shintaro-iwasaki** [comment]
test:jenkins/ch4/argobots

File: src/mpl/include/mpl_thread_argobots.h (hunk 1 above)
Comment (hzhou) [reply src/mpl/include/mpl_thread_argobots.h]: So argobots have both "thread id" and "thread descriptor"? Can they be converted back and forth?

File: src/include/mpitimpl.h (hunk 3 above)
Comment (hzhou) [reply src/include/mpitimpl.h]: I see. For now, I would be satisfied by just adding a comment for `MPL_thread_init` (in each implementation) noting that they need balance init/finalize. As long as it is explicitly noted, we can add that counter in MPL when necessary -- it doesn't have to be now.

File: src/mpl/include/mpl_thread_argobots.h (hunk 1 above)
Comment (shintaro-iwasaki) [reply src/mpl/include/mpl_thread_argobots.h]: Descriptor -> ID, yes.
ID -> Descriptor, no.

A thread descriptor is essentially a pointer, so two different threads can have the same value when their lifetimes are not overlapped.

In this use case, `thread descriptor` works well.

File: src/include/mpitimpl.h (hunk 3 above)
Comment (shintaro-iwasaki) [reply src/include/mpitimpl.h]: Thanks. I will add a comment.

File: src/mpl/include/mpl_thread_argobots.h (hunk 1 above)
Comment (hzhou) [reply src/mpl/include/mpl_thread_argobots.h]: I see. Thanks for the explanation.

**Comment by shintaro-iwasaki** [comment]
test:jenkins/ch4/argobots
test:jenkins/ch4/ofi

File: test/mpi/util/mtest_thread_abt.h [hunk 4]
```diff
@@ -47,6 +47,11 @@ static void MTest_abt_error(int err, const char *msg, const char *file, int line
 
 #define MTEST_NUM_XSTREAMS 2
 
+/* Reference counter */
+
+static void MTest_abt_incr_refcount(void);
+static void MTest_abt_decr_refcount(void);
```
Comment (hzhou) [inline test/mpi/util/mtest_thread_abt.h]: I understand this is only included in `mtest_thread.c`, but it is concerning to have static implementation inside a `.h` header.

File: test/mpi/util/mtest_thread_abt.h [hunk 5]
```diff
@@ -229,3 +247,39 @@ void MTest_finalize_thread_pkg()
...
+}
+
+static void MTest_abt_release_spinlock(void)
+{
+    __atomic_clear(&MTest_argobots_lock, __ATOMIC_RELEASE);
+}
+
+static void MTest_abt_incr_refcount(void)
+{
+    MTest_abt_acquire_spinlock();
```
Comment (hzhou) [inline test/mpi/util/mtest_thread_abt.h]: Will it work without the lock?

Comment (shintaro-iwasaki) [reply test/mpi/util/mtest_thread_abt.h]: Lock initialization might happen in created threads, so this spinlock is necessary.

File: test/mpi/util/mtest_thread_abt.h (hunk 4 above)
Comment (shintaro-iwasaki) [reply test/mpi/util/mtest_thread_abt.h]: In terms of coding practice, I believe non-static/inline definitions should be avoided since it often causes a "multiple definition" error.

In this specific case, static means these functions cannot be called by individual tests.

File: test/mpi/util/mtest_thread_abt.h (hunk 5 above)
Comment (hzhou) [reply test/mpi/util/mtest_thread_abt.h]: I think this is beyond simple. It adds the lazy initialization logic, then the concern of checking and initialization inside the spawned threads, then the concern of using spin-lock, and then the concern of atomics. I much prefer solution #2 at this point.

Comment (shintaro-iwasaki) [reply test/mpi/util/mtest_thread_abt.h]: Thank you. I got it. I will adopt solution #2.

**Comment by shintaro-iwasaki** [comment]
test:jenkins/ch4/argobots
test:jenkins/ch4/ofi

**Comment by shintaro-iwasaki** [comment]
test:mpich/ch4/argobots
test:mpich/ch4/ofi

**Comment by shintaro-iwasaki** [comment]
test:mpich/ch4/argobots

**Comment by shintaro-iwasaki** [comment]
test:mpich/ch4/argobots

**Comment by shintaro-iwasaki** [comment]
test:mpich/ch4/argobots

**Comment by shintaro-iwasaki** [comment]
test:mpich/ch4/argobots
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by shintaro-iwasaki** [comment]
test:mpich/ch4/argobots
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by shintaro-iwasaki** [comment]
test:mpich/ch4/argobots
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by shintaro-iwasaki** [comment]
test:mpich/ch4/argobots

**Comment by shintaro-iwasaki** [comment]
test:mpich/ch4/ofi

File: test/mpi/util/mtest_thread_abt.h (hunk 5 above)
Comment (shintaro-iwasaki) [reply test/mpi/util/mtest_thread_abt.h]: This has been fixed by #4429, so this PR no longer contains it.

File: src/include/mpitimpl.h (hunk 2 above)
Comment (shintaro-iwasaki) [reply src/include/mpitimpl.h:1195]: This concern is mentioned in `src/mpl/include/mpl_thread_argobots.h`.

**Comment by shintaro-iwasaki** [comment]
Finally all checks passed. @hzhou could you please take a look at this PR when you have time?

**Comment by hzhou** [comment]
> Finally all checks passed. @hzhou could you please take a look at this PR when you have time?

Sure, I'll review it tomorrow. Thank you for the effort.

File: test/mpi/threads/spawn/th_taskmaster.c [hunk 6]
```diff
@@ -101,6 +101,10 @@ int main(int argc, char *argv[])
 #endif /* USE_THREADS */
 
 #ifdef USE_THREADS
+        /* Initialize the thread package. It should not be initialized via
+         * MTest_Init_thread since MTest_Finalize cannot be called. */
```
Comment (hzhou) [inline test/mpi/threads/spawn/th_taskmaster.c:105]: It is because both `MTest_Init_thread` and `MTest_Finalize` _are_ not called rather than _cannot_ be called, right?

Comment (shintaro-iwasaki) [reply test/mpi/threads/spawn/th_taskmaster.c:105]: You are right. I will change the comment. Thanks a lot for reviewing this PR!

Comment (shintaro-iwasaki) [reply test/mpi/threads/spawn/th_taskmaster.c:105]: @hzhou I fixed the comment.

File: test/mpi/threads/comm/idup_deadlock.c [hunk 7]
```diff
@@ -41,6 +41,7 @@ MTEST_THREAD_RETURN_TYPE test_comm_dup(void *arg)
             wait = 0;
             for (i = 0; i < NUM_THREADS; i++)
                 wait += start_idup[i];
+            MTest_thread_yield();
```
Comment (hzhou) [inline test/mpi/threads/comm/idup_deadlock.c:44]: @shintaro-iwasaki `MTest_thread_yield()` is not in a header file that is included in `idup_deadlock.c`, causing a compiler warning. Could you fix it?
