### PR TITLE
finalize: allow non-collective finalizing

### LINKED ISSUE #5553: ch4/ofi/psm2: psm2_ep_connect intermittently failing for some coll tests
Some collective tests are failing intermittently, during finalize step. Problem reported during a local debug run.

Config: psm2 + multi-vci + SEP (--disable-ofi-domains)

Error:
```
libfabric:34420:psm2:av:psmx2_epid_to_epaddr():230<warn> psm2_ep_connect retured error Operation timed out, remote epid=1f0302.If it is a timeout
```
tests: `./coll/opbxor 5` `./coll/bcastzerotype 5 MPIR_CVAR_BCAST_DEVICE_COLLECTIVE=0 MPIR_CVAR_BCAST_INTRA_ALGORITHM=scatter_recursive_doubling_allgather` `./init/session_mult_init 4` etc.

Finding: Problem occurs during test finalize, rank 0 is still at `MPI_Reduce` trying to connect to a remote ep to receive data whereas other ranks have send their data and proceeded to `MPI_Finalize`. Rank 0 tries to connect to an already closed ep 

Logs from test bcastzerotype:
```
[4] libfabric:62990:psm2:core:psmx2_trx_ctxt_free():190<info> epid: 0000000000040e02 (tx+rx)
[0] libfabric:62986:psm2:av:psmx2_epid_to_epaddr():230<warn> psm2_ep_connect retured error Operation timed out, remote ep
```

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
While posing a barrier at finalize is convenient, it is not always desirable or will work. Some process may need exit early or even call MPI_Abort without MPI_Finalize. Only some applications may need cater to this behavior but it is a sufficient reason for us to at least provide a mechanism allow non-collective finalizing.

## Work in progress
* [x] Init_shm_barrier in MPIDU_Init_shm_finalize
* [x] add MPIR_CVAR_NO_COLLECTIVE_FINALIZE
* [x] Avoid barriers in ofi_finalzie
* [x] Add `psm2` to the list of providers that require `MPIR_pmi_barrier` at finalize
       Fixes #5553
[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch3/sock

File: src/mpid/ch3/channels/nemesis/src/mpid_nem_init.c [hunk 1]
```diff
@@ -409,6 +409,8 @@ MPID_nem_init(int pg_rank, MPIDI_PG_t *pg_p, int has_parent ATTRIBUTE((unused)))
 
     mpi_errno = MPIDI_CH3_SHM_Init();
     MPIR_ERR_CHECK(mpi_errno);
+    mpi_errno = MPIDU_Init_shm_barrier();
+    MPIR_ERR_CHECK(mpi_errno);
```
Comment (raffenet) [inline src/mpid/ch3/channels/nemesis/src/mpid_nem_init.c:413]: what's the reasoning for adding another shm barrier here?

**Review by raffenet — COMMENTED** [review]
Just one comment, otherwise looks good.

File: src/mpid/ch3/channels/nemesis/src/mpid_nem_init.c (hunk 1 above)
Comment (hzhou) [reply src/mpid/ch3/channels/nemesis/src/mpid_nem_init.c:413]: We need a barrier before `MPIDU_Init_shm_finalize`. In ch3, all init_shm usages are in MPI_Init. Having a shm barrier here ensures processes won't enter finalize when init_shm is still in use.

**Review by raffenet — APPROVED** [review]
