### PR TITLE
mpit: add global config file

### LINKED ISSUE #6501: Have MPICH read from a global config file
We have customers who would like to set default values for MPICH CVARs that are difficult for their users to override. As an example, there are GPU variables that if set incorrectly, or not set at all, can result in machine hangs. They would like MPICH to check for variable settings upon launch from a file, instead of just checking the user's environment. While they could put these settings into existing files in /etc to modify user environments, they've had problems with users overriding the values they're supposed to use.
The attached patch against MPICH 3.4a2 is one way we could accomplish this. It has MPI_Init() read from /etc/mpich.conf. The files is organized as lines of text formatted as KEY=VALUE. By default, if KEY is already set, then the existing value is kept. If a line in the file is formatted as KEY:force=VALUE, then the VALUE overrides any existing value. 
[mpi.patch](https://github.com/pmodels/mpich/files/11389850/mpi.patch)

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
Add a mechanism to set a global config file to be loaded at init time. The config file has a ":force" syntax to allow system admin to set variables that are difficult for user to overwrite.

Fixes #6501 

[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

File: src/mpi_t/mpit_initthread.c [hunk 1]
```diff
@@ -5,6 +5,52 @@
...
+            fprintf(stderr, "Error parsing config file %s line %d: %s\n", fname, lineno, line);
+            goto err;
+        }
+        /* If KEY:force=VALUE, then write prior values */
+        if ((spot = strstr(key, ":force"))) {
+            force = true;
+            *spot = '\0';
+        }
+
+        already = getenv(key);
```
Comment (RaymondMichael) [inline src/mpi_t/mpit_initthread.c:43]: already isn't used in this patch. In my original patch, I used it to determine whether we should print some debugging info.

File: maint/extractcvars [hunk 2]
```diff
@@ -252,6 +252,10 @@ int ${fn_ns}_init(void)
     MPIR_T_cvar_value_t defaultval;
 
     int debug = 0;
+    rc = MPL_env2bool("MPICH_DEBUG_CVARS", &debug);
+    MPIR_ERR_CHKANDJUMP1((-1 == rc),mpi_errno,MPI_ERR_OTHER,"**envvarparse","**envvarparse %s","MPICH_DEBUG_CVARS");
+    rc = MPL_env2bool("MPIR_PARAM_DEBUG_CVARS", &debug);
+    MPIR_ERR_CHKANDJUMP1((-1 == rc),mpi_errno,MPI_ERR_OTHER,"**envvarparse","**envvarparse %s","MPIR_PARAM_DEBUG_CVARS");
```
Comment (RaymondMichael) [inline maint/extractcvars:258]: I'm not sure how these are related to the other code changes

Comment (hzhou) [reply maint/extractcvars:258]: They are not. I noticed that we only checked `MPIR_CVAR_DEBUG_CVARS`, while all other cvars can also use `MPICH_` and `MPIR_PARAM_` suffixes, so I patch it for consistency.

File: src/mpi_t/mpit_initthread.c (hunk 1 above)
Comment (RaymondMichael) [reply src/mpi_t/mpit_initthread.c:43]: I'm going to be out the next three weeks. If you cleaned this up I'd approve it.

Comment (hzhou) [reply src/mpi_t/mpit_initthread.c]: Done.

**Review by RaymondMichael — APPROVED** [review]

**Review by raffenet — APPROVED** [review]
