### PR TITLE
ROMIO: Preliminary support for MPI-4 large-count user-defined datatypes

### LINKED ISSUE #6121: ROMIO and MPI-4: Broken large-count datatype decoding
### Description
Current mpi4py@master use the large-count MPI-4 APIs exclusively for all operations, including the construction of user-defined datatypes. However, looks like the datatype decoding infrastructure in ROMIO was not updated to cope with datatypes created via the large-count MPI-4 APIs. 

### Reproducer
```python
import numpy as np
from mpi4py import MPI
from mpi4py.util import dtlib

comm = MPI.COMM_WORLD
size = comm.Get_size()
rank = comm.Get_rank()

mode = 0
mode |= MPI.MODE_RDWR
mode |= MPI.MODE_CREATE
mode |= MPI.MODE_DELETE_ON_CLOSE
file = MPI.File.Open(comm, "/tmp/data", mode)
file.Set_size(0)

datatype = MPI.DOUBLE
subarray = datatype.Create_subarray(
    sizes=[size, 3],
    subsizes=[1, 3],
    starts=[rank, 0],
    order=MPI.ORDER_C,
).Commit()

dtype = dtlib.to_numpy_dtype(datatype)
data = np.full((1, 3), rank, dtype=dtype)

file.Set_view(0, datatype, subarray)
file.Write_all(data)

comm.Barrier()
file.Sync()
comm.Barrier()

file.Set_view(0, datatype, subarray)
file.Read_all(data)
assert np.allclose(data, rank)

subarray.Free()
file.Close()
```

```
$ mpiexec --prepend-rank -n 2 python test_io_array.py
[0] Out of memory in file ../../../../src/mpi/romio/adio/common/flatten.c, line 944
[0] Abort(1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[0] Out of memory in file ../../../../src/mpi/romio/adio/common/flatten.c, line 946
[0] Abort(1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[0] 
[0] python:788935 terminated with signal 11 at PC=7f9bc47e9c3c SP=7ffcb6ceabe0.  Backtrace:
...
[0] /home/devel/mpi/mpich/dev/lib/libmpi.so.0(PMPI_File_set_view+0x5f6)[0x7f9bc47b59d8]
...
[1] Out of memory in file ../../../../src/mpi/romio/adio/common/flatten.c, line 944
[1] Abort(1) on node 1 (rank 1 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
[1] Out of memory in file ../../../../src/mpi/romio/adio/common/flatten.c, line 946
[1] Abort(1) on node 1 (rank 1 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
[1] 
[1] python:788936 terminated with signal 11 at PC=7f45e031bc3c SP=7ffe9bc3d930.  Backtrace:
...
[1] /home/devel/mpi/mpich/dev/lib/libmpi.so.0(PMPI_File_set_view+0x5f6)[0x7f45e02e79d8]
...
```

CC: @mengaldo

### PR DESCRIPTION
**Pull request by dalcinl**
## Pull Request Description

Fixes #6121.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

File: src/mpi/romio/adio/common/utils.c [hunk 1]
```diff
@@ -6,6 +6,47 @@
...
+    MPI_Count ni, na, nc, nt;
+    ret = MPI_Type_get_envelope_c(datatype, &ni, &na, &nc, &nt, combiner);
+#else
+    int ni, na, nt;
+    ret = MPI_Type_get_envelope(datatype, &ni, &na, &nt, combiner);
+#endif
+    return ret;
+}
+
+int ADIOI_Type_ispredef(MPI_Datatype datatype, int *flag)
```
Comment (hzhou) [inline src/mpi/romio/adio/common/utils.c:22]: How about directly return the boolean value?

File: src/mpi/romio/adio/common/utils.c [hunk 2]
```diff
@@ -6,6 +6,47 @@
...
+            *flag = 1;
+            break;
+        default:
+            *flag = 0;
+            break;
+    }
+    return ret;
+}
+
+int ADIOI_Type_free(MPI_Datatype * datatype)
```
Comment (hzhou) [inline src/mpi/romio/adio/common/utils.c:40]: How about rename it to `ADIOI_Type_free_ifnotpredef`?

File: src/mpi/romio/adio/common/utils.c (hunk 1 above)
Comment (dalcinl) [reply src/mpi/romio/adio/common/utils.c:22]: Well, most of the code in ROMIO does not check error codes. That's obviously bad practice, so I did not want to add my own contribution. Additionally, you already have the query routine `ADIOI_Datatype_iscontig()` with the same signature as this one.

File: src/mpi/romio/adio/common/utils.c (hunk 2 above)
Comment (dalcinl) [reply src/mpi/romio/adio/common/utils.c:40]: Again, I was following the pattern of `ADIOI_Datatype_iscontig()`. I'm used to write predicate routines that check for the "positive" property, not the opposite (`is_<something>` rather than `is_not_<something>`), although I admit that is ultimately a matter of style and personal preference. 

If you want to change it anyway, I'll surrender. But please look the code around in ROMIO and confirm whether your  choice follows the established patterns elsewhere.

File: src/mpi/romio/adio/common/utils.c (hunk 1 above)
Comment (dalcinl) [reply src/mpi/romio/adio/common/utils.c:22]: Alternatively, we could implement your suggestion, and add a new one `ADIOI_Type_iscontig()` wrapping `ADIOI_Datatype_iscontig()`.

Comment (hzhou) [reply src/mpi/romio/adio/common/utils.c:22]: Don't worry about it. We can always refactor later.

File: src/mpi/romio/adio/common/utils.c (hunk 2 above)
Comment (hzhou) [reply src/mpi/romio/adio/common/utils.c:40]: I just want to reflect the semantics in the function name. The semantics of the routine is "free the datatype if it is not a predefined type", right? Just `ADIOI_Type_free` makes people wonder.

Comment (dalcinl) [reply src/mpi/romio/adio/common/utils.c:40]: > Just ADIOI_Type_free makes people wonder.

Oh. Sorry, I totally misunderstood your comment. I misread, I thought you were talking about `ADIOI_Type_ispredef`!

I believe you are right, `ADIOI_Type_free` is not explicit enough regarding its intention. I don't like your naming 100%, but I cannot come up with anything better, so if you still want it, I can implement your suggestion. Should I?

Comment (hzhou) [reply src/mpi/romio/adio/common/utils.c:40]: I certainly would like the name be more explicit.

**Comment by hzhou** [comment]
> @hzhou I just noticed that `src/mpi/romio/adio/ad_pvfs2/ad_pvfs2_io_dtype.c` uses `MPI_COMBINER_HINDEXED_BLOCK` (added in MPI-3.0) without protecting its use with the preprocessor guard `#if defined HAVE_DECL_MPI_COMBINER_HINDEXED_BLOCK && HAVE_DECL_MPI_COMBINER_HINDEXED_BLOCK`.
> 
> Should this be fixed, or you guys no longer care about ROMIO being able to compile with pre MPI-3.0 implementations? If that is the case, then perhaps all the preprocessor guards related to `MPI_COMBINER_DUP` and `MPI_Type_dup` should be cleaned up.

I would suggest let's fix it (add ifdef-guard) for now. We can make a separate PR if we decide to remove these guards altogether.

File: src/mpi/romio/adio/common/utils.c (hunk 2 above)
Comment (dalcinl) [reply src/mpi/romio/adio/common/utils.c]: I renamed it to `MPI_Type_dispose()` and added a comment explaining its semantics. If you do not like my new name, then I'll give up trying to be inventive, and I'll just go your way.

**Comment by hzhou** [comment]
test:mpich/warnings
test:mpich/ch3/tcp
test:mpich/ch4/most

**Comment by dalcinl** [comment]
@hzhou I force-pushed to fixed a minor issue catched by the mpich-warnings check. Just in case, run tests again.

**Comment by hzhou** [comment]
test:mpich/warnings
test:mpich/ch3/tcp
test:mpich/ch4/most

File: src/mpi/romio/adio/common/ad_close.c [hunk 3]
```diff
@@ -97,13 +97,8 @@ void ADIO_Close(ADIO_File fd, int *error_code)
...
 
-    MPI_Type_get_envelope(fd->etype, &i, &j, &k, &combiner);
-    if (combiner != MPI_COMBINER_NAMED)
-        MPI_Type_free(&(fd->etype));
-
-    MPI_Type_get_envelope(fd->filetype, &i, &j, &k, &combiner);
-    if (combiner != MPI_COMBINER_NAMED)
-        MPI_Type_free(&(fd->filetype));
+    ADIOI_Type_dispose(&(fd->etype));
+    ADIOI_Type_dispose(&(fd->filetype));
```
Comment (roblatham00) [inline src/mpi/romio/adio/common/ad_close.c:102]: good cleanup.  ROMIO dates back to the "function calls are expensive" era, so there are lots of opportunities to add back in some utilities.  thanks.

**Review by roblatham00 — APPROVED** [review]
This is some of the oldest most fragile code in ROMIO.  I think your approach is good, and reading the code looks like a few drop-in replacements for new MPI-4 routines.     I'd like to see a lot more kinds of datatypes hit these paths .. .perhaps mpi4py has already covered these paths for us?

**Review by hzhou — APPROVED** [review]
LGTM

File: src/mpi/romio/adio/common/ad_close.c (hunk 3 above)
Comment (hzhou) [reply src/mpi/romio/adio/common/ad_close.c:102]: I am testing an ideal of exposing MPICH typerep functionality as MPIX functions, in particular, two -
* `MPIX_Type_iov(datatype, iov_offset, iov[], max_iov_len, *actual_iov_len)`
* `MPIX_Type_iov_len(datatype, max_iov_bytes, *iov_len)`

With these two, user can query and retrieve contiguous segments at any offset. Thus ROMIO can skip maintaining the flat list. The flat list code are not only complex, it can also be very slow and potentially use up the memory.

Comment (dalcinl) [reply src/mpi/romio/adio/common/ad_close.c:102]: > ROMIO dates back to the "function calls are expensive" era

Good old times... Now kiddos code Python for a living!

**Comment by dalcinl** [comment]
> I'd like to see a lot more kinds of datatypes hit these paths .. .perhaps mpi4py has already covered these paths for us?

@roblatham00 I'm not following. What kind of datatypes and paths are you talking about? 

@hzhou's idea of exposing typerep info to ROMIO is great, as it is a definitive solution for large count support within MPICH. 

If you guys want to keep maintaining the MPI-agnostic paths for ROMIO to support third-party MPI impls, then at some point a few things here and there have to be refactor to properly handle MPI_Count. This PR supports datatypes created with the new MPI-4 large-count APIs, but as soon as one of these datatypes uses a MPI_Count value larger than the 2GB 32bit limit, ROMIO will abort.

**Comment by roblatham00** [comment]
oh I just mean our test suite mostly creates VECTOR, one or two DARRAY and RESIZED tests.  Weird STRUCT types or deeply nested "INDEX of VECTOR of STRUCT of CONTIG of... " -- I only see those from the HDF5 test suite.

**Comment by dalcinl** [comment]
@roblatham00 I added some stuff in [mpi4py testsuite](https://github.com/mpi4py/mpi4py/blob/master/test/test_io.py#L424). It is far from comprehensive, but it covers almost all `MPI_COMBINER_XXX` and C datatypes. In fact, I coded up all these new tests to validate the code changes I submitted to this PR. An obvious omission is subarray and darray with Fortran order. It will be in my TODO list to validate an upcoming PR to MPICH to truly support large counts.

PS: I hope MPICH is running mpi4py testsuite from git master branch. Otherwise, you will be missing stuff.
