### PR TITLE
bug: fix enable memory tracing and pmix together

### LINKED ISSUE #3832: Build failure with `--enable-g=all` and `pmix.h`
@zhenggb72 has reported that when building with PMIX and `--enable-g=all`, the compilation fails with the following error:

```
/opt/ohpc/admin/pmix/include/pmix_common.h: In function 'pmix_value_destruct':
/opt/ohpc/admin/pmix/include/pmix_common.h:2074:34: warning: character constant too long for its type
             free((m)->data.string);
                                  ^
In file included from ./src/include/mpiimpl.h:183:0,
                 from src/mpi/attr/attr_delete.c:8:
./src/include/mpir_mem.h:92:27: warning: statement with no effect [-Wunused-value]
 #define free(a)           'Error use MPL_free'   :::
                           ^
```

After looking at the code of src/mpl/include/mpl_trmem.h, I think the problem is due to the `#define` of the `free()` function when memory tracing is enabled. What happens is `pmix.h` includes `pmix_common.h` which has macros that calls `free()`. In this case, these invocations will be incorrectly replaced by our `#define` and cause the build to fail.

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

This PR fixes issue #3832: build failure with `--enable-g=all --with-pmix=path/to/pmix --with-device=ch4:ofi`.

The problem was `pmix` header files, in particular `pmix_common.h` contains naked calls to memory functions such as `malloc`, `free`. Some of them are in inline functions; many of them are in macros. When memory tracing requires all memory functions be called through `MPL_xxx` wrappers. With `--enable-g=all` or `--enable-g=mem`, we raise errors for any naked call to memory functions.

This PR makes sure the `pmix` headers are included before `mpl.h`. This works with memory function inside inline functions as they are parsed in the order of occurrence. However, the macros are expanded at usage, therefore, will still raise error. Upstream (https://github.com/pmix/pmix/issues/1312) is fixing this by wrapping all memroy functions inside inline functions. The combination of this PR that upstream fix will fix the issue.

## Expected Performance Changes

Minimal.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)

Fixes #3832 

* [x] Confirm whitespace/style checkers are happy (or has a good reason for being bad)
* [x] Commits are self-contained and do not do two things at once
* [x] Remove xfail from the test suite when fixing a test
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Add comments such that someone without knowledge of the code could understand
* [x] Add Devel Docs in the `doc/` directory for any new code design
* [x] Passes tests (included warning check)

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/custom --enable-g=all --with-pmix=/nfs/gce/projects/login-pmrs/opt/pmix

**Comment by hzhou** [comment]
test:mpich/custom --enable-g=all --with-pmix=/nfs/gce/projects/login-pmrs/opt/pmix
env: MPIEXEC=/nfs/gce/projects/login-pmrs/opt/openmpi-3.0.0/bin/mpiexec -oversubscribe

**Comment by hzhou** [comment]
test:mpich/custom --enable-g=all --with-pmix=/nfs/gce/projects/login-pmrs/opt/pmix
env: MPIEXEC=/nfs/gce/projects/login-pmrs/opt/openmpi-3.0.0/bin/mpiexec -oversubscribe

**Comment by hzhou** [comment]
test:mpich/custom --enable-g=all --with-pmix=/nfs/gce/projects/login-pmrs/opt/pmix
env: MPIEXEC=/nfs/gce/projects/login-pmrs/opt/openmpi-3.0.0/bin/mpiexec -oversubscribe

**Comment by hzhou** [comment]
test:mpich/custom --enable-g=all --with-pmix=/nfs/gce/projects/login-pmrs/opt/pmix
env: MPIEXEC=/nfs/gce/projects/login-pmrs/opt/openmpi-3.0.0/bin/mpiexec -oversubscribe

**Comment by hzhou** [comment]
Trouble-shooting: 

test:mpich/custom --with-pmix=/nfs/gce/projects/login-pmrs/opt/pmix-2.1.1
env: MPIEXEC=/nfs/gce/projects/login-pmrs/opt/openmpi-3.0.0/bin/mpiexec -oversubscribe

**Comment by hzhou** [comment]
Reset back one merge in PMIx:

test:mpich/custom --enable-g=all --with-pmix=/nfs/gce/projects/login-pmrs/opt/pmix
env: MPIEXEC=/nfs/gce/projects/login-pmrs/opt/openmpi-3.0.0/bin/mpiexec -oversubscribe
env: skip_test=true

**Comment by hzhou** [comment]
Reset back one merge in PMIx:

test:mpich/custom --with-pmix=/nfs/gce/projects/login-pmrs/opt/pmix
env: MPIEXEC=/nfs/gce/projects/login-pmrs/opt/openmpi-3.0.0/bin/mpiexec -oversubscribe
env: skip_test=true

**Comment by hzhou** [comment]
Trying OMPI master and PMIx master:

test:mpich/custom --enable-g=all --with-pmix=/nfs/gce/projects/login-pmrs/opt/pmix
env: MPIEXEC=/nfs/gce/projects/login-pmrs/opt/ompi/bin/mpiexec -oversubscribe
env: skip_test=true

**Comment by hzhou** [comment]
test:mpich/custom --enable-g=all --with-pmix=/nfs/gce/projects/login-pmrs/opt/pmix
env: MPIEXEC=/nfs/gce/projects/login-pmrs/opt/ompi/bin/mpiexec -oversubscribe

**Comment by hzhou** [comment]
test:mpich/custom --enable-g=all --with-pmix=/nfs/gce/projects/login-pmrs/opt/pmix
env: MPIEXEC=/nfs/gce/projects/login-pmrs/opt/ompi/bin/mpiexec -oversubscribe

**Comment by hzhou** [comment]
test:jenkins/ch4/pmi

**Comment by hzhou** [comment]
@raffenet You fixed the test failures in `ch4/pmi` in another PR, right?

**Comment by raffenet** [comment]
Yes, all the tests in those results are resolved in master.

**Comment by hzhou** [comment]
Rebased to master, retest:

test:jenkins/ch4/pmi

**Comment by hzhou** [comment]
test:mpich/custom --enable-g=all --with-pmix=/nfs/gce/projects/login-pmrs/opt/pmix
env: MPIEXEC=/nfs/gce/projects/login-pmrs/opt/ompi/bin/mpiexec -oversubscribe

**Comment by hzhou** [comment]
@raffenet The PR is ready for your review. The 3 failures in custom tests are all xfails that the custom tests failed apply.

File: src/mpid/ch4/shm/src/shm_impl.c [hunk 1]
```diff
@@ -4,11 +4,8 @@
  *      See COPYRIGHT in top-level directory.
  */
 
-#include "mpl.h"
-
-MPL_SUPPRESS_OSX_HAS_NO_SYMBOLS_WARNING;
-
 #include "posix_impl.h"
+MPL_SUPPRESS_OSX_HAS_NO_SYMBOLS_WARNING;
```
Comment (yfguo) [inline src/mpid/ch4/shm/src/shm_impl.c]: Do we really need to move this line here? Wouldn't removing the inclusion of mpl.h be sufficient?

Comment (hzhou) [reply src/mpid/ch4/shm/src/shm_impl.c]: It needs to happen after "#include <mpl.h>", but we need control when <mpl.h> gets included, ie ensure it is after `mpix.h`. Therefore it needs to move after "posix_impl.h" which includes "mpiimpl.h", which include mpl.h there.
