### PR TITLE
pmi: fallback to PMI_Barrier when applicable

### LINKED ISSUE #7478: [mpi4py] gforker failures at MPI initialization
Maybe the previous gforker fixes were not enough?

**ch3:sock** https://github.com/mpi4py/mpi4py-testing/actions/runs/15865555850/job/44731637088
```
Fatal error in internal_Init_thread: Other MPI error, error stack:
internal_Init_thread(71)............: MPI_Init_thread(argc=(nil), argv=(nil), required=3, provided=0x7ffd3076b7d8) failed
MPII_Init_thread(204)...............: 
MPIR_pmi_init(183)..................: 
MPIR_build_nodemap(146).............: 
MPIR_pmi_build_nodemap_fallback(345): 
pmi_publish_node_id(301)............: 
pmi1_barrier(120)...................: PMI_Barrier returned -1
```

**ch3:nemesis** https://github.com/mpi4py/mpi4py-testing/actions/runs/15865555850/job/44731637091
```
Fatal error in internal_Init_thread: Other MPI error, error stack:
internal_Init_thread(71)............: MPI_Init_thread(argc=(nil), argv=(nil), required=3, provided=0x7ffde0db5918) failed
MPII_Init_thread(204)...............: 
MPIR_pmi_init(183)..................: 
MPIR_build_nodemap(146).............: 
MPIR_pmi_build_nodemap_fallback(345): 
pmi_publish_node_id(301)............: 
pmi1_barrier(120)...................: PMI_Barrier returned -1
Fatal error in internal_Init_thread: Other MPI error, error stack:
internal_Init_thread(71)............: MPI_Init_thread(argc=(nil), argv=(nil), required=3, provided=0x7ffc46f98338) failed
MPII_Init_thread(204)...............: 
MPIR_pmi_init(183)..................: 
MPIR_build_nodemap(146).............: 
MPIR_pmi_build_nodemap_fallback(345): 
pmi_publish_node_id(301)............: 
pmi1_barrier(120)...................: PMI_Barrier returned -1
```

**ch4:ofi** https://github.com/mpi4py/mpi4py-testing/actions/runs/15865555850/job/44731637092
```
Abort(3293199): Fatal error in internal_Init_thread: Other MPI error, error stack:
internal_Init_thread(71)............: MPI_Init_thread(argc=(nil), argv=(nil), required=3, provided=0x7ffeca689818) failed
MPII_Init_thread(204)...............: 
MPIR_pmi_init(183)..................: 
MPIR_build_nodemap([14](https://github.com/mpi4py/mpi4py-testing/actions/runs/15865555850/job/44731637092#step:17:15)6).............: 
MPIR_pmi_build_nodemap_fallback(345): 
pmi_publish_node_id(301)............: 
pmi1_barrier(120)...................: PMI_Barrier returned -1
Abort(875708431): Fatal error in internal_Init_thread: Other MPI error, error stack:
internal_Init_thread(71)............: MPI_Init_thread(argc=(nil), argv=(nil), required=3, provided=0x7ffc3da422c8) failed
MPII_Init_thread(204)...............: 
MPIR_pmi_init([18](https://github.com/mpi4py/mpi4py-testing/actions/runs/15865555850/job/44731637092#step:17:19)3)..................: 
MPIR_build_nodemap(146).............: 
MPIR_pmi_build_nodemap_fallback(345): 
pmi_publish_node_id(301)............: 
pmi1_barrier(1[20](https://github.com/mpi4py/mpi4py-testing/actions/runs/15865555850/job/44731637092#step:17:21))...................: PMI_Barrier returned -1
```

**ch4:ucx** https://github.com/mpi4py/mpi4py-testing/actions/runs/15865555850/job/44731637094
In this case `MPI_Init_thread` seems to be OK. Later on, some spawn test fails (deadlock).
```
testArgsBad (test_spawn.TestSpawnMultipleSelf.testArgsBad) ... ok
[1750817495.414615] [pkrvmxyh4eaekms:166143:0]         address.c:944  UCX  ERROR failed to unpack address, invalid bandwidth 0.00
testArgsOnlyAtRoot (test_spawn.TestSpawnMultipleSelf.testArgsOnlyAtRoot) ... Abort(139608079) on node 1: Fatal error in internal_Init_thread: Other MPI error, error stack:
internal_Init_thread(71)..............: MPI_Init_thread(argc=(nil), argv=(nil), required=3, provided=0x7fff4de7ff58) failed
MPII_Init_thread(284).................: 
MPIR_init_comm_world(35)..............: 
MPIR_Comm_commit(820).................: 
MPID_Comm_commit_pre_hook(145)........: 
MPIDI_UCX_mpi_comm_commit_pre_hook(19): 
MPIDI_UCX_comm_addr_exchange(117).....:  ucx function returned with failed status(ucx_init.c 117 MPIDI_UCX_comm_addr_exchange Invalid parameter)
```

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

This commit reverts the logic in b661404e8, rather than alias PMI_Barrier to PMI_Barrier_group, fallback to PMI_Barrier whenever it is applicable. At the wire protocol layer, PMI_Barrier should have the group attribute omitted for backward compatibility. This makes the older PMI servers such as gforker still work.

Fixes #7478
[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/pmi

**Comment by hzhou** [comment]
test:mpich/pmi

File: src/pmi/src/pmi_v1.c [hunk 1]
```diff
@@ -324,7 +340,11 @@ PMI_API_PUBLIC int PMI_Barrier_group(const int *group, int count, const char *ta
     }
 
     char *group_str;
-    if (group == PMI_GROUP_WORLD) {
+    if (group == PMI_GROUP_WORLD && !tag && !PMIU_is_threaded) {
```
Comment (raffenet) [inline src/pmi/src/pmi_v1.c:345]: isn't `PMIU_is_threaded=1` unconditional currently? should we disable after getting the version back from the server in `PMI_Init`?

Comment (raffenet) [reply src/pmi/src/pmi_v1.c:345]: Oh, this doesn't actually get called during `PMI_Barrier` anymore so it doesn't matter for that use-case. I see how it works now.

Comment (hzhou) [reply src/pmi/src/pmi_v1.c:345]: Good suggestion!

Comment (raffenet) [reply src/pmi/src/pmi_v1.c:345]: I suppose that disabling thread support based on server version could allow sessions apps using the world process group to function with gforker?

Comment (hzhou) [reply src/pmi/src/pmi_v1.c:345]: Please review the last commit.

**Comment by hzhou** [comment]
test:mpich/pmi

pmi-1 ✔️  Will address other failures (pmi2, pmix) separately.

File: src/pmi/src/pmi_v1.c (hunk 1 above)
Comment (hzhou) [reply src/pmi/src/pmi_v1.c:345]: > I suppose that disabling thread support based on server version could allow sessions apps using the world process group to function with gforker?

```
if (group == PMI_GROUP_WORLD && !tag && !PMIU_is_threaded) {
    /* Backward-compatible PMI_Barrier */
    pmi_errno = PMI_Barrier();
}
```
`MPI_Comm_create_from_group` will have `tag` set, so it still won't work    But setting `MPIR_CVAR_PMI_DISABLE_GROUP` (https://github.com/pmodels/mpich/pull/7354/commits/dd1a84e139ece2f21b19ee02c9da9da7b9c17433)  will fallback to `PMI_Barrier` and make sessions over world work
