### PR TITLE
ch4: fix accept/connect not ignoring args on non-root ranks

### LINKED ISSUE #5149: Accept/Connect failures with ch4:ofi
I'm getting some Accept/Connect failures (segfaults) in mpi4py testsuite. Valgrind output is not clean. I get similar valgrind output with Spawn tests (with deadlock under valgrind). A a simple pure C code using MPI_Comm_spawn is also not clean under valgrind, similar output.

Any tips on how to provide more information to help sort this out?

```
==490939== Conditional jump or move depends on uninitialised value(s)
==490939==    at 0x14CE5687: sock_cq_readerr (in /home/devel/mpi/mpich/3.4.1-ch4-ofi/lib/libmpi.so.12.1.10)
==490939==    by 0x1477A58A: fi_cq_readerr (fi_eq.h:406)
==490939==    by 0x1477A58A: MPIDI_OFI_handle_cq_error (ofi_events.c:912)
==490939==    by 0x1477CB38: MPIDI_OFI_progress (ofi_progress.c:81)
==490939==    by 0x1476AAB0: dynproc_exchange_map (ofi_spawn.c:384)
==490939==    by 0x1476CE3A: MPIDI_OFI_mpi_comm_accept (ofi_spawn.c:759)
==490939==    by 0x14726322: MPID_Comm_accept (ch4_spawn.c:194)
==490939==    by 0x14604966: MPIR_Comm_accept_impl (comm_accept.c:30)
==490939==    by 0x14604966: PMPI_Comm_accept (comm_accept.c:103)
...
```

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

The port_name parameter in MPI_Comm_connect and MPI_Comm_accept is only needed by root rank and should be ignored by other ranks. The current code assumes the parameter is available for all processes, which is wrong. This PR fixes it by having root process proceed with the connection and then broadcast the results (`errno`) to children.

Fixes #5149
[skip warnings]
## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/spellcheck

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

File: src/mpid/ch4/src/ch4_spawn.c [hunk 1]
```diff
@@ -68,10 +69,22 @@ int MPID_Comm_spawn_multiple(int count, char *commands[], char **argvs[], const
...
+    }
     MPIR_Errflag_t errflag = MPIR_ERR_NONE;
-
-    mpi_errno = MPIR_Bcast(&spawn_error, 1, MPI_INT, root, comm_ptr, &errflag);
+    mpi_errno = MPIR_Bcast(bcast_ints, 2, MPI_INT, root, comm_ptr, &errflag);
     MPIR_ERR_CHECK(mpi_errno);
+    if (comm_ptr->rank != root) {
+        total_num_processes = bcast_ints[0];
+        spawn_error = bcast_ints[1];
+        MPIR_Assert(total_num_processes > 0 && total_num_processes < 10);
```
Comment (raffenet) [inline src/mpid/ch4/src/ch4_spawn.c:83]: Why less than 10?

**Review by raffenet — COMMENTED** [review]
This seems good. Just the one comment.

File: src/mpid/ch4/src/ch4_spawn.c [hunk 2]
```diff
@@ -81,7 +94,7 @@ int MPID_Comm_spawn_multiple(int count, char *commands[], char **argvs[], const
         MPIR_ERR_CHECK(mpi_errno);
 
         /* FIXME: Are we only checking pmi_errcodes[0] and ignoring the rest? */
-        for (i = 0; i < total_num_processes; i++) {
+        for (int i = 0; i < total_num_processes; i++) {
             errcodes[i] = pmi_errcodes[0];
```
Comment (raffenet) [inline src/mpid/ch4/src/ch4_spawn.c:98]: not from this PR, but should this be?
```suggestion
            errcodes[i] = pmi_errcodes[i];
```

File: src/mpid/ch4/src/ch4_spawn.c (hunk 1 above)
Comment (hzhou) [reply src/mpid/ch4/src/ch4_spawn.c:83]: Oops, it is a leftover from debugging. I will delete this line. Good catch!

File: src/mpid/ch4/src/ch4_spawn.c (hunk 2 above)
Comment (hzhou) [reply src/mpid/ch4/src/ch4_spawn.c:98]: The "FIXME" was also from me last time I looked at this code. I agree with you. Let me change it.

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Review by raffenet — APPROVED** [review]
