### PR TITLE
coll: fix additional neighbor_alltoall algorithms

### LINKED ISSUE #2194: bug: MPI_Neighbor_alltoall
**Originally by _Rolf Rabenseifner_ on 2014-10-31 10:09:16 -0500**

---

there seems to be wrong communication in all three MPI libraries [CrayMPT, OpenMPI, and MPICH](mpich tested only by using CrayMPT).
The bug seems to exist only for periodic Cartesian dimensions
with size 1 and 2. Here, the sequence of the two receive buffers
is wrong.

---

Bug-Report by Rolf Rabenseifner for
- mpich:   PrgEnv-cray/4.1.40 (and therefore also for mpich)
- OpenMPI: PrgEnv-intel + mpi/openmpi/1.8.3-intel-14.0.3

The used programs
  ring_double.c
  ring_double_array.c
  ring_double_neighbor.c
show that MPI_Neighbor_alltoall works incorrectly for the case that
- the Carteasian communicator is period
- AND the number of processes is 1 or 2.
  The programs test only for 1 dimension.

The programs ring_double.c and ring_double_array.c are in principle identical,
except that ring_double_array.c uses arrays with two elements instead of two individual buffers.
Therefore, they have identical output.
The sequence of buffers is already according to the rules of MPI_Neighbor_alltoall.

The programs ring_double_array.c and ring_double_neighbor.c are in principle identical,
except that ring_double_neighbor.c uses MPI_Neighbor_alltoall instead of nonblocking
point-to-point communication.
They should have identical output, but due to a bug in MPI_Neighbor_alltoall for
## 1 and 2 processes, the output is only identical for 3 and more processes.

Further details, see protocol file:
    ring_double_output.txt

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

The fix is for peioridic cartetian graph when dimension is 1 or 2. In
both case we have two edges points to the same process and vice versa.
If we send in the order of left and right, we need receive in the order
of right and left since left and right are reversed between in and out.

Previously we only fixed ineighbor_alltoall. This patch extends the same
fix to ineighbor_alltoallv and ineighbor_alltoallw.

I also updated the comment because the previous comments is still
confusing to me. In particular, it fails to high light the key points --
First it only matters for the periodic cartesian dimension of 1 or 2.
Second that results in multiple message with the same datatype and tag.
Lastly, the matching need reverse because left and right is reversed
between in and out.

Personally, I think allowing graphs to have duplicated edges pointing to
the same rank shouldn't be allowed. Because a general graph may not
guarantee ordering the edges and thus there is no way of ensuring the
correct matching order. In the general light, this fix is merely a hack.

Fixes #2194 

Reference: previous PR #4902, previous issue #4061, mpi forum issue https://github.com/mpi-forum/mpi-issues/issues/153

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch3/tcp
test:mpich/ch4/ofi

File: src/mpi/coll/ineighbor_alltoall/ineighbor_alltoall_allcomm_sched_linear.c [hunk 1]
```diff
@@ -42,11 +42,11 @@ int MPIR_Ineighbor_alltoall_allcomm_sched_linear(const void *sendbuf, MPI_Aint s
         MPIR_ERR_CHECK(mpi_errno);
     }
 
-    /* receive needs to happen in the opposite order of sends.  This
-     * is to cover the case of Cartesian graphs where the same process
-     * might be both the left and right neighbor.  In this case, we
-     * need to make sure the first message (which is from the right
-     * neighbor) is received in the last buffer. */
+    /* periodic cartetian graph may result in different degree goes to the same process.
+     * For example, when dim is 1, both left and right neighbor are self. And when dim is
```
[the remark this answers is not in the document]
Comment (hzhou) [reply src/mpi/coll/ineighbor_alltoall/ineighbor_alltoall_allcomm_sched_linear.c]: I overhauled the comments to make the explanation easier to read. Both of your comments have been taken into account.

File: src/mpi/coll/ineighbor_alltoall/ineighbor_alltoall_allcomm_sched_linear.c [hunk 2]
```diff
@@ -42,11 +42,20 @@ int MPIR_Ineighbor_alltoall_allcomm_sched_linear(const void *sendbuf, MPI_Aint s
         MPIR_ERR_CHECK(mpi_errno);
     }
 
-    /* receive needs to happen in the opposite order of sends.  This
-     * is to cover the case of Cartesian graphs where the same process
-     * might be both the left and right neighbor.  In this case, we
-     * need to make sure the first message (which is from the right
-     * neighbor) is received in the last buffer. */
+    /* Cartetian graph will result in multiple edges going to the same process when it is
```
Comment (raffenet) [inline src/mpi/coll/ineighbor_alltoall/ineighbor_alltoall_allcomm_sched_linear.c:45]:
```suggestion
    /* Cartesian graph will result in multiple edges going to the same process when it is
```

File: src/mpi/coll/ineighbor_alltoall/ineighbor_alltoall_allcomm_sched_linear.c [hunk 3]
```diff
@@ -42,11 +42,20 @@ int MPIR_Ineighbor_alltoall_allcomm_sched_linear(const void *sendbuf, MPI_Aint s
...
+     * periodic and dim is 1 or 2, in which case, both left and right neighbor points to
+     * self or the other process. When that occurs, we are sending two messages to the
+     * same target and receiving two messages from the same target. Both messages are using
```
Comment (raffenet) [inline src/mpi/coll/ineighbor_alltoall/ineighbor_alltoall_allcomm_sched_linear.c:48]:
```suggestion
     * same receiver and receiving two messages from the same sender. Both messages are using
```

File: src/mpi/coll/ineighbor_alltoall/ineighbor_alltoall_allcomm_sched_linear.c [hunk 4]
```diff
@@ -42,11 +42,20 @@ int MPIR_Ineighbor_alltoall_allcomm_sched_linear(const void *sendbuf, MPI_Aint s
...
+     * the same tag, thus we need reverse the order of recvs to ensure correct matching.
+     * In the example of 1-dim cartesian graph, if we send in the order of left and right,
+     * the target need receive in the order of right and left to receive the correct messages.
+     *
+     * For all other case, the source and destination ranks should differentiate the messages
+     * and the order doesn't matter.
+     *
+     * The matching will be undefined if a general graph contains duplicate edges with
+     * unspecified orders.
```
Comment (raffenet) [inline src/mpi/coll/ineighbor_alltoall/ineighbor_alltoall_allcomm_sched_linear.c:57]: Is this comment talking about the MPI_Graph_create, et. al functions? Duplicate edges are not possible in those functions.

File: src/mpi/coll/ineighbor_alltoall/ineighbor_alltoall_tsp_linear.c [hunk 5]
```diff
@@ -52,11 +52,8 @@ int MPIR_TSP_Ineighbor_alltoall_sched_allcomm_linear(const void *sendbuf, MPI_Ai
         MPIR_ERR_COLL_CHECKANDCONT(mpi_errno, errflag);
     }
 
-    /* receive needs to happen in the opposite order of sends.  This
-     * is to cover the case of Cartesian graphs where the same process
-     * might be both the left and right neighbor.  In this case, we
-     * need to make sure the first message (which is from the right
-     * neighbor) is received in the last buffer. */
+    /* need reverse the order to ensure matching in the periodic case when dim is 1 or 2.
```
Comment (raffenet) [inline src/mpi/coll/ineighbor_alltoall/ineighbor_alltoall_tsp_linear.c:55]:
```suggestion
    /* need reverse the order to ensure matching in the periodic case when dims[n] is 1 or 2.
```

File: src/mpi/coll/ineighbor_alltoall/ineighbor_alltoall_allcomm_sched_linear.c [hunk 6]
```diff
@@ -42,11 +42,20 @@ int MPIR_Ineighbor_alltoall_allcomm_sched_linear(const void *sendbuf, MPI_Aint s
         MPIR_ERR_CHECK(mpi_errno);
     }
 
-    /* receive needs to happen in the opposite order of sends.  This
-     * is to cover the case of Cartesian graphs where the same process
-     * might be both the left and right neighbor.  In this case, we
-     * need to make sure the first message (which is from the right
-     * neighbor) is received in the last buffer. */
+    /* Cartetian graph will result in multiple edges going to the same process when it is
+     * periodic and dim is 1 or 2, in which case, both left and right neighbor points to
```
Comment (raffenet) [inline src/mpi/coll/ineighbor_alltoall/ineighbor_alltoall_allcomm_sched_linear.c:46]: the issue is if the size of the dimension is 1 or 2. neighbors are not necessarily left and right.

File: src/mpi/coll/ineighbor_alltoall/ineighbor_alltoall_allcomm_sched_linear.c (hunk 4 above)
Comment (hzhou) [reply src/mpi/coll/ineighbor_alltoall/ineighbor_alltoall_allcomm_sched_linear.c:57]: The algorithm here is without the context of how the graph was created. Since the fix here is concerned with duplicated edges, I feel necessary to explain that it only accommodates a particular case of duplicated edges that is resulted from MPI_Cart_create. Let me rewrite this paragraph to be more specific.

File: src/mpi/coll/ineighbor_alltoall/ineighbor_alltoall_allcomm_sched_linear.c (hunk 6 above)
Comment (hzhou) [reply src/mpi/coll/ineighbor_alltoall/ineighbor_alltoall_allcomm_sched_linear.c:46]: "left and right" in a circular sense. In the case of 2 for example, saying it produces two edges both pointing to the neighboring process leaves one wondering why. But that maybe just me. Feel free to suggest better wording.

**Comment by hzhou** [comment]
@raffenet Pushed a fixup commit. Let me know if it good to squash.

**Review by raffenet — APPROVED** [review]
