### PR TITLE
ch4/win: refactor win_shm_alloc_impl

### LINKED ISSUE #7681: Incorrect flag/variable update in win_shm_alloc_impl
https://github.com/pmodels/mpich/blob/dcfab137749d5f798083f9900c4e0b58cfb66b12/src/mpid/ch4/src/mpidig_win.c#L594

Should('nt) shm_mapfail_flag be updated instead of symheap_mapfail_flag  at 594 and 596? Note that further in the function we check shm_mapfail_flag which never seems to be updated in this routine after it gets initialised.

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
There is a potential issue - https://github.com/pmodels/mpich/issues/7681.

The code was a bit convoluted. Cleaned it up while fixing the issue.

Fixes #7681 

[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

File: src/mpid/ch4/src/mpidig_win.c [hunk 1]
```diff
@@ -531,29 +533,38 @@ static int win_shm_alloc_impl(MPI_Aint size, int disp_unit, MPIR_Comm * comm_ptr
...
-            goto fn_no_shm;
+        if (total_shm_size == 0 && shm_comm_ptr->local_size == comm_ptr->local_size) {
+            goto fn_exit;
+        }
 
+        /* because MPI_shm follows a create & attach mode, we need to set the
+         * size of entire shared memory segment on each node as the size of
+         * each process. */
+        mapsize = MPIDU_shm_get_mapsize(total_shm_size, NULL);
+        /* MPIR_Assert(mapsize > 0); */
```
Comment (raffenet) [inline src/mpid/ch4/src/mpidig_win.c]: do we want to do error checking here or remove this commented line?

File: src/mpid/ch4/src/mpidig_win.c [hunk 2]
```diff
@@ -564,82 +575,84 @@ static int win_shm_alloc_impl(MPI_Aint size, int disp_unit, MPIR_Comm * comm_ptr
...
-        MPL_free(MPIDIG_WIN(win, shared_table));
+    if (shared_table && !shm_mapped) {
+        MPL_free(shared_table);
         MPIDIG_WIN(win, shared_table) = NULL;
+    } else {
+        MPIDIG_WIN(win, shared_table) = shared_table;
     }
-
-  fn_exit:
     MPIR_CHKLMEM_FREEALL();
```
Comment (raffenet) [inline src/mpid/ch4/src/mpidig_win.c]: I think all uses of CHKLMEM in this function are gone now.

File: src/mpid/ch4/src/mpidig_win.c (hunk 1 above)
Comment (hzhou) [reply src/mpid/ch4/src/mpidig_win.c]: I'll remove this commented line. `total_shm_size` is none zero at this point thus `mapsize` should be positive.

File: src/mpid/ch4/src/mpidig_win.c (hunk 2 above)
Comment (hzhou) [reply src/mpid/ch4/src/mpidig_win.c]: Good point!

**Comment by hzhou** [comment]
> LGTM. Just to confirm my understanding, the additional hint doesn't affect the default behavior of trying a symheap and falling back if not available? Just that it turns the failure into an error instead falling back.

The hint changes the default behavior and will fail unless symheap succeeded. I assume if the app need symheap, then they *require* it. But I guess we could also reflect that in info hints to give application some way of fallback. On the other hand, the app always can `ERROR_RETURN` and retry without the symheap hints.

**Comment by hzhou** [comment]
I'll investigate the test failures.

**Comment by hzhou** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by hzhou** [comment]
test:mpich/warnings/auto

**Comment by raffenet** [comment]
Based on the discussion yesterday, I may have misunderstood the behavior change in this PR. Previously, MPICH would try a symmetric heap allocation and fallback after a number of unsuccessful tries for every window allocation. This was because symmetric heap had nicer optimization properties vs. the default. Is the behavior now to never try symmetric heap unless the user requests it via info argument?

**Comment by hzhou** [comment]
>  Is the behavior now to never try symmetric heap unless the user requests it via info argument?

Yes. We never try symmetric heap unless the user request it. 

> This was because symmetric heap had nicer optimization properties vs. the default.

What are the nicer optimization properties of symmetric heap? Are we utilizing it somewhere?

**Comment by raffenet** [comment]
> > Is the behavior now to never try symmetric heap unless the user requests it via info argument?
> 
> Yes. We never try symmetric heap unless the user request it.
> 
> > This was because symmetric heap had nicer optimization properties vs. the default.
> 
> What are the nicer optimization properties of symmetric heap? Are we utilizing it somewhere?

Hm, not that I can find. The idea was that you could avoid storing the base pointer array for the window since it was all the same. I thought we had implemented but it may have been lost in a branch or removed over time.

**Comment by hzhou** [comment]
> The idea was that you could avoid storing the base pointer array for the window since it was all the same. I thought we had implemented but it may have been lost in a branch or removed over time.

That makes sense. We can easily add back the symheap trial when we add that optimization. And the key point I noticed that was missing was we don't flag whether we had symheap. Without that flag, there won't be code to take advantage of it. I can add a comment or TODO if you'd like.
