### PR TITLE
autogen: add set -e

### LINKED ISSUE #5455: autogen: abort when encouter errors
Currently `autogen.sh` will blissfully continue when some of the command fails. We should abort when error is encountered. This could be as simple as adding `set -e` and `set pipefail` (or something like that).

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
Add set -e so the autogen will fail when one of the command fail. The
set -e is added in the middle of the script after basic checks are done
-- other wise it will always trigger. This should prevent it proceed
happily after a python script error and difficult for user to spot
issues.

Fixes #5455
[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Review by raffenet — COMMENTED** [review]
This needs to be able to handle when our libtool patches don't apply. For instance on my laptop, the Homebrew version of libtool already has the BigSur patch. With this PR, `autogen.sh` stops here on my machine:
```
running autoreconf in .
glibtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'confdb'.
glibtoolize: copying file 'confdb/ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'confdb'.
glibtoolize: copying file 'confdb/libtool.m4'
glibtoolize: copying file 'confdb/ltoptions.m4'
glibtoolize: copying file 'confdb/ltsugar.m4'
glibtoolize: copying file 'confdb/ltversion.m4'
glibtoolize: copying file 'confdb/lt~obsolete.m4'
glibtoolize: Consider adding '-I confdb' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:33: installing 'confdb/compile'
configure.ac:40: installing 'confdb/missing'
src/Makefile.am: installing 'confdb/depcomp'
glibtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'confdb'.
glibtoolize: copying file 'confdb/ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'confdb'.
glibtoolize: copying file 'confdb/libtool.m4'
glibtoolize: copying file 'confdb/ltoptions.m4'
glibtoolize: copying file 'confdb/ltsugar.m4'
glibtoolize: copying file 'confdb/ltversion.m4'
glibtoolize: copying file 'confdb/lt~obsolete.m4'
glibtoolize: 'AC_PROG_RANLIB' is rendered obsolete by 'LT_INIT'
configure.ac:650: installing 'confdb/compile'
configure.ac:43: installing 'confdb/missing'
attr/Makefile.am: installing 'confdb/depcomp'
glibtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'confdb'.
glibtoolize: copying file 'confdb/ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'confdb'.
glibtoolize: copying file 'confdb/libtool.m4'
glibtoolize: copying file 'confdb/ltoptions.m4'
glibtoolize: copying file 'confdb/ltsugar.m4'
glibtoolize: copying file 'confdb/ltversion.m4'
glibtoolize: copying file 'confdb/lt~obsolete.m4'
configure.ac:629: installing 'confdb/compile'
configure.ac:653: installing 'confdb/missing'
Makefile.am: installing 'confdb/depcomp'
Patching ltmain.sh for compatibility with Intel compiler options... done
Patching libtool.m4 for system dynamic library search path...done
Patching libtool.m4 for compatibility macOS BigSur...Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file ./confdb/libtool.m4.rej
```

**Comment by hzhou** [comment]
> This needs to be able to handle when our libtool patches don't apply. For instance on my laptop, the Homebrew version of libtool already has the BigSur patch. With this PR, `autogen.sh` stops here on my machine:

I see. We can protect the `patch` by appending it with ` || true`

**Comment by hzhou** [comment]
@raffenet Can you check if this new version works for you?

**Comment by raffenet** [comment]
> @raffenet Can you check if this new version works for you?

Yes, this versions works on my laptop.

File: autogen.sh [hunk 1]
```diff
@@ -1004,7 +1005,7 @@ if [ "$do_build_configure" = "yes" ] ; then
             # Patching ltmain.sh
             if [ -f $amdir/confdb/ltmain.sh ] ; then
                 echo_n "Patching ltmain.sh for compatibility with Intel compiler options... "
-                patch -N -s -l $amdir/confdb/ltmain.sh maint/patches/optional/confdb/intel-compiler.patch
+                patch -N -s -l $amdir/confdb/ltmain.sh maint/patches/optional/confdb/intel-compiler.patch && :
```
Comment (raffenet) [inline autogen.sh:1008]: So `&& :` seems to work, but why? I'm not familiar with this shell pattern.

Comment (hzhou) [reply autogen.sh:1008]: `-e` just ignores components with `&&` or `||`.  And `:` doesn't overwrite `$?`.

Comment (raffenet) [reply autogen.sh:1008]: I'm was mostly trying to understand what `:` does. Finally was able to figure out it is a shell builtin.

**Review by raffenet — APPROVED** [review]
