### PR TITLE
nameserv: add infohints to MPI_Lookup_name

### LINKED ISSUE #6831: Name publishing and port names under CH4:UCX
Name publishing with ch4:ucx seems to be broken in current main branch, I'm getting truncated port names

Don't you have to add the support for "port_name_size" via info to all routines that involve a port name string? Or did you , and I just failed to figured that out in your original PR?

Maybe only `MPI_Lookup_name` needs the "port_name_size" hint. The other routines that only read the port name (close, publish, and unpublish) can get away by checking whether the character at MPI_MAX_PORT_NAME(=512) is the null terminator to decide whether to keep reading the buffer. `MPI_Close_port` doesn't even have an info hint!

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
Similar to `MPID_Open_port` (https://github.com/pmodels/mpich/pull/5467/commits/ab2be7740cad6c6b482bc41f28553db089059c3c), add info hint "port_name_size" to `MPI_Lookup_name` so user can supply a port_name buffer larger than `MPI_MAX_PORT_NAME` to circumvent larger business cards, e.g. on UCX.

Fixes #6831
[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

File: src/nameserv/pmi/pmi_nameserv.c [hunk 1]
```diff
@@ -41,10 +41,14 @@ int MPID_NS_Publish(MPID_NS_Handle handle, const MPIR_Info * info_ptr,
...
                    const char service_name[], char port[])
 {
-    MPL_UNREFERENCED_ARG(info_ptr);
     MPL_UNREFERENCED_ARG(handle);
 
-    return MPIR_pmi_lookup(service_name, port);
+    int port_name_size = MPI_MAX_PORT_NAME;
+    if (info_ptr) {
+        const char *val = MPIR_Info_lookup(info_ptr, "port_name_size");
+        port_name_size = atoi(val);
```
Comment (dalcinl) [inline src/nameserv/pmi/pmi_nameserv.c:49]:
```suggestion
        if (val) {
            port_name_size = atoi(val);
        }
```

Comment (hzhou) [reply src/nameserv/pmi/pmi_nameserv.c]: Thanks for finding the bug!

**Comment by hzhou** [comment]
test:mpich/ch3/tcp
test:mpich/ch4/most

**Comment by dalcinl** [comment]
FWIW, all mpi4py test are [passing](https://github.com/mpi4py/mpi4py-testing/actions/runs/7152377260/job/19477638372) with hydra+ch4:ucx.

**Comment by dalcinl** [comment]
@hzhou Could you please rebase this PR to latest main?

**Comment by dalcinl** [comment]
@hzhou I'm still getting a truncation when using `device=ch4:ucx` `pm=gforker` `namepublisher=file` [[logs]](https://github.com/mpi4py/mpi4py-testing/actions/runs/7200124766/job/19613359683#step:19:1671)
Or is `namepublisher=file` obsolete if using `pm=gforker`?

**Comment by hzhou** [comment]
> @hzhou I'm still getting a truncation when using `device=ch4:ucx` `pm=gforker` `namepublisher=file` [[logs]](https://github.com/mpi4py/mpi4py-testing/actions/runs/7200124766/job/19613359683#step:19:1671) Or is `namepublisher=file` obsolete if using `pm=gforker`?

I need add another patch for the "file" nameserver.

**Comment by dalcinl** [comment]
BTW, would it make sense to make `namepublisher=file` the default if `pm=gforker` at configure time? Or is `namepublisher=pmi` now working with gforker?

**Comment by hzhou** [comment]
Is it not working? I'll check later. If it's not working, I am sure we can make it work.

--
Hui Zhou
________________________________

**Comment by dalcinl** [comment]
@hzhou All green now! [[logs]](https://github.com/mpi4py/mpi4py-testing/actions/runs/7200124766/job/19615048793)

> Is it not working? I'll check later. If it's not working, I am sure we can make it work.

Are you talking about mpi4py tests, or my suggestion about nameserver configure default with gforker?

File: CHANGES [hunk 2]
```diff
@@ -6,6 +6,11 @@
   of 256. One can work around by use an info hint "port_name_size" and use a
   larger port name buffer.
 
+# PMI-1 defines PMI_MAX_PORT_NAME, which may be different from MPI_MAX_PORT_NAME.
+  This is used by "PMI_Lookup_name". Consequently, MPI_Lookup_name accepts info
+  hint "port_name_size" that may be larger than MPI_MAX_PORT_NAME. If the port
+  name does not fit in "port_name_size", it will return a truction error.
```
Comment (raffenet) [inline CHANGES:12]:
```suggestion
  name does not fit in "port_name_size", it will return a truncation error.
```

**Review by raffenet — APPROVED** [review]
Just a spelling nit in the changelog, otherwise looks good.

**Review by dalcinl — APPROVED** [review]

**Comment by hzhou** [comment]
> @hzhou All green now! [[logs]](https://github.com/mpi4py/mpi4py-testing/actions/runs/7200124766/job/19615048793)
> 
> > Is it not working? I'll check later. If it's not working, I am sure we can make it work.
> 
> Are you talking about mpi4py tests, or my suggestion about nameserver configure default with gforker?

Just checked the code, `gforker` does not support `PMI_Publish_name` etc. right now. Let me create a ticket for adding that support.
