### PR TITLE
ch4/am: make rndz descision from generic layer

### LINKED ISSUE #3915: ch4: Fortran ssend tests segfault in am-only tests
```
$ mpiexec -n 2 ./ssendf

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f5eff0adaba in ???
#1  0x7f5eff0acce3 in ???
#2  0x7f5efe5a82ef in ???
#3  0x7f5f00a6c6b1 in MPIDI_POSIX_eager_send
	at /home/hajimefu/src/mpich/src/mpid/ch4/shm/posix/eager/fbox/fbox_send.h:47
#4  0x7f5f009f8c96 in MPIDI_POSIX_eager_send
	at /home/hajimefu/src/mpich/src/mpid/ch4/shm/posix/eager/include/posix_eager_impl.h:30
#5  0x7f5f009f8c96 in MPIDI_POSIX_am_isend
	at /home/hajimefu/src/mpich/src/mpid/ch4/shm/src/../posix/posix_am.h:192
#6  0x7f5f009f8c96 in MPIDI_POSIX_am_isend_reply
	at /home/hajimefu/src/mpich/src/mpid/ch4/shm/src/../posix/posix_am.h:287
#7  0x7f5f009f8c96 in MPIDI_SHM_am_isend_reply
	at /home/hajimefu/src/mpich/src/mpid/ch4/shm/src/shm_am.h:95
#8  0x7f5eff96dc28 in MPIDI_SHM_am_isend_reply
	at /home/hajimefu/src/mpich/src/mpid/ch4/shm/src/shm_impl.h:112
#9  0x7f5eff96dc28 in MPIDIG_reply_ssend
	at /home/hajimefu/src/mpich/src/mpid/ch4/src/ch4r_recv.h:28
#10  0x7f5eff972334 in recv_target_cmpl_cb
	at /home/hajimefu/src/mpich/src/mpid/ch4/src/ch4r_callbacks.c:348
#11  0x7f5f00370e68 in MPIDI_OFI_handle_short_am
	at /home/hajimefu/src/mpich/src/mpid/ch4/netmod/ofi/ofi_am_events.h:168
#12  0x7f5f003fd47c in MPIDI_OFI_am_recv_event
	at /home/hajimefu/src/mpich/src/mpid/ch4/netmod/ofi/ofi_events.h:569
#13  0x7f5f003fd47c in MPIDI_OFI_dispatch_function
	at /home/hajimefu/src/mpich/src/mpid/ch4/netmod/ofi/ofi_events.h:688
#14  0x7f5f003fd47c in MPIDI_OFI_handle_cq_entries
	at /home/hajimefu/src/mpich/src/mpid/ch4/netmod/ofi/ofi_events.h:801
#15  0x7f5f003fd47c in MPIDI_NM_progress
	at /home/hajimefu/src/mpich/src/mpid/ch4/netmod/ofi/ofi_progress.h:32
#16  0x7f5eff659ad4 in MPIDI_NM_progress
	at /home/hajimefu/src/mpich/src/mpid/ch4/netmod/include/netmod_impl.h:26
#17  0x7f5eff659ad4 in MPIDI_vci_progress
	at /home/hajimefu/src/mpich/src/mpid/ch4/src/ch4_progress.h:50
#18  0x7f5eff659ad4 in MPIDI_Progress_test
	at /home/hajimefu/src/mpich/src/mpid/ch4/src/ch4_progress.h:156
#19  0x7f5eff659ad4 in MPIDI_wait
	at /home/hajimefu/src/mpich/src/mpid/ch4/include/mpidpost.h:163
#20  0x7f5eff659ad4 in MPID_Wait
	at /home/hajimefu/src/mpich/src/mpid/ch4/include/mpidpost.h:212
#21  0x7f5eff659ad4 in PMPI_Recv
	at /home/hajimefu/src/mpich/src/mpi/pt2pt/recv.c:144
#22  0x7f5f01142ef7 in pmpi_recv_
	at /home/hajimefu/src/mpich/src/binding/fortran/mpif_h/recvf.c:276
#23  0x4014f4 in test_pair_ssend_
	at /home/hajimefu/src/mpich/test/mpi/f77/pt2pt/ssendf.f:116
#24  0x4015e7 in ssend
	at /home/hajimefu/src/mpich/test/mpi/f77/pt2pt/ssendf.f:24
#25  0x401643 in main
	at /home/hajimefu/src/mpich/test/mpi/f77/pt2pt/ssendf.f:30

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 13385 RUNNING AT ancc01
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
```
I believe these xfail entries are referring to the same issue.
```
* * am-only ch4:ofi * sed -i "s+\(^ssendf .*\)+\1 xfail=ticket0+g" test/mpi/f77/pt2pt/testlist
* * am-only ch4:ofi * sed -i "s+\(^ssendf90 .*\)+\1 xfail=ticket0+g" test/mpi/f90/pt2pt/testlist
* * am-only ch4:ofi * sed -i "s+\(^issendf .*\)+\1 xfail=ticket0+g" test/mpi/f77/pt2pt/testlist
* * am-only ch4:ofi * sed -i "s+\(^issendf90 .*\)+\1 xfail=ticket0+g" test/mpi/f90/pt2pt/testlist
```

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

The current way of letting netmod overwrite send protocol into long_send is awkward. Not only it duplicates code, spreads protocol, it also complicates the active message api interfaces.

This PR attempts to make the rndz decision from the generic layer. It uses the netmod api MPIDI_NM_am_hdr_max_sz, so individual netmod still can make its individual choice. It should be noted that this api is used in multiple places. It might be a good idea to add a new api, e.g. `MPIDI_NM_am_eager_limit`.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
       Fixes #3915
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [x] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand

### CODE REVIEW

**Comment by hzhou** [comment]
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:whitespace

**Comment by hzhou** [comment]
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:jenkins/ch4/most

File: src/mpid/ch4/generic/mpidig_send.h [hunk 1]
```diff
@@ -14,21 +14,62 @@
...
+#else
+    if (is_local) {
+        return MPIDI_SHM_am_eager_limit() - MPIDIG_AM_SEND_HDR_SIZE;
+    } else {
+        return MPIDI_NM_am_eager_limit() - MPIDIG_AM_SEND_HDR_SIZE;
+    }
+#endif
+}
+
+static inline int MPIDIG_do_send(const void *buf, MPI_Aint count, MPI_Datatype datatype,
```
Comment (raffenet) [inline src/mpid/ch4/generic/mpidig_send.h]: I would suggest `MPIDIG_do_eager_send` and `MPIDIG_do_rndv_send`

File: src/mpid/ch4/src/ch4r_callbacks.c [hunk 2]
```diff
@@ -554,6 +554,10 @@ int MPIDIG_send_long_req_target_msg_cb(int handler_id, void *am_hdr, void **data
         MPID_THREAD_CS_EXIT(VCI, MPIDIU_THREAD_MPIDIG_GLOBAL_MUTEX);
     } else {
         /* Matching receive was posted, tell the netmod */
+        /* we still need hold onto comm for sending ack.
+         * This shouldn't be necessary if we use global rank for active messages */
+        MPIR_Comm_add_ref(root_comm);
```
Comment (raffenet) [inline src/mpid/ch4/src/ch4r_callbacks.c]: Strike the `MPIR_Comm_release` below and this add should not be needed.

File: src/mpid/ch4/src/ch4r_recvq.h [hunk 3]
```diff
@@ -158,13 +158,18 @@ MPL_STATIC_INLINE_PREFIX MPIR_Request *MPIDIG_dequeue_posted(int rank, int tag,
     MPIR_T_PVAR_TIMER_START(RECVQ, time_failed_matching_postedq);
     DL_FOREACH_SAFE(*list, curr, tmp) {
         MPIR_T_PVAR_COUNTER_INC(RECVQ, posted_recvq_match_attempts, 1);
-        req = curr->request;
-        if (MPIDIG_match_posted(rank, tag, context_id, req)) {
+#ifndef MPIDI_CH4_DIRECT_NETMOD
+        /* NOTE: extra negation to force logical comparisons */
+        if (!MPIDI_REQUEST(curr->request, is_local) != !is_local) {
```
Comment (raffenet) [inline src/mpid/ch4/src/ch4r_recvq.h]: oof. `bool` type would avoid having to do this, no? Also is this related to rndv or just a matching optimization? Rank comparison is already part of matching.

File: src/mpid/ch4/generic/mpidig_send.h [hunk 4]
```diff
@@ -14,20 +14,64 @@
...
-    void *hdr = &am_hdr;
-    size_t hdr_sz = sizeof(am_hdr);;
+    MPI_Aint data_sz;
+    MPIR_Datatype *dt_ptr;
+    MPIDI_Datatype_get_size_dt_ptr(count, datatype, data_sz, dt_ptr);
 
-    MPIR_FUNC_VERBOSE_STATE_DECL(MPID_STATE_MPIDIG_ISEND_IMPL);
-    MPIR_FUNC_VERBOSE_ENTER(MPID_STATE_MPIDIG_ISEND_IMPL);
+    int is_local = MPIDI_av_is_local(addr);
+    if (type == MPIDIG_SSEND_REQ) {
```
Comment (raffenet) [inline src/mpid/ch4/generic/mpidig_send.h]: No rndv for long synchronous sends? ch3 only implemented an eager ssend protocol. Synchronous sends larger than the eager limit went over the regular rndv protocol with no modification.

File: src/mpid/ch4/generic/mpidig_send.h [hunk 5]
```diff
@@ -14,21 +14,62 @@
 
 #include "ch4_impl.h"
 
+#define MPIDIG_AM_SEND_HDR_SIZE  sizeof(MPIDIG_hdr_t)
```
Comment (raffenet) [inline src/mpid/ch4/generic/mpidig_send.h]: Will be available for other message types? Rendezvous shouldn't be limited to pt2pt operations.

Comment (hzhou) [reply src/mpid/ch4/generic/mpidig_send.h]: My idea is to have specific protocol for each specific operation. So a rendezvous pt2pt will be a distinct protocol from, say a put rendezvous protocol. In fact, even within pt2pt send, we may have different rndz protocols, e.g. one send lmt, one send multiple eager segments, one sets up rdma, etc., and each will be distinct from each other and each have independent headers.

That said, we still can reduce code-duplication by factoring common routines to an inline header file. But conceptually, they are distinct and can be modified locally in all aspects without interfering other similar protocols.

File: src/mpid/ch4/generic/mpidig_send.h (hunk 4 above)
Comment (hzhou) [reply src/mpid/ch4/generic/mpidig_send.h]: That is how current ch4 code does. I am trying to stick to a refactor for this PR. RNDZ synchronous sends need be implemented as a separate protocol. If we factor the common code smartly, a new protocol can be implemented easily and cleanly.

File: src/mpid/ch4/src/ch4r_callbacks.c (hunk 2 above)
Comment (hzhou) [reply src/mpid/ch4/src/ch4r_callbacks.c]: True. But the add_ref and the release are for different semantic ownership though. I guess replace both with an explanation comment will do.

File: src/mpid/ch4/src/ch4r_recvq.h (hunk 3 above)
Comment (hzhou) [reply src/mpid/ch4/src/ch4r_recvq.h]: Yes, if we use a true boolean type (which C99 provides) then we can avoid this hack. Somehow, I am still nervous that some compilers may still not do the right thing -- i.e. internally use integer and one true may not equal to another true.

Anyway, how about leave this to a separate PR that do the bool refactor in wholesale to maintain consistency?

File: src/mpid/ch4/src/ch4r_callbacks.c (hunk 2 above)
Comment (raffenet) [reply src/mpid/ch4/src/ch4r_callbacks.c]: Hmm, yes I see your point. Backing up, I'm not sure why the other reference is released here. The message should be tied to the recv request, which is not yet complete. I agree that requiring comm to send the ack is not necessary in the long run.

File: src/mpid/ch4/src/ch4r_recvq.h (hunk 3 above)
Comment (raffenet) [reply src/mpid/ch4/src/ch4r_recvq.h]: But is this new optimization or a fix? If optimization, then I prefer dropping it from this series.

File: src/mpid/ch4/generic/mpidig_send.h (hunk 4 above)
Comment (raffenet) [reply src/mpid/ch4/generic/mpidig_send.h]: True, fair enough.

File: src/mpid/ch4/generic/mpidig_send.h (hunk 5 above)
Comment (raffenet) [reply src/mpid/ch4/generic/mpidig_send.h]: I have to be honest I thought ch3 sent more message types over rndv protocol, but looking back I was wrong. This is probably fine to start here and add more as we go.

**Comment by hzhou** [comment]
Addressed comments and rebased to master:

test:mpich/warnings
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:mpich/warnings
test:jenkins/ch4/most

File: src/mpid/ch4/src/ch4r_recvq.h (hunk 3 above)
Comment (raffenet) [reply src/mpid/ch4/src/ch4r_recvq.h]: OK, I see we are posting anysource requests twice to the same list with AM enabled 😞

File: src/mpid/ch4/netmod/ofi/ofi_am.h [hunk 6]
```diff
@@ -123,6 +123,11 @@ static inline size_t MPIDI_NM_am_hdr_max_sz(void)
     return MPL_MIN(max_shortsend, max_representable);
 }
 
+static inline size_t MPIDI_NM_am_eager_limit(void)
+{
+    return MPIDI_OFI_DEFAULT_SHORT_SEND_SIZE - sizeof(MPIDI_OFI_am_header_t);
+}
+
```
Comment (wesbland) [inline src/mpid/ch4/netmod/ofi/ofi_am.h]: This doesn't take into account d061878934d3 and 064dacbe7207ad1f7288a79b183f2f229e2102b7 that adds a CVAR to overwrite this value. Probably all versions of this function need to check whether this CVAR is specified.

File: src/mpid/ch4/src/ch4r_callbacks.c [hunk 7]
```diff
@@ -553,8 +553,12 @@ int MPIDIG_send_long_req_target_msg_cb(int handler_id, void *am_hdr, void **data
         }
         MPID_THREAD_CS_EXIT(VCI, MPIDIU_THREAD_MPIDIG_GLOBAL_MUTEX);
     } else {
-        /* Matching receive was posted, tell the netmod */
-        MPIR_Comm_release(root_comm);   /* -1 for posted_list */
```
Comment (wesbland) [inline src/mpid/ch4/src/ch4r_callbacks.c]: You removed the `MPIR_Comm_release` here, but where is the release actually going to happen now? Does that happen automatically when the request is freed?

File: src/mpid/ch4/src/ch4r_callbacks.c [hunk 8]
```diff
@@ -381,7 +381,7 @@ int MPIDIG_send_target_msg_cb(int handler_id, void *am_hdr, void **data, size_t
         /* MPIDI_CS_ENTER(); */
         while (TRUE) {
             rreq = MPIDIG_dequeue_posted(hdr->src_rank, hdr->tag, hdr->context_id,
-                                         &MPIDIG_COMM(root_comm, posted_list));
+                                         is_local, &MPIDIG_COMM(root_comm, posted_list));
```
Comment (wesbland) [inline src/mpid/ch4/src/ch4r_callbacks.c]: There's a typo in the commit message for 6176e7b83801a12d5eb7ea9f6177fc14a4850f34:

```diff
- This is necessary when both shmmod and netmod are using activemessages
+ This is necessary when both shmmod and netmod are using active messages
and an anysource recv pair are posted in the same posted_list. Without
- it, a netmod send will gets matched to a shmmod recv, resulting in
+ it, a netmod send will get matched to a shmmod recv, resulting in
errors.
```

File: src/mpid/ch4/netmod/ofi/ofi_am.h (hunk 6 above)
Comment (hzhou) [reply src/mpid/ch4/netmod/ofi/ofi_am.h]: I wasn't aware of that CVAR, thanks for pointing it out.

Ken convinced me that the eager limit should be dictated by the lower-layer -- netmod or shmmod -- because the lower layer knows what makes sense for their mechanism. In what scenario that user desire to set eager limit regardless of lower-layer transport?

Comment (wesbland) [reply src/mpid/ch4/netmod/ofi/ofi_am.h]: I don't have a problem with that CVAR being a nm/shm level decision. I just want to make sure the override exists. It's really only used for testing, but tweaking the eager/rndv threshold is also one of the classic examples of an "MPI Tuning Knob" that people want to see.

Comment (hzhou) [reply src/mpid/ch4/netmod/ofi/ofi_am.h]: Sounds good. I'll update it to honor that CVAR.

File: src/mpid/ch4/src/ch4r_callbacks.c (hunk 7 above)
Comment (hzhou) [reply src/mpid/ch4/src/ch4r_callbacks.c]: It is in the comments I added below. 

What actually happens is: we do `MPIR_Comm_release` for removing from `posted_list`, then we need do `MPIR_Comm_add_ref`  for attaching the comm to `rreq`. The latter is necessary to fix a bug when user free the comm before we do `ack` later. 

Now release the reference then immediately add the reference back cancels, so the change appears to be just removing `MPIR_Comm_release`.

File: src/mpid/ch4/netmod/ofi/ofi_am.h (hunk 6 above)
Comment (hzhou) [reply src/mpid/ch4/netmod/ofi/ofi_am.h]: Added a commit to apply this CVAR at MPIDIG layer.

**Comment by hzhou** [comment]
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:jenkins/warnings/quick
test:jenkins/ch4/most

File: src/mpid/ch4/generic/mpidig_send.h [hunk 9]
```diff
@@ -14,19 +14,47 @@
 
 #include "ch4_impl.h"
 
+/*
```
Comment (gcongiu) [inline src/mpid/ch4/generic/mpidig_send.h]: Commit message has typos

File: src/mpid/ch4/src/ch4r_callbacks.c [hunk 10]
```diff
@@ -553,8 +553,12 @@ int MPIDIG_send_long_req_target_msg_cb(int handler_id, void *am_hdr, void **data
...
     } else {
-        /* Matching receive was posted, tell the netmod */
-        MPIR_Comm_release(root_comm);   /* -1 for posted_list */
+        /* Matching receive was posted */
+        rreq->comm = root_comm;
+        /* NOTE: we are skipping MPIR_Comm_release for taking off posted_list since we are holding
+         * the reference to root_comm in the rreq. We need to hold on to this reference so the comm
+         * may remain valid by the time we send ack (using the comm).
+         */
         MPIDIG_REQUEST(rreq, req->status) |= MPIDIG_REQ_LONG_RTS;
```
Comment (gcongiu) [inline src/mpid/ch4/src/ch4r_callbacks.c]: Commit message has typo

File: src/mpid/ch4/generic/mpidig_send.h [hunk 11]
```diff
@@ -14,20 +14,92 @@
...
+    MPIR_Assert(thresh > 0);
+
+    return thresh;
+}
+
+static inline int MPIDIG_do_eager_send(const void *buf, MPI_Aint count, MPI_Datatype datatype,
+                                       int rank, int tag, MPIR_Comm * comm, int context_offset,
+                                       MPIDI_av_entry_t * addr, MPIR_Request ** request,
+                                       MPIR_Errflag_t errflag);
+static inline int MPIDIG_do_rndz_send(const void *buf, MPI_Aint count, MPI_Datatype datatype,
```
Comment (gcongiu) [inline src/mpid/ch4/generic/mpidig_send.h]: I think @raffenet already made a comment about naming of this function. Can you use `_rndv_` instead of `_rndz_` for consistency with the rest of the code? Same goes for comments and commit messages.

File: src/mpid/ch4/src/ch4r_recvq.h (hunk 3 above)
Comment (gcongiu) [inline src/mpid/ch4/src/ch4r_recvq.h]: Personally I don't like this. Can we change the logic a little bit to get rid of the extra negation? Would something like:
```
    bool do_matching = true;

#ifndef MPIDI_CH4_DIRECT_NETMOD
    do_matching = (MPIDI_REQUEST(curr->request, is_local) && is_local);
#endif 

    if (do_matching && MPIDIG_match_posted(rank, ...)) {
        ...
        break;
    }
```
work?

File: src/mpid/ch4/generic/mpidig_send.h (hunk 9 above)
Comment (hzhou) [reply src/mpid/ch4/generic/mpidig_send.h]: fixed.

File: src/mpid/ch4/src/ch4r_callbacks.c (hunk 10 above)
Comment (hzhou) [reply src/mpid/ch4/src/ch4r_callbacks.c]: fixed.

File: src/mpid/ch4/generic/mpidig_send.h (hunk 11 above)
Comment (hzhou) [reply src/mpid/ch4/generic/mpidig_send.h]: Even though I believe *rndz* is the right abbreviation, I see we have been using *rndz* throughout the existing code base, so I have updated to `MPIDIG_do_rndv_send` instead.

File: src/mpid/ch4/src/ch4r_recvq.h (hunk 3 above)
Comment (hzhou) [reply src/mpid/ch4/src/ch4r_recvq.h]: From our offline discussion, we decided to let this one go as the alternative is even more gross :(

**Comment by hzhou** [comment]
test:mpich/warnings/quick
test:jenkins/ch4/most
