### PR TITLE
ch4/ofi: use separate req_hdr for send and receive

### LINKED ISSUE #4976: bug/jenkins: timeout with rma/win_dynamic_rma_flush_get_collattach
Encountered this failure in PR #4974, only in `ch4/ofi - am-only` config.  I don't think it is related to the PR and it probably is intermittent. Creating this issue to track.

```
Error Message

not ok  - ./rma/win_dynamic_rma_flush_get_collattach 2

Stacktrace

not ok  - ./rma/win_dynamic_rma_flush_get_collattach 2
  ---
  Directory: ./rma
  File: win_dynamic_rma_flush_get_collattach
  Num-procs: 2
  Timeout: 180
  Date: "Mon Jan  4 11:55:46 2021"
  ...
## Test output (expected 'No Errors'):
## [mpiexec@pmrs-centos64-240-03.cels.anl.gov] APPLICATION TIMED OUT, TIMEOUT = 180s
## 
##   uptime:
##  11:55:46 up 76 days, 19:18,  0 users,  load average: 6.06, 6.38, 7.49
 ```

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
During an active message protocol, the same request may switch from a
send request into a receive request, and in the rdma case, the ofi
receive side need some persistent data storage that is currently using
the same req_hdr as the send side. However, at the point of recv, the
previous send completion may not have run yet (rare, but happens), and
overwriting the req_hdr corrupts the data when send completion finally
run. Because the send-side origin_cbs are often simple and similar, this
doesn't result in many failures by accident, but nevertheless, it is
erroneous code. One case that currently triggers is the
rma/win_dynamic_rma_flush_get test, which only fails 1 out of 1000
repeats.

This patch allocates separate sreq_hdr and rreq_hdr so send and recv
won't compete for persistent strorage space, fixing the bug.

Fixes #4976.

Pending:
* [x] https://github.com/pmodels/mpich/pull/5533
[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

File: src/mpid/ch4/netmod/ofi/ofi_events.c [hunk 1]
```diff
@@ -488,12 +488,12 @@ static int am_isend_event(struct fi_cq_tagged_entry *wc, MPIR_Request * sreq)
 
     MPIR_FUNC_ENTER;
 
-    msg_hdr = &MPIDI_OFI_AMREQUEST_HDR(sreq, msg_hdr);
+    msg_hdr = &MPIDI_OFI_AM_SREQ_HDR(sreq, msg_hdr);
```
Comment (hzhou) [inline src/mpid/ch4/netmod/ofi/ofi_events.c:491]: NOTE: this ensures that we access the correct `msg_hdr` from the `sreq` since now the rdma part uses `MPIDI_OFI_AM_RREQ_HDR`, which is separate from the SREQ region.

Comment (raffenet) [reply src/mpid/ch4/netmod/ofi/ofi_events.c:491]: OK, I think I get it now.

**Review by raffenet — APPROVED** [review]

**Comment by hzhou** [comment]
test:mpich/ch4/ofi
