### PR TITLE
binding/f90: revamp f90 generation with python

### LINKED ISSUE #4812: mpi_gather is not explicitly declared with implicit none (external) in Fortran
Consider the following Fortran program:
```
program test_prg
  use mpi
  implicit none (type, external)
  integer :: source, dest, ierr
  call MPI_Init(ierr)
  call MPI_Gather(source, 1, MPI_INTEGER, dest, 1, MPI_INTEGER, 0, MPI_COMM_WORLD, ierr)
  call MPI_Finalize(ierr)
end program
```
An attempt to compile with `mpifort test_prg.F90 -ffree-line-length-0` (gfortran 10.2, mpich 3.3.2) results in the following error message:
```
6 |   call MPI_Gather(source, 1, MPI_INTEGER, dest, 1, MPI_INTEGER, 0, MPI_COMM_WORLD, ierr)
  |                                                                                        1
Error: Procedure ‘mpi_gather’ called at (1) is not explicitly declared; did you mean ‘mpi_barrier’?
```

Note, that there are no problems with `MPI_Init` and `MPI_Finalize`. The same program works with `mpi_f08`. So is `MPI_Gather` actually not explicitly declared in `mpi` or is this a `gfortran` bug?

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
This PR partially replaces the perl script `buildiface` to generate routine interfaces in `mpi_base.f90`. 

Fixes #4812 
Partially addresses #4300
[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

File: test/mpi/autogen.sh [hunk 1]
```diff
@@ -31,6 +31,10 @@ echo "Running autoreconf in dtpools"
 # Create and/or update the f90 tests
 printf "Create or update the Fortran 90 tests derived from the Fortran 77 tests... "
 for dir in f77/* ; do
+    if [ $dir = 'f77/profile' ] ; then
+        # skip profiling test for "use mpi"
+        continue
+    fi
```
Comment (raffenet) [inline test/mpi/autogen.sh:37]: Not sure I understand why the compiler won't allow the profiling routines. Could you explain more?

File: configure.ac [hunk 2]
```diff
@@ -4236,8 +4239,10 @@ AC_SUBST(pkgconfigdir)
 export pkgconfigdir
 
 if test "$f08_works" = "yes" ; then
-    PAC_CHECK_PYTHON
     PAC_FC_CHECK_REAL128
+    if test -z "$PYTHON" -a ! -f src/binding/fortran/use_mpi_f08/mpi_f08.f90 ; then
+        AC_MSG_ERROR([Python 3 is required to generate F08 bindings but not found!])
+    fi
```
[the remark this answers is not in the document]
Comment (hzhou) [reply configure.ac:4254]: The workaround of missing "Python 3" is to pre-generate the bindings on a machine that has Python 3. The addition here is to enable this workaround -- when `mpi_f08.f90` already exist, we assume the bindings are pre-generated, and let user continue.

Just noticed that I need wrap the following `AC_CONFIG_COMMANDS` inside `if test -n "$PYTHON"`... will update.

File: test/mpi/autogen.sh (hunk 1 above)
Comment (hzhou) [reply test/mpi/autogen.sh:37]: In `test/mpi/f77/profile/profile1f.f`, it includes a `subroutine mpi_send`. Now that `mpi_send` is listed in the `mpi.mod` interface, the compiler doesn't allow a duplicated one.

Comment (raffenet) [reply test/mpi/autogen.sh:37]: I see. The MPI Forum suggests renaming the interface when using the module inside the subroutine definition in order to workaround this problem. See MPI-4.0 pg 803. It does work in my limited testing, though we'll either have to modify the test conversion script or just commit this test by itself.
```fortran
       subroutine mpi_send( smsg, count, dtype, dest, tag, comm, ierr )
       use mpi, my_noname => mpi_send
```

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

File: configure.ac (hunk 2 above)
[the remark this answers is not in the document]
Comment (hzhou) [reply configure.ac]: Updated.

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch4/ucx

File: test/mpi/autogen.sh (hunk 1 above)
Comment (hzhou) [reply test/mpi/autogen.sh]: The fix works for gfortran-4.9+. But gfortran-4.8 doesn't support ignore-tkr, thus mpi.mod doesn't contain routines as `mpi_send`, the above fix won't compile. I added a `sed` in configure to patch it if that is the case.

**Review by raffenet — APPROVED** [review]

File: test/mpi/autogen.sh (hunk 1 above)
Comment (hzhou) [reply test/mpi/autogen.sh]: Note: the `sed` in configure potentially modifies a distributed file, thus it is a bit hairy. Fortran doesn't do macros, and I don't have a good solution to do autoconf `.in` substitution. So that leaves the solution of moving `f77tof90` to a config command in `configure`. 

I'll go ahead merge this PR. If we decide to move `f77tof90` to configure, we can patch it later.

Comment (hzhou) [reply test/mpi/autogen.sh]: Oh, the complication is, `f77tof90` will generate automaker files, so it will mess up the autoconf flow. So we'll need find another solution
