### PR TITLE
ch4/ofi: fix potential mismatch in dynamic_sendrecv

### LINKED ISSUE #7458: `MPI_Intercomm_create` segfaults on Aurora
Just wanted to log some info on a possible bug. Fails with segfault on a single node but not on multi-node. Backtrace collected with the following module `mpich/dbg/develop-git.6037a7a`. This functionality used to work fine before the MPICH was updated to this particular module/commit

The application affected is [NWChemEx](https://github.com/NWChemEx) & [ExaChem](https://github.com/ExaChem/exachem). 

The app uses PGAS project [GlobalArrays](https://github.com/GlobalArrays/ga) underneath and I couldn`t come up with a reproducer yet. Will be adding more relevant details

```bash
#0  0x0000153a358fdaf0 in extract_remote_data (remote_data=0x36baa40, remote_size_out=0x7ffdf38d5a5c, remote_context_id_out=0x7ffdf38d5a40, remote_lpids_out=0x7ffdf38d5570, remote_upid_sizes_out=0x7ffdf38d5568, remote_upids_out=0x7ffdf38d5560)
    at src/mpid/ch4/src/ch4_comm.c:604
#1  0x0000153a358fc373 in MPID_Intercomm_exchange (local_comm=0x153a35c91c98 <MPIR_Comm_direct+12824>, local_leader=0, peer_comm=0x153a35c8fff8 <MPIR_Comm_direct+5496>, remote_leader=4, tag=262144, context_id=432, remote_context_id_out=0x7ffdf38d5a40, 
    remote_size_out=0x7ffdf38d5a5c, remote_lpids_out=0x7ffdf38d5a50, timeout=0) at src/mpid/ch4/src/ch4_comm.c:390
#2  0x0000153a356fedc4 in MPIR_Intercomm_create_timeout (local_comm_ptr=0x153a35c91c98 <MPIR_Comm_direct+12824>, local_leader=0, peer_comm_ptr=0x153a35c8fff8 <MPIR_Comm_direct+5496>, remote_leader=4, tag=262144, timeout=0, new_intercomm_ptr=0x7ffdf38d5b30)
    at src/mpi/comm/comm_impl.c:851
#3  0x0000153a356fe600 in MPIR_Intercomm_create_impl (local_comm_ptr=0x153a35c91c98 <MPIR_Comm_direct+12824>, local_leader=0, peer_comm_ptr=0x153a35c8fff8 <MPIR_Comm_direct+5496>, remote_leader=4, tag=0, new_intercomm_ptr=0x7ffdf38d5b30) at src/mpi/comm/comm_impl.c:818
#4  0x0000153a350a2c13 in internal_Intercomm_create (local_comm=-2080374777, local_leader=0, peer_comm=-2080374781, remote_leader=4, tag=0, newintercomm=0x7ffdf38d5bec) at src/binding/c/comm/intercomm_create.c:116
#5  0x0000153a350a22e5 in PMPI_Intercomm_create (local_comm=-2080374777, local_leader=0, peer_comm=-2080374781, remote_leader=4, tag=0, newintercomm=0x7ffdf38d5bec) at src/binding/c/comm/intercomm_create.c:174
#6  0x0000153a3fc0ebaf in comex_group_create (n=n@entry=12, pid_list=pid_list@entry=0x36706f0, id_parent=id_parent@entry=0, id_child=<optimized out>)
    at /lus/flare/projects/NWChemEx_aesp_CNDA/abagusetty/shared_vs_static_onemkl/exachemdev_mpipr_mpichdbgdevelopgit6037a7a_06-13-2025/TAMM/build_oneapi2025.0.5-mpichdbgdevelopgit6037a7a/GlobalArrays_External-prefix/src/GlobalArrays_External/comex/src-mpi-pr/groups.c:343
#7  0x0000153a3fbefeca in armci_init_domains (comm=-2080374781)
```

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
When MPIDI_OFI_ENABLE_DATA is off, the dynamic message matching does not distinguish sources, resulting in potential mismatch. Enhance it with match bits derived from source address.

Fixes #7458

[skip warnings]
## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

File: src/mpid/ch4/netmod/ofi/ofi_spawn.c [hunk 1]
```diff
@@ -6,10 +6,17 @@
 #include "mpidimpl.h"
 #include "ofi_impl.h"
 #include "ofi_noinline.h"
+#include "uthash.h"
 
 /* NOTE: all these functions assume the caller to enter VCI-0 critical section */
 
+/* NOTE: MPIDI_OFI_dynamic_{send,recv} is an "any source" message that is used for initial MPI_Comm_{connect/accept},
+ *       while MPIDI_OFI_dynamic_sendrecv require exact source matching. That latter uses get_dynamic_match_bits
+ *       for match_bits.
```
Comment (raffenet) [inline src/mpid/ch4/netmod/ofi/ofi_spawn.c]: maybe this comment is from a previous version where both cases didn't use `get_dynamic_match_bits`?

Comment (raffenet) [reply src/mpid/ch4/netmod/ofi/ofi_spawn.c]: is there still a danger of an "any source" recv jumping in front of the recv with the source and still causing issues?

**Review by raffenet — COMMENTED** [review]
I trust this resolves whatever issue that raised it in testing. I'm just wondering how we can always prevent `MPIDI_OFI_dynamic_recv` from unintentionally matching with a message destined for a recv with source matching. Setting the source in the match bits won't matter if those bits are ignored.

File: src/mpid/ch4/netmod/ofi/ofi_spawn.c (hunk 1 above)
Comment (hzhou) [reply src/mpid/ch4/netmod/ofi/ofi_spawn.c]: Hmm, maybe...

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

File: src/mpid/ch4/netmod/ofi/ofi_spawn.c (hunk 1 above)
Comment (hzhou) [reply src/mpid/ch4/netmod/ofi/ofi_spawn.c]: I added the last commit to separate the matching space between the dynamic connection (send and recv) from the dynamic data exchange (MPIDI_NM_dynamic_sendrecv).

**Comment by hzhou** [comment]
> LGTM. I'm a little surprised to see that the mask bits for the dynamic recvs are always 0. I guess the only chance of collision is when rank 0 is the one getting embedded in the match bits. Any other rank shouldn't have that problem if I understand correctly? Setting the high bit should be enough to differentiate these messages then.

Since it is an anysource recv, the mask bits just need ignore the source bits. But since we are not setting the source bits in the sender anyway, there is nothing to mask.
