### PR TITLE
mpi_t: check the CVAR scope before attempting to write to it

### LINKED ISSUE #2654: bug: mpi_t/cvarwrite.c test case fails when cvars are constant or read-only scope
The mpi_t_/cvarwrite.c test case is failing when cvars scope is either constant or read-only.

Currently the test case only checks the cvar's binding and datatype before trying to write to it, without regard for whether the scope allows for writing.

The error output when running the test on ill-suited cvars looks like this:

```
$ srun -n 1 ./cvarwrite
INTERNAL ERROR: invalid error code 44 (Ring ids do not match) in PMPI_T_cvar_write:135
Rank 0 [Wed Oct 26 14:46:31 2016] [c0-0c0s6n0] Fatal error in PMPI_T_cvar_write: Other MPI error, error stack:
PMPI_T_cvar_write(149):  MPI_T_cvar_write(handle=0x9aaac0, buf=0x7fffffff5880)
PMPI_T_cvar_write(135):
srun: error: nid00024: task 0: Aborted
srun: Terminating job step 87614.0
```

It looks like this is an opportunity to use a more descriptive error message when trying to write to a constant or read-only cvar.

### PR DESCRIPTION
**Pull request by sudheer9**
mpi_t: check the CVAR scope before attempting to write to it 

fixes #2654

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

File: test/mpi/mpi_t/cvarwrite.c [hunk 1]
```diff
@@ -46,6 +46,9 @@ int main(int argc, char *argv[])
         if (binding != MPI_T_BIND_NO_OBJECT)
             continue;
 
+        if (scope == MPI_T_SCOPE_READONLY && scope == MPI_T_SCOPE_CONSTANT)
```
Comment (raffenet) [inline test/mpi/mpi_t/cvarwrite.c:49]: Shouldn't this be logical OR?

Comment (sudheer9) [reply test/mpi/mpi_t/cvarwrite.c]: Yeah, it should be.

**Review by raffenet — APPROVED** [review]
