### PR TITLE
config: move f08 autogen to configure

### LINKED ISSUE #4005: Fortran: disable real128 when compiler does not support
Fails with v3.3.1, v.3.2.1 is OK:
```
src/binding/fortran/use_mpi_f08/mpi_f08_types.f90:355:16:

  355 |     real(real128),dimension(..) :: x
      |                1
Error: Kind -1 not supported for type REAL at (1)
src/binding/fortran/use_mpi_f08/mpi_f08_types.f90:385:19:

  385 |     complex(real128),dimension(..) :: x
      |                   1
Error: Kind -1 not supported for type COMPLEX at (1)
src/binding/fortran/use_mpi_f08/mpi_f08_types.f90:383:36:

  383 | subroutine MPI_Sizeof_xcomplex128 (x, size, ierror)
      |                                    1
Error: Symbol ‘x’ at (1) has no IMPLICIT type
src/binding/fortran/use_mpi_f08/mpi_f08_types.f90:353:33:

  353 | subroutine MPI_Sizeof_xreal128 (x, size, ierror)
      |                                 1
Error: Symbol ‘x’ at (1) has no IMPLICIT type
src/binding/fortran/use_mpi_f08/mpi_f08_types.f90:353:30:

  353 | subroutine MPI_Sizeof_xreal128 (x, size, ierror)
      |                              1
......
  383 | subroutine MPI_Sizeof_xcomplex128 (x, size, ierror)
      |                                 2
Error: Ambiguous interfaces in generic interface 'mpi_sizeof' for ‘mpi_sizeof_xreal128’ at (1) and ‘mpi_sizeof_xcomplex128’ at (2)
make: *** [Makefile:48733: src/binding/fortran/use_mpi_f08/mpi_f08_types.stamp] Error 1
```
Fails in Fedora rawhide, F31, F30.

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
The f08 bindings need some configure check to properly generate. For
example, whether REAL128 is supported and whether MPI-IO is included.

Fixes #4005

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
compiler: intel

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
compiler: intel

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
compiler: intel

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
compiler: intel

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
compiler: intel

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
compiler: intel

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
compiler: intel

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
compiler: intel

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
compiler: intel

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
compiler: intel

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
compiler: intel

**Comment by hzhou** [comment]
test:mpich/custom --disable-romio
netmod: ch4:ofi
compiler: intel

**Comment by hzhou** [comment]
test:mpich/custom --disable-romio
netmod: ch4:ofi
compiler: intel

**Comment by hzhou** [comment]
test:mpich/custom --disable-romio
netmod: ch4:ofi
compiler: intel

**Comment by hzhou** [comment]
test:mpich/custom --disable-romio
netmod: ch4:ofi
compiler: intel

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
compiler: intel

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
Tested on Raspberry Pi (one of the systems that known won't support `real128`) and it is working, although takes an awful while.

File: autogen.sh [hunk 1]
```diff
@@ -824,7 +824,6 @@ if [ $do_bindings = "yes" ] ; then
 	# Top-level files
 	( cd src/binding/fortran/use_mpi_f08 && chmod a+x ./buildiface && ./buildiface )
         # generate src/binding/fortran/use_mpi_f08/wrappers_c/...
-        $PYTHON maint/gen_binding_f08.py
```
Comment (raffenet) [inline autogen.sh:827]: So this introduces a `python3` dependency on tarball builds, not just developer builds.

**Review by raffenet — COMMENTED** [review]
So adding the python3 dependency to `configure` concerns me some, since its non-standard on most systems today unless I am mistaken. I'm curious what others think @pmodels/mpich-dev.

File: autogen.sh [hunk 2]
```diff
@@ -1033,7 +1032,7 @@ if [ "$do_build_configure" = "yes" ] ; then
                 else
                     echo "failed"
                 fi
-                echo_n "Patching libtool.m4 for compatibility macOS Big Sur..."
+                echo_n "Patching libtool.m4 for compatibility macOS BigSur..."
```
Comment (wesbland) [inline autogen.sh:1035]:
```suggestion
                echo_n "Patching libtool.m4 for compatibility macOS Big Sur..."
```

Why the change here?

File: autogen.sh (hunk 1 above)
Comment (wesbland) [reply autogen.sh:827]: I don't have a strong feeling either way. We already require for ourselves so it doesn't impact me. I don't know how users will feel about it.

Is there a strong need for it? We use it in the MPI Forum I assume because it's easier than not using it, but it could probably be written without it.

That being said (and I'm not a Python expert), Python 3 is how old now?

Comment (hzhou) [reply autogen.sh:827]: Yes. Python 2 has been officially deprecated for a while now, so I expect most systems have python 3 in one form or another.

Comment (hzhou) [reply autogen.sh:827]: I just don't understand why people hate Perl, it won't have any such issues...

Comment (raffenet) [reply autogen.sh:827]: Please correct me if I am wrong, but tarball builds are still quite bare in their dependencies. Adding Python, in any form, is a significant change. In my mind, it's
```
sh
C
C++ (optional)
Fortran (optional)
make
```
Am I missing anything?

Comment (hzhou) [reply autogen.sh:827]: Yes, It is a significant change. It is adding --
```
   Python 3 (optional, required to build f08)
```
Just to be clear, this is a solution so the f08 build can correctly --

1. properly support `real128`
2. properly support `--disable-romio`

Currently, users have to 

1. manually delete the `real128` code if their system doesn't support `real128`
2. can't build without romio or they won't be able to link any Fortran program

The potential benefit, in addition to fixing current issues,

1. Smaller distribution tarballs
2. Potential to simplify configure as we may be able to move some complexities from configure into Python and let configure just do feature detection.

And the con side --

1. User will need install Python 3 if they need build Fortran with f08

Comment (raffenet) [reply autogen.sh:827]: For the benefit of understanding, how much more complex would this be to do with conditional compilation vs. generation? What I'm getting at is, how many files are affected by the configuration? Could we pre-generate multiple versions in` autogen.sh` and use `AM_CONDITIONAL` to build the "right" ones? I realize this means `autogen.sh` still has to do some unnecessary work, but the new buildiface scripts seem way faster that the old ones, so that's less of a concern in my mind.

Comment (raffenet) [reply autogen.sh:827]: I do want to avoid generating the full cross-product of
```
real128+romio
no real128+romio
real128+no romio
no real128+no romio
```
if possible.

File: autogen.sh (hunk 2 above)
Comment (hzhou) [reply autogen.sh:1035]: "Sur" triggers spell checker.

Comment (wesbland) [reply autogen.sh:1035]: Then the spell checker is wrong. 😄 The name of the OS is "macOS Big Sur".

Surely there's a way to add terms to the dictionary?

File: autogen.sh (hunk 1 above)
Comment (hzhou) [reply autogen.sh:827]: It is not complex to achieve, but it is not elegant -- any newly discovered or developed similar issue will exponentially grow the solution.

If we are really driven to avoid Python dependency, I think we can --
1. move `mpi_f08_types.f90` to `mpi_f08_types.f90.in` and let configure to replace `real128` into `real64`.
2. Build empty stubs with `--disable-romio`

I am really motivated by the prospect of reducing `xxx.in` files and simplify configure complexities. How about let's first discuss the "con"-side of having Python dependency. What is the practical impact?

File: autogen.sh (hunk 2 above)
Comment (hzhou) [reply autogen.sh:1035]: Yes. I am looking at the balance of "local ugliness of a hack" vs. "the long-range maintenance impact of a *correct* solution" (and who is caring for it).

File: autogen.sh (hunk 1 above)
Comment (raffenet) [reply autogen.sh:827]: > I am really motivated by the prospect of reducing `xxx.in` files and simplify configure complexities. How about let's first discuss the "con"-side of having Python dependency. What is the practical impact?

Most likely a lot of confused users asking why `./configure` failed 😄. This can _hopefully_ be overcome with a good error message and the passage of time. Package maintainers can be notified in a release announcement, so I'm less concerned about them.

And just to be clear, I'm not really thinking about Python 2 vs. 3, just Python in general.

Comment (raffenet) [reply autogen.sh:827]: A point of reference: PETSc is one project that requires Python in their `configure` script.
```
if sys.version_info < (2,6) or (sys.version_info >= (3,0) and sys.version_info < (3,4)):
  print('************************************************************************')
  print('*      Python version 2.6+ or 3.4+ is required to run ./configure      *')
  print('*         Try: "python2.7 ./configure" or "python3 ./configure"        *')
  print('************************************************************************')
  sys.exit(4)
```

Comment (hzhou) [reply autogen.sh:827]: That's a Python script. How would they print that message if "Python" is not available?

Comment (hzhou) [reply autogen.sh:827]: Oh, their configure apparently is a python script

Comment (raffenet) [reply autogen.sh:827]: Right. I'll reach out to those folks to see if they can share any experience/headaches from using Python in configure.

Comment (hzhou) [reply autogen.sh:827]: Are they using Meson https://github.com/mesonbuild/meson?

Comment (hzhou) [reply autogen.sh:827]: Found a whole page of python build tools: https://wiki.python.org/moin/ConfigurationAndBuildTools

**Review by raffenet — CHANGES_REQUESTED** [review]
Let's add a note in CHANGES then go ahead and merge this. We'll use the next pre-release to decide whether people have a problem with the new requirement.

**Comment by hzhou** [comment]
`CHANGES` updated in the last commit

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
compiler: intel
