### PR TITLE
ch4/ofi: fix address exchange assertion

### LINKED ISSUE #5552: ch4/ofi: assertion failure during address exchange under multi-NIC
Config: psm2 + multi-nic + mult-vci (passes for single vci)
Replicated with SEP, have not tested with mutiple-domains

(error goes away with single NIC:  env: export MPIR_CVAR_CH4_OFI_MAX_NICS=1)

```
Assertion failed in file src/mpid/ch4/netmod/ofi/init_addrxchg.c at line 300: av->dest[nic][vni] == get_av_table_index(r, nic, vni)
Tests: all under multi-nic.
```

Finding: Address exchange is failing when using multiple-nics are used. Address entry returned by `get_av_table_index` is not matching an expected value. Tests run fine after removing the av table valuation/assertion.

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
Fix get_av_table_index when SEP is used for vni contexts, when it is
equivalent to single vni for the purpose of address exchange.       

Fixes #5552

[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

File: src/mpid/ch4/netmod/ofi/init_addrxchg.c [hunk 1]
```diff
@@ -60,7 +60,12 @@ static int get_av_table_index(int rank, int nic, int vni)
             return rank;
         }
     } else {
+#ifdef MPIDI_OFI_VNI_USE_DOMAIN
         int num_vnis = MPIDI_OFI_global.num_vnis;
+#else
+        /* with scalable endpoint as context, all vnis share the same address. */
+        int num_vnis = 1;
```
Comment (sagarth) [inline src/mpid/ch4/netmod/ofi/init_addrxchg.c:67]: I think this variable should be named something else to avoid confusion with the actual number vnis that we use for SEP, which can still be higher than one. Maybe `num_domains`?

Comment (hzhou) [reply src/mpid/ch4/netmod/ofi/init_addrxchg.c:67]: This is a local variable with the scope of a few lines. And it also has a comment explaining why it is set to `1` in the case of SEP. I think it is fine. `num_domains` would be a new name that isn't used elsewhere and I think it is not necessarily easier to read.

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

File: src/mpid/ch4/netmod/ofi/init_addrxchg.c (hunk 1 above)
Comment (sagarth) [reply src/mpid/ch4/netmod/ofi/init_addrxchg.c:67]: Hmm.. with the comment, it's probably fine.

File: src/mpid/ch4/netmod/ofi/init_addrxchg.c [hunk 2]
```diff
@@ -160,7 +160,7 @@ int MPIDI_OFI_addr_exchange_root_ctx(void)
 /* Step 2 & 3: exchange non-root contexts */
 
 /* Macros to reduce clutter, so we can focus on the ordering logics.
- * Note: they are not perfectly-wraaped, but tolearable since only used here. */
+ * Note: they are not perfectly-wrapped, but tolearable since only used here. */
```
Comment (raffenet) [inline src/mpid/ch4/netmod/ofi/init_addrxchg.c:163]: `s/tolearable/tolerable/`. I'd also remove the hyphen from perfectly-wrapped if no one else objects.

File: src/mpid/ch4/netmod/ofi/init_addrxchg.c (hunk 1 above)
Comment (raffenet) [reply src/mpid/ch4/netmod/ofi/init_addrxchg.c:67]: Its odd to look at, but I'm not sure `num_domains` or `num_eps` is that much better. I guess I agree it's probably fine as-is.

File: src/mpid/ch4/netmod/ofi/init_addrxchg.c (hunk 2 above)
Comment (hzhou) [reply src/mpid/ch4/netmod/ofi/init_addrxchg.c]: Fixed.

**Review by raffenet — APPROVED** [review]
