### PR TITLE
ch4/ofi: fix multiple nic with "multi_nic_pref_nic" hint

### LINKED ISSUE #6419: bug/jenkins: ch4-ofi-amonly multinic-infohints
```
not ok 2683 - ./impls/mpich/threads/pt2pt/multinic_infohints 2
  ---
  Directory: ./impls/mpich/threads/pt2pt
  File: multinic_infohints
  Num-procs: 2
  Timeout: 180
  Date: "Fri Feb 24 15:31:25 2023"
  ...
## Test output (expected 'No Errors'):
## [mpiexec@pmrs-centos64-240-02.cels.anl.gov] APPLICATION TIMED OUT, TIMEOUT = 180s
## 
##   uptime:
##  15:31:25 up 459 days,  6:08,  0 users,  load average: 2.19, 2.52, 3.37
```
This appears to be a persistent failure that recently showed up.

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
When "multi_nic_pref_nic" hint is used, we inconsistently use the preferred nic despite the am code explicitly setting nic to 0.

Fixes #6419 

[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by nusislam** [comment]
Even when `pref_nic` is set, active message transfers will use NIC-0 with this PR, whereas others will use the pref_nic. Is this right?

**Comment by hzhou** [comment]
> Even when `pref_nic` is set, active message transfers will use NIC-0 with this PR, whereas others will use the pref_nic. Is this right?

Yes. To let active message to use `pref_nic` will require we allocating per-nic resources for the active message path and also expand the header to track source nic and destination nic similar to what we did with vci. Since active messages are mostly serve as a fallback path, I don't think the explosion of complexities would be worth it.

File: src/mpid/ch4/netmod/ofi/ofi_am_impl.h [hunk 1]
```diff
@@ -24,52 +24,68 @@ MPL_STATIC_INLINE_PREFIX int MPIDI_OFI_progress_do_queue(int vni_idx);
...
+MPL_STATIC_INLINE_PREFIX uint16_t MPIDI_OFI_am_get_next_recv_seqno(int vni, uint64_t remote_id)
 {
-    uint64_t id = addr;
     void *r;
 
-    r = MPIDIU_map_lookup(MPIDI_OFI_global.per_vni[vni].am_recv_seq_tracker, id);
+    r = MPIDIU_map_lookup(MPIDI_OFI_global.per_vni[vni].am_recv_seq_tracker, remote_id);
     if (r == MPIDIU_MAP_NOT_FOUND) {
-        MPL_DBG_MSG_FMT(MPIDI_CH4_DBG_GENERAL, VERBOSE,
-                        (MPL_DBG_FDEST, "First time adding recv seqno addr=%" PRIx64 "\n", addr));
```
Comment (raffenet) [inline src/mpid/ch4/netmod/ofi/ofi_am_impl.h:56]: I prefer not to delete these debug messages.

File: src/mpid/ch4/netmod/ofi/ofi_am_impl.h [hunk 2]
```diff
@@ -24,52 +24,68 @@ MPL_STATIC_INLINE_PREFIX int MPIDI_OFI_progress_do_queue(int vni_idx);
...
 }
 
-MPL_STATIC_INLINE_PREFIX void MPIDI_OFI_am_set_next_recv_seqno(int vni, fi_addr_t addr,
+MPL_STATIC_INLINE_PREFIX void MPIDI_OFI_am_set_next_recv_seqno(int vni, uint64_t remote_id,
                                                                uint16_t seqno)
 {
-    uint64_t id = addr;
-
-    MPL_DBG_MSG_FMT(MPIDI_CH4_DBG_GENERAL, VERBOSE,
-                    (MPL_DBG_FDEST, "Next recv seqno=%d addr=%" PRIx64 "\n", seqno, addr));
```
Comment (raffenet) [inline src/mpid/ch4/netmod/ofi/ofi_am_impl.h:70]: Prefer not to delete.

File: src/mpid/ch4/netmod/ofi/ofi_am_impl.h [hunk 3]
```diff
@@ -111,12 +127,8 @@ MPL_STATIC_INLINE_PREFIX MPIDI_OFI_am_unordered_msg_t
      * If it's not the case, we should consider using better data structure and algorithm
      * to look up. */
     DL_FOREACH(MPIDI_OFI_global.per_vni[vni].am_unordered_msgs, uo_msg) {
-        if (uo_msg->am_hdr.fi_src_addr == addr && uo_msg->am_hdr.seqno == seqno) {
-            MPL_DBG_MSG_FMT(MPIDI_CH4_DBG_GENERAL, TERSE,
-                            (MPL_DBG_FDEST,
-                             "Found unordered message in the queue: addr=%" PRIx64 ", seqno=%d\n",
-                             addr, seqno));
```
Comment (raffenet) [inline src/mpid/ch4/netmod/ofi/ofi_am_impl.h:118]: Prefer not to delete.

File: src/mpid/ch4/netmod/ofi/ofi_impl.h [hunk 4]
```diff
@@ -455,37 +461,35 @@ MPL_STATIC_INLINE_PREFIX int MPIDI_OFI_vci_to_vni_assert(int vci)
     return vni;
 }
 
-MPL_STATIC_INLINE_PREFIX fi_addr_t MPIDI_OFI_av_to_phys(MPIDI_av_entry_t * av, int nic,
-                                                        int vni_local, int vni_remote)
+/* NOTE: in general, the address can be different between any two endpoints. Thus, we need
+ *       a 4 dimension tuple of (nic_local, vni_local, nic_remote, vni_remote) for a given addr.
+ *       However, libfabric let us to have the same addr for a (nic_remote, vni_remote) pair
+ *       on any local endpoints, as long as we are careful in the isertion order). Thus,
```
Comment (raffenet) [inline src/mpid/ch4/netmod/ofi/ofi_impl.h:467]:
```suggestion
 *       on any local endpoints, as long as we are careful in the insertion order). Thus,
```

**Review by raffenet — COMMENTED** [review]
Looks good to me. Just some minor comments.

File: src/mpid/ch4/netmod/ofi/ofi_rma.c [hunk 5]
```diff
@@ -66,7 +66,9 @@ int MPIDI_OFI_nopack_putget(const void *origin_addr, MPI_Aint origin_count,
     /* allocate request */
     MPIDI_OFI_win_request_t *req = MPIDI_OFI_win_request_create();
     MPIR_ERR_CHKANDSTMT((req) == NULL, mpi_errno, MPIX_ERR_NOREQ, goto fn_fail, "**nomemreq");
-    req->vni = MPIDI_WIN(win, am_vci);
+    req->vni_local = MPIDI_WIN(win, am_vci);
+    req->vni_target = MPIDI_WIN_TARGET_VCI(win, target_rank);
```
Comment (sagarth) [inline src/mpid/ch4/netmod/ofi/ofi_rma.c:70]: Would it be make sense to change the name `MPIDI_WIN` to something similar as `MPIDI_WIN_TARGET_VCI`?

Comment (hzhou) [reply src/mpid/ch4/netmod/ofi/ofi_rma.c:70]: `MPIDI_WIN` is a macro to access the `win` struct. But I guess we can wrap into a new macro, `MPIDI_WIN_LOCAL_VCI`. Let's do that separately.

Comment (sagarth) [reply src/mpid/ch4/netmod/ofi/ofi_rma.c:70]: That sounds good

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Review by raffenet — APPROVED** [review]

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch4/most

File: src/util/mpir_pmi.c [hunk 6]
```diff
@@ -202,6 +203,7 @@ int MPIR_pmi_init(void)
     MPIR_Process.rank = rank;
     MPIR_Process.size = size;
     MPIR_Process.appnum = appnum;
+    HASH_FNV(pmi_kvs_name, strlen(pmi_kvs_name), MPIR_Process.world_id);
```
Comment (sonjahapp) [inline src/util/mpir_pmi.c:206]: @hzhou A comment on compatibility with PMIx: `pmi_kvs_name` only exists if `USE_PMI1_API` is defined. I run into a compile error for PMIx here. I think this hash needs a `#ifdef` case distinction for PMI1, PMI2 and PMIx. Or am I overlooking something?

Comment (hzhou) [reply src/util/mpir_pmi.c:206]: It was our negligence. Thanks for pointing it out. I'll push a PR to fix it.
