### PR TITLE
misc: fix spelling mistakes

### LINKED ISSUE #4982: Codespell report for "MPICH" (on fossies.org)
The FOSS server [fossies.org](https://fossies.org) - supporting also the "MPICH" project - offers among others a feature named "[Source code misspelling reports](https://fossies.org/features.html#codespell)". Such reports are normally only generated on request, but as Fossies administrator I have just created for testing purposes such a [codespell](https://github.com/codespell-project/codespell) based analysis for the "MPICH" release 3.4:

&nbsp;https://fossies.org/linux/misc/mpich/codespell.html

That version-independent URL should redirect always to the last report (if available), so currently to

&nbsp;https://fossies.org/linux/misc/mpich-3.4.tar.gz/codespell.html.

By the way, the context type of the spelling errors and typos are marked by a single character (within the sortable column "T"): The less interesting, probably not user visible ones (in "comments") are greyed, while the probably more interesting ones are black-colored. Of particular interest may be unassigned errors marked by a "?" since they may be contained in the source code itself (here I especially noticed the typo "stae -> state" at line 712 of the file [src/mpid/ch3/include/mpidpre.h](http://www.schiller-fossies.org/linux/misc/mpich-3.4.tar.gz/mpich-3.4/src/mpid/ch3/include/mpidpre.h?M=712#l_712)). Some more according information is offered by a tooltip if the mouse is over the string "error context type character" above the table, over the "T" in the table header or over such a context character itself within the table. If JavaScript is enabled all table columns are sortable.

Although after a first review some obviously wrong matches ("False Positives" = FPs) are already filtered out (ignored) please inform me if you find more of them so that I can force a new improved check if applicable.

Just for information there are also three supplemental pages showing some used "codespell" [configuration details](https://fossies.org/linux/misc/mpich/codespell_conf.html), all obvious [false positives](https://fossies.org/linux/misc/mpich/codespell_fps.html) and an [misspelling history](https://fossies.org/linux/misc/mpich/codespell_hist.html) (log).

Perhaps more meaningful may be a similar and continuously updated report for the MPICH GitHub "main" version which could be generated on request within a special restricted "test" folder that isn't really integrated into the standard Fossies services and should also not be accessible to search engines.

Although the correction of misspellings and typos has probably not a top priority, I hope that the report can nevertheless be a little bit useful.

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

Add maint/spellcheck.sh and apply it to the codebase. It uses [codespell](https://github.com/codespell-project/codespell) for spell checking.

Fixes #4982

[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Review by yfguo — APPROVED** [review]

**Comment by hzhou** [comment]
test:mpich/ch3/all
test:mpich/ch4/all

**Comment by hzhou** [comment]
test:mpich/ch4/argobots
test:mpich/ch4/pmi
test:mpich/ch4/xpmem

File: test/mpi/datatype/hvecblklen.c [hunk 1]
```diff
@@ -14,7 +14,7 @@
 */
 int main(int argc, char *argv[])
 {
-    MPI_Datatype ot, ot2, newtype;
+    MPI_Datatype dt, dt2, newtype;
```
Comment (raffenet) [inline test/mpi/datatype/hvecblklen.c:17]: I don't know the original motivation for using `ot`, but I'm not sure it qualifies as a spelling mistake.

File: test/mpi/datatype/vecblklen.c [hunk 2]
```diff
@@ -14,7 +14,7 @@
 */
 int main(int argc, char *argv[])
 {
-    MPI_Datatype ot, ot2, newtype;
+    MPI_Datatype dt, dt2, newtype;
```
Comment (raffenet) [inline test/mpi/datatype/vecblklen.c:17]: same comment about `ot` not being a spelling issue.

File: test/mpi/f08/coll/alltoallvf08.f90 [hunk 3]
```diff
@@ -8,7 +8,7 @@
       program main
       use mpi_f08
       integer ierr, errs
-      integer i, ans, size, rank, color
+      integer i, and, size, rank, color
```
Comment (raffenet) [inline test/mpi/f08/coll/alltoallvf08.f90:11]: this is not right.

File: test/mpi/f08/coll/alltoallwf08.f90 [hunk 4]
```diff
@@ -8,7 +8,7 @@
       program main
       use mpi_f08
       integer ierr, errs
-      integer i, intsize, ans, size, rank, color
+      integer i, intsize, and, size, rank, color
```
Comment (raffenet) [inline test/mpi/f08/coll/alltoallwf08.f90:11]: this is not right.

File: test/mpi/f08/coll/exscanf08.f90 [hunk 5]
```diff
@@ -25,7 +25,7 @@ subroutine uop( cin, cout, count, datatype )
       program main
       use mpi_f08
       integer inbuf(2), outbuf(2)
-      integer ans, rank, size
+      integer and, rank, size
```
Comment (raffenet) [inline test/mpi/f08/coll/exscanf08.f90:28]: this is not right.

File: test/mpi/f08/coll/nonblockingf08.f90 [hunk 6]
```diff
@@ -19,7 +19,7 @@ program main
       TYPE(MPI_Comm) comm
       TYPE(MPI_Request) req
       integer ierr, errs
-      integer ii, ans
+      integer ii, and
```
Comment (raffenet) [inline test/mpi/f08/coll/nonblockingf08.f90:22]: not right.

File: test/mpi/f08/coll/split_typef08.f90 [hunk 7]
```diff
@@ -8,7 +8,7 @@
       program main
       use mpi_f08
       integer ierr, errs
-      integer i, ans, size, rank, color
+      integer i, and, size, rank, color
```
Comment (raffenet) [inline test/mpi/f08/coll/split_typef08.f90:11]: not right.

File: test/mpi/f08/datatype/typesubf08.f90 [hunk 8]
```diff
@@ -13,7 +13,7 @@ program main
       integer fullsizes(2), subsizes(2), starts(2)
       integer fullarr(maxn,maxm),subarr(maxn-3,maxm-4)
       integer i,j, ssize
-      integer size, rank, ans
+      integer size, rank, and
```
Comment (raffenet) [inline test/mpi/f08/datatype/typesubf08.f90:16]: not right.

File: test/mpi/f08/io/ioharness.defn [hunk 9]
```diff
@@ -46,11 +46,11 @@ enddo
 
 <checkContigBuffer>
 do i=1, n
-    ans = r*n + (k-1)*n*s + i-1
-    if (buf(i) .ne. ans) then
+    and = r*n + (k-1)*n*s + i-1
```
Comment (raffenet) [inline test/mpi/f08/io/ioharness.defn:49]: not right.

File: test/mpi/f08/rma/winaccf08.f90 [hunk 10]
```diff
@@ -14,7 +14,7 @@ program main
       integer nrows, ncols
       parameter (nrows=25,ncols=10)
       integer buf(1:nrows,0:ncols+1)
-      integer ans
+      integer and
```
Comment (raffenet) [inline test/mpi/f08/rma/winaccf08.f90:17]: not right.

File: test/mpi/f08/rma/winfencef08.f90 [hunk 11]
```diff
@@ -14,7 +14,7 @@ program main
       integer nrows, ncols
       parameter (nrows=25,ncols=10)
       integer buf(1:nrows,0:ncols+1)
-      integer ans
+      integer and
```
Comment (raffenet) [inline test/mpi/f08/rma/winfencef08.f90:17]: not right.

File: test/mpi/f08/rma/wingetf08.f90 [hunk 12]
```diff
@@ -14,7 +14,7 @@ program main
       integer nrows, ncols
       parameter (nrows=25,ncols=10)
       integer buf(1:nrows,0:ncols+1)
-      integer ans
+      integer and
```
Comment (raffenet) [inline test/mpi/f08/rma/wingetf08.f90:17]: not right.

File: test/mpi/f08/rma/winscale1f08.f90 [hunk 13]
```diff
@@ -14,7 +14,7 @@ program main
       integer nrows, ncols
       parameter (nrows=25,ncols=10)
       integer buf(1:nrows,0:ncols+1)
-      integer ans
+      integer and
```
Comment (raffenet) [inline test/mpi/f08/rma/winscale1f08.f90:17]: not right.

File: test/mpi/f08/rma/winscale2f08.f90 [hunk 14]
```diff
@@ -14,7 +14,7 @@ program main
       integer nrows, ncols
       parameter (nrows=25,ncols=10)
       integer buf(1:nrows,0:ncols+1)
-      integer ans
+      integer and
```
Comment (raffenet) [inline test/mpi/f08/rma/winscale2f08.f90:17]: not right.

File: test/mpi/f77/io/ioharness.defn [hunk 15]
```diff
@@ -46,11 +46,11 @@ enddo
 
 <checkContigBuffer>
 do i=1, n
-    ans = r*n + (k-1)*n*s + i-1
-    if (buf(i) .ne. ans) then
+    and = r*n + (k-1)*n*s + i-1
```
Comment (raffenet) [inline test/mpi/f77/io/ioharness.defn:49]: not right.

File: test/mpi/f90/f90types/createf90types.c [hunk 16]
```diff
@@ -51,38 +51,38 @@ static int checkType(const char str[], int p, int r, int f90kind, int err, MPI_D
             errs++;
             printf("Wrong combiner type (got %d, should be %d) for %s\n", combiner, f90kind, str);
         } else {
-            int parms[2];
+            int params[2];
```
Comment (raffenet) [inline test/mpi/f90/f90types/createf90types.c:54]: this doesn't seem right.

File: test/mpi/threads/comm/idup_nb.c [hunk 17]
```diff
@@ -47,7 +47,7 @@ MTEST_THREAD_RETURN_TYPE test_intracomm(void *arg)
     int i, j;
     int root, bcastbuf;
     int rank, size;
-    int ans[4], expected[4];
+    int and[4], expected[4];
```
Comment (raffenet) [inline test/mpi/threads/comm/idup_nb.c:50]: not right.

File: test/mpi/threads/pt2pt/ibsend.c [hunk 18]
```diff
@@ -10,7 +10,7 @@
    It starts a single receiver thread that expects
    NUMSENDS from NUMTHREADS sender threads, that
    use [i]bsend/[i]send to send a message of size MSGSIZE
-   to its right neigbour or rank 0 if (my_rank==comm_size-1), i.e.
+   to its right neighbour or rank 0 if (my_rank==comm_size-1), i.e.
```
Comment (raffenet) [inline test/mpi/threads/pt2pt/ibsend.c:13]: neighbor

**Review by raffenet — CHANGES_REQUESTED** [review]
If this will need re-review, it needs to be broken up into smaller commits. Github made me click on individual files at some point because the diff was way too big. This took well over and hour to get through.

File: src/include/mpir_topo.h [hunk 19]
```diff
@@ -73,7 +73,7 @@ int MPIR_Topo_canon_nhb_count(MPIR_Comm * comm_ptr, int *indegree, int *outdegre
  * Section 7.6 of the MPI-3.0 standard. */
 int MPIR_Topo_canon_nhb(MPIR_Comm * comm_ptr,
                         int indegree, int sources[], int inweights[],
-                        int outdegree, int dests[], int outweights[]);
+                        int outdegree, int dests[], int outweighs[]);
```
Comment (raffenet) [inline src/include/mpir_topo.h:76]: outweights is correct.

File: test/mpi/f90/f90types/createf90types.c (hunk 16 above)
Comment (hzhou) [reply test/mpi/f90/f90types/createf90types.c:54]: I'll rename it to `ints` since we use `ints` in everywhere else.

**Comment by hzhou** [comment]
> 
> 
> If this will need re-review, it needs to be broken up into smaller commits. Github made me click on individual files at some point because the diff was way too big. This took well over an hour to get through.

Thanks @raffenet . I have updated some of the skip rules in `maint/spellcheck.sh`, and also pre-applied some manual spelling fix (e.g. British to US English). Now I think it addresses all the places you pointed out and the script is clean now. As you complained, I split the changes into 3 commits and on my browser seems GitHub is able to load each commit in its entirety.

Hopefully, this is a one-time thing and we will be able to keep the code spelling-clean :) 

Could you review it again?

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
compiler: intel

File: src/mpi/romio/adio/ad_lustre/ad_lustre_wrcoll.c [hunk 20]
```diff
@@ -1106,7 +1106,7 @@ static void ADIOI_LUSTRE_IterateOneSided(ADIO_File fd, const void *buf, int *str
      * aggregator.  The segmentLen is the maximum size in bytes of each segment
      * (stripeSize*number of aggs).  Iteratively call ADIOI_OneSidedWriteAggregation
      * for each segment to aggregate the data to the collective buffers, but only do
-     * the actual write (via flushCB stripe parm) once stripesPerAgg stripes
+     * the actual write (via flushCB stripe param) once stripesPerAgg stripes
```
Comment (raffenet) [inline src/mpi/romio/adio/ad_lustre/ad_lustre_wrcoll.c:1109]: This is an odd one. The struct is named `stripeParms`, which appears to be short for stripe parameters. So I think either param is technically correct, but parm is better in context.

**Review by raffenet — COMMENTED** [review]
Everything but my one comment looks good. Thanks for splitting up. This was way faster to review this time.

File: src/mpi/romio/adio/ad_lustre/ad_lustre_wrcoll.c (hunk 20 above)
Comment (hzhou) [reply src/mpi/romio/adio/ad_lustre/ad_lustre_wrcoll.c:1109]: I have whitelisted `parm`, I don't know how this one leaked through. Anyway, I thought `parm` is just an abbreviation of `param` which is an abbreviation of `parameter`. Is `parm` more preferred or does it have a different meaning?

Meanwhile, let me clean up that instance.

Comment (raffenet) [reply src/mpi/romio/adio/ad_lustre/ad_lustre_wrcoll.c:1109]: Personally I prefer "param", but the code in this instance historically uses "parm". I suggest we match the code instead of changing variable names in this instance.

Comment (hzhou) [reply src/mpi/romio/adio/ad_lustre/ad_lustre_wrcoll.c]: Oh, I *manually* did the quoted fix before I decided to whitelist `parm`. So the script is working after all. I have reverted the wrong *manual* change.

**Comment by hzhou** [comment]
@raffenet Rebased and (I believe) it should be good now. Could you take one more look?

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
compiler: intel

**Review by raffenet — APPROVED** [review]
