### PR TITLE
ch4/ofi: fix and refactor provider selection

### LINKED ISSUE #4188: ofi: provider tcp;ofi_rxm is not being picked up
When trying to run MPI with tcp;ofi_rxm, I usually set FI_PROVIDER=tcp which automatically picks up tcp;ofi_rxm. Intel MPI and Open MPI work with this method, but MPICH fails with ENODATA. If I specifically set FI_PROVIDER="tcp;ofi_rxm" it is fine. Is this expected? Does MPICH check provider names again and fail?

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

In `pick_provider` function where we loop through provider list for matching, we set `prov_use` first before checking the fields. When all providers fail the matching, `prov_use` will be set to the last provider in the list, which is wrong. In the PR, we fix this bug.

The code that initializes and update the settings are complex and repeated many times, very difficult to read. Using a local macro to allows more concise code.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
       Fixes #4188 #4187 #4185
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [x] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by hzhou** [comment]
Manually tested the following cases (on local linux ethernet):
```
$ ./configure --with-device=ch4:ofi --enable-g=dbg,log && make install
$ dbglog='-mpich-dbg=file -mpich-dbg-level=verbose -mpich-dbg-filename=dbg%d.log'
$ ./cpi $dbglog && grep -i provider dbg0.log
$ FI_PROVIDER='tcp;ofi_rxm' ./cpi $dbglog && grep -i provider dbg0.log
$ FI_PROVIDER='tcp' ./cpi $dbglog && grep -i provider dbg0.log
$ FI_PROVIDER='sockets' ./cpi $dbglog && grep -i provider dbg0.log
$ MPIR_CVAR_OFI_USE_PROVIDER=sockets ./cpi $dbglog && grep -i provider dbg0.log

**Comment by hzhou** [comment]
test:jenkins/ch4/ofi

**Comment by hzhou** [comment]
test:jenkins/ch4/ofi

**Comment by hzhou** [comment]
test:jenkins/ch4/ofi

**Comment by hzhou** [comment]
test:jenkins/ch4/ofi

**Comment by hzhou** [comment]
test:jenkins/ch4/ofi
test:jenkins/ch3/ofi

**Comment by hzhou** [comment]
Ready for review. Commit #4 shifts large amount of code, so it is better to be reviewed separately (instead of the diffs). Other commits are relatively trivial.

File: src/mpid/ch4/netmod/ofi/ofi_init.c [hunk 1]
```diff
@@ -1352,151 +1173,369 @@ static int create_endpoint(struct fi_info *prov_use, struct fid_domain *domain,
...
+    struct fi_info *prov_use = NULL;
+    /* We'll try to pick the best provider three times.
+     * 1 - Check to see if any provider matches an existing capability set (e.g. sockets)
+     * 2 - Check to see if any provider meets the default capability set
+     * 3 - Check to see if any provider meets the minimal capability set
+     */
+    bool provname_is_set = (provname &&
+                            strcmp(provname, MPIDI_OFI_SET_NAME_DEFAULT) != 0 &&
+                            strcmp(provname, MPIDI_OFI_SET_NAME_MINIMAL) != 0);
+    if (NULL == prov_use && provname_is_set) {
```
Comment (raffenet) [inline src/mpid/ch4/netmod/ofi/ofi_init.c]: `NULL == prov_use` is always true at this point, no?

Comment (hzhou) [reply src/mpid/ch4/netmod/ofi/ofi_init.c]: Yes. I tried to make the three round more uniform in appearance so in case (prob. unlikely) we want to add rounds or remove rounds, it is easier.

Comment (raffenet) [reply src/mpid/ch4/netmod/ofi/ofi_init.c]: OK, fair enough. I think this is good to go.

**Comment by raffenet** [comment]
Perhaps a broader question, are there modifications we should make to our Jenkins tests and scripts after this? Which provider gets picked now? verbs;ofi_rxm on Linux? Will tcp;ofi_rxm get picked on non-Linux platforms?

**Comment by raffenet** [comment]
> Perhaps a broader question, are there modifications we should make to our Jenkins tests and scripts after this? Which provider gets picked now? verbs;ofi_rxm on Linux? Will tcp;ofi_rxm get picked on non-Linux platforms?

To summarize offline discussion - there is no change to functionality or testing as a result of this PR. We still have some work to do to adjust our capability requirements to better support tcp/verbs;ofi_rxm.

**Comment by hzhou** [comment]
Test after rebase:

test:jenkins/ch3/ofi
test:jenkins/ch4/ofi
