### PR TITLE
coll: bug fix in ibcast_intra_sched_smp

### LINKED ISSUE #4635: Bug with MPI_Ibcast/MPI_Wait since 2020-02-14 on mpich/master
Hi,

first, sorry for the delay.  We noticed a failure with mpich/master since 2020-02-14.

Our nightly tests showed errors with MPI_Ibcast/MPI_Wait.

On 2020-02-13, always on mpich/master, everything was fine with SHA 44013c5f60 .

On 2020-02-14, our nightly tests tested cf1f4046798a and it was faulty.

Fortunately, the bug is very simple to reproduce: I happens only if the "root" of MPI_Ibcast is not 0, and it is visible only if someone check the return code of MPI_Wait (hum hum, that means there are no validation of this in MPICH nightly tests? )
 
Here is the simple reproducer attached, compiled and ran like this:
<pre>
mpicxx -o bug bug_ibcast_2020_02_14.cc
mpiexec -n 3 ./bug
</pre>

gives:

<pre>
Fatal error in PMPI_Wait: Other MPI error, error stack:
PMPI_Wait(199).................: MPI_Wait(request=0x7ffe00f508cc, status=0x7ffe00f508d0) failed
MPIR_Wait(99)..................: 
MPIDU_Sched_progress_state(958): Invalid communicator
Message from process 0 : Hello, world
Fatal error in PMPI_Wait: Other MPI error, error stack:
PMPI_Wait(199).................: MPI_Wait(request=0x7ffcae68070c, status=0x7ffcae680710) failed
MPIR_Wait(99)..................: 
MPIDU_Sched_progress_state(958): Invalid communicator
</pre>

[bug_ibcast_2020_02_14.zip](https://github.com/pmodels/mpich/files/4766872/bug_ibcast_2020_02_14.zip)

Thanks,

Eric

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
The ERROR_CHECKING of sched_test_length is supposed only for recv side,
but we accidentally checked on both side. The send side status is simply
garbage, causing errors.

Thanks Eric for reporting issue #4635.

## TODO

* [x] check testsuite to confirm the bug case is not covered or understand why
* [x] add test to cover the bug case if necessary

## Expected Impact
Fixes #4635 

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [x] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] You or your company has a signed contributor's agreement on file with Argonne
* [x] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll

**Comment by hzhou** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

File: test/mpi/coll/nonblocking2.c [hunk 1]
```diff
@@ -36,21 +36,23 @@ static void sum_fn(void *invec, void *inoutvec, int *len, MPI_Datatype * datatyp
...
-    int *recvbuf = NULL;
-    int *sendcounts = NULL;
-    int *recvcounts = NULL;
-    int *sdispls = NULL;
-    int *rdispls = NULL;
-    int *sendtypes = NULL;
-    int *recvtypes = NULL;
-    signed char *buf_alias = NULL;
-    MPI_Request req;
+    int root = 0;
```
Comment (raffenet) [inline test/mpi/coll/nonblocking2.c:55]: this doesn't appear to be used

File: test/mpi/coll/nonblocking2.c [hunk 2]
```diff
@@ -64,16 +66,35 @@ int main(int argc, char **argv)
...
+    free(recvtypes);
+    free(sendtypes);
+    return 0;
+}
+
+void test_icoll_with_root(int rank, int size, int root)
+{
+    int i, j;
 
+    root = size - 1;
```
Comment (raffenet) [inline test/mpi/coll/nonblocking2.c:88]: overriding input arg?

Comment (hzhou) [reply test/mpi/coll/nonblocking2.c:88]: Thanks for pointing out my negligence. I'll update it.

Comment (hzhou) [reply test/mpi/coll/nonblocking2.c]: Updated.

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll

File: src/mpi/coll/ibcast/ibcast_intra_sched_smp.c [hunk 3]
```diff
@@ -49,18 +49,19 @@ int MPIR_Ibcast_intra_sched_smp(void *buffer, int count, MPI_Datatype datatype,
...
                                        MPIR_Get_intranode_rank(comm_ptr, root), comm_ptr->node_comm,
                                        &ibcast_state->status, s);
-        }
-        MPIR_ERR_CHECK(mpi_errno);
-        MPIR_SCHED_BARRIER(s);
+            MPIR_ERR_CHECK(mpi_errno);
 #ifdef HAVE_ERROR_CHECKING
-        mpi_errno = MPIR_Sched_cb(&sched_test_length, ibcast_state, s);
-        MPIR_ERR_CHECK(mpi_errno);
+            MPIR_SCHED_BARRIER(s);
```
Comment (raffenet) [inline src/mpi/coll/ibcast/ibcast_intra_sched_smp.c:60]: It took me a second to realize this was just a local barrier and doesn't involve other processes. Maybe we should update that name, but that is a separate issue/PR.

Comment (hzhou) [reply src/mpi/coll/ibcast/ibcast_intra_sched_smp.c:60]: Maybe `MPIR_SCHED_STAGE`?
