### PR TITLE
hydra: reuse the same proxy for spawn

### LINKED ISSUE #2277: hydra: resource allocation and multiple mpi_comm_spawn's
**Originally by _jczhang_ on 2015-06-16 17:51:36 -0500**

---

Thanks to Arjen for reporting this and the patch.

See http://lists.mpich.org/pipermail/discuss/2015-June/004057.html
# 

Hello,

I've patched the hydra process manager (mpich release 3.1), to support
my case (see attachment).

It's a bit ugly (I have not prefixed the sort and compare function names
as these are local to the alloc.c file) but it works for me and makes
the resource allocation for consecutive MPI_COMM_SPAWNs more fair.

All I had to patch was 'utils/alloc/alloc.c' in the hydra source-code.

New procedure for allocating proxy's and assigning executables is now:
1. make proxies (NEW: make a proxy for every node, do not stop when
   number of processes is reached)
   2 (NEW). sort the proxies by their nodes active number of processes
   (decreasing, the first proxy will have the least number of processes)
2. allocate executables to the proxies

Should I create a bug report for this? (I can't find a login button on
the trac website)

Kind regards,

Arjen

---

From: Arjen van Elteren info@arjenvanelteren.com
Date: Fri, Jun 12, 2015 at 4:23 AM
Subject: [mpich-discuss] resource allocation and multiple mpi_comm_spawn's
To: discuss@mpich.org

Hello,

I'm working with an application that invokes multiple mpi_comm_spawn calls.

I'm using mpiexec on a cluster without a resource manager or job queue,
so plain ssh and fork calls and everything is managed by mpich.

It looks like mpiexec (both hydra and mpd) re-use the hostfile from the
start (and do not look at already allocated resources/used nodes).

For example I have a hostfile like this:

```
node01:1
node02:1
node03:1
```

When I run a call like this:

```
 MPI_Comm_spawn(cmd, MPI_ARGV_NULL, number_of_workers,
                 MPI_INFO_NULL, 2,
                 MPI_COMM_SELF, &worker,
                 MPI_ERRCODES_IGNORE);
```

I get an allocation like this:

```
node              process
---------------    ------------------
node01          manager
node02          worker 1
node03          worker 2
```

Which is what I expected.

But when I instead do 2 calls like this (i.e. each worker has one
process, but there are 2 workers):

```
 MPI_Comm_spawn(cmd, MPI_ARGV_NULL, number_of_workers,
                 MPI_INFO_NULL, 1,
                 MPI_COMM_SELF, &worker,
                 MPI_ERRCODES_IGNORE);

 MPI_Comm_spawn(cmd, MPI_ARGV_NULL, number_of_workers,
                 MPI_INFO_NULL, 1,
                 MPI_COMM_SELF, &worker,
                 MPI_ERRCODES_IGNORE);
```

I get an allocation like this (both hydra and mpd):

```
node              process
---------------    ------------------
node01          manager
node02          worker 1   + worker 2
node03
```

Which is not what I expected at all!

In fact, when I do this for a more complex example, I conclude that in
MPI_Comm_spawn the hostfile is simply re-interpreted for every spawn and
previous allocations in the same application are not accounted for.

I know I could set hostname in the MPI_Comm_spawn call,  but then I'm
moving deployment information into my application (and I don't want to
recompile or add a commandline argument for something that should be
handled by mpiexec)

Is there an option or easy fix for this problem? (I looked at the code
of hydra, but I'm unsure how the different proxy's and processes divide
this spawning work between them (I could not easily detect one "grand
master" that does the allocation...)

Kind regards,

Arjen

### LINKED ISSUE #2913: hydra: inactive hydra_pmi_proxy
To whom it may concern,

Problem summary: many inactive processes hydra_pmi_proxy during the running of mpirun.mpich -np 1 python etisp.py, Then the number of inactive processes hydra_pmi_proxy would exceed the limit number that a CPU would permit.

On my laptop I use

mpirun.mpich -np 1 python etisp.py

The process hydra_pmi_proxy spawned in

    for j in range(1):
        partsims.append(MPI.COMM_SELF.Spawn('esysparticle', args="partsim.py", maxprocs=2))

will continuously be recognized as a process after

    for ps in partsims:
        ps.send([], 0)
        ps.recv()    
        ps.Barrier()
        ps.Disconnect()

So, there will be many inactive processes hydra_pmi_proxy during the running of mpirun.mpich -np 1 python etisp.py. Then the number of inactive processes hydra_pmi_proxy would exceed the limit number that a CPU would permit.

When etisp.py is done, all hydra_pmi_proxy would be killed automatically.

Is there a way to kill the inactive process hydra_pmi_proxy during the running of mpirun.mpich -np 1 python etisp.py

Best regards,

Jiadun
Script 1:
etisp.py
from mpi4py import MPI

print("Starting particle simulations")

for i in range(1000):
	partsims = []
	for j in range(1):
		partsims.append(MPI.COMM_SELF.Spawn('esysparticle', args="partsim.py", maxprocs=2))
	#print("Loop", i)
	for k in range(1):
		partsims[k].send([1, 2, 3, 4], 0)	
	for ps in partsims:
		sigma = ps.recv()
		#print("Received from spawned", sigma)
	##if converged
	for ps in partsims:
		ps.send([], 0)
		ps.recv()	
		ps.Barrier()
		ps.Disconnect()
	print i
print("Done")
#MPI.Finalize()

Script 2: partsim.py
from esys.lsm import *
from esys.lsm.util import *
from esys.lsm.geometry import *
from mpi4py import MPI
import time

parent = MPI.Comm.Get_parent()

sigma = 0
sim = LsmMpi(numWorkerProcesses=1, mpiDimList=[1,1,1])
while True:
	data = parent.recv()
	if data == []:
		break
	#print("Received from etisp", data)
	#time.sleep(1)
	sigma += 1
	parent.send(sigma, 0)
	
#parent.Disconnect()
parent.send(sigma, 0)
sim.exit()

### LINKED ISSUE #5903: MPI_Comm_spawn -- too many file descriptors
When a job spawns many subprocesses via MPI_Comm_spawn, the job can fail with the error below.  MPICH currently launches an individual proxy for each spawn, which probably attributes to the flood of file descriptors on the server. 

**[mpiexec@n002.cluster.pssclabs.com] HYDU_create_process (../../../../mpich-4.0.1/src/pm/hydra/utils/launch/launch.c:21): pipe error (Too many open files)
[mpiexec@n002.cluster.pssclabs.com] HYDT_bscd_common_launch_procs (../../../../mpich-4.0.1/src/pm/hydra/tools/bootstrap/external/external_common_launch.c:296): create process returned error
free(): invalid pointer
/var/spool/slurm/job235999/slurm_script: line 296: 3778907 Aborted                 (core dumped)**

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
When we spawning processes, rather than launch separate proxy process, we can reuse the same proxy on each node to launch additional processes so long as the proxy can handle multiple `pg`s.

This is split from #5943

Fixes #2277 
Fixes #2913
Fixes #5903
[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/warnings/auto

**Comment by hzhou** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by hzhou** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by hzhou** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by hzhou** [comment]
test:mpich/pm

**Comment by hzhou** [comment]
test:mpich/pmi

**Comment by hzhou** [comment]
test:mpich/ch4/most
test:mpich/ch3/most
test:mpich/pmi

**Comment by hzhou** [comment]
test:mpich/ch4/most
test:mpich/ch3/most
test:mpich/pmi

**Comment by hzhou** [comment]
test:mpich/ch3/sock

File: src/pm/hydra/mpiexec/pmiserv_cb.c [hunk 1]
```diff
@@ -508,6 +508,8 @@ HYD_status HYD_pmcd_pmiserv_proxy_init_cb(int fd, HYD_event_t events, void *user
     proxy = &pg->proxy_list[proxy_id];
 
     /* This will be the control socket for this proxy */
+    // HYDU_ASSERT(proxy->node->control_fd == -1, status);
```
Comment (raffenet) [inline src/pm/hydra/mpiexec/pmiserv_cb.c:533]: should this assert be active or deleted?

File: src/pm/hydra/proxy/pmip.c [hunk 2]
```diff
@@ -149,40 +149,41 @@ int main(int argc, char **argv)
...
+                done++;
             }
+        }
 
-            /* If no more processes are pending, break out */
-            if (done == total_count)
-                break;
+        /* If no more processes are pending, break out */
+        if (done == total_count)
+            break;
```
Comment (raffenet) [inline src/pm/hydra/proxy/pmip.c:181]: do we still need this break now that the loop condition is basically the same?

**Comment by hzhou** [comment]
test:mpich/ch4/most
test:mpich/ch3/most
test:mpich/pmi

**Review by raffenet — COMMENTED** [review]
a couple minor comments. looks mostly good.

File: src/pm/hydra/proxy/pmip.c (hunk 2 above)
Comment (hzhou) [reply src/pm/hydra/proxy/pmip.c:181]: It was meant to skip the `HYDT_dmx_wait_for_event(0)` but I guess it is harmless to have the extra poll anyway. I'll try remove this break later.

**Comment by hzhou** [comment]
test:mpich/ch4/most
test:mpich/ch3/most
test:mpich/pmi

**Comment by hzhou** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by hzhou** [comment]
The `session_re_init` failures in PMI2 and PMIx are unrelated. I'll fix them separately.

File: src/pm/hydra/mpiexec/pmiserv_cb.c (hunk 1 above)
Comment (hzhou) [reply src/pm/hydra/mpiexec/pmiserv_cb.c]: Added fixup. Will squash before merge.

File: src/pm/hydra/proxy/pmip.c (hunk 2 above)
Comment (hzhou) [reply src/pm/hydra/proxy/pmip.c]: Added fixup. Will squash before merge.

**Review by raffenet — APPROVED** [review]
