### PR TITLE
thread: refactor thread initializations

### LINKED ISSUE #4192: MPI_Init_thread fails when using Argobots
What is the status of argobots support? The 3.3.1 README says it's supported, but it doesn't seem to work.

### MPICH info
```bash
$ mpichversion
MPICH Version:          3.3.1
MPICH Release date:     Wed Jun  5 14:57:33 CDT 2019
MPICH Device:           ch4:ofi
MPICH configure:        --prefix=/home/chogan/local --with-thread-package=argobots --with-ibverbs --with-device=ch4:ofi --with-libfabric=/home/chogan/local
MPICH CC:       gcc -I/home/chogan/local/include   -O2
MPICH CXX:      g++   -O2
MPICH F77:      gfortran   -O2
MPICH FC:       gfortran   -O2
MPICH Custom Information:
```

### Argobots info
Version `v1.0rc1`

### Reproducer
```bash
$ cat abt_test.c
#include "mpi.h"

int main(int argc, char **argv) {
  int provided;
  MPI_Init_thread(&argc, &argv, MPI_THREAD_MULTIPLE, &provided);
  return 0;
}

$ mpicc abt_test.c
$ mpirun -n 2 ./a.out
[mutex.c:120] ABT_mutex_free: 20
Error in system call ABT_mutex_free: Not a directory
    ../src/mpi/init/initthread.c:270
[mutex.c:120] ABT_mutex_free: 20
Error in system call ABT_mutex_free: Not a directory
    ../src/mpi/init/initthread.c:270
Assertion failed in file ../src/mpi/init/initthread.c at line 270: *&err == 0
Assertion failed in file ../src/mpi/init/initthread.c at line 270: *&err == 0
0x7f6cd81ef150 MPL_backtrace_show() + 0x18
0x7f6cd81949c4 MPIR_Assert_fail() + 0x24
0x7f6cd7392cc4 MPIR_Thread_CS_Finalize() + 0x154
0x7f6cd7392f50 MPIR_Init_thread() + 0x60
0x7f6cd7403b03 MPI_Init_thread() + 0xd3
0x400602 main() + 0x2b
0x7f6cd6dcc445 __libc_start_main() + 0xf5
0x400529 _start() + 0x29
Abort(1): Internal error
0x7f772a6ed150 MPL_backtrace_show() + 0x18
0x7f772a6929c4 MPIR_Assert_fail() + 0x24
0x7f7729890cc4 MPIR_Thread_CS_Finalize() + 0x154
0x7f7729890f50 MPIR_Init_thread() + 0x60
0x7f7729901b03 MPI_Init_thread() + 0xd3
0x400602 main() + 0x2b
0x7f77292ca445 __libc_start_main() + 0xf5
0x400529 _start() + 0x29
Abort(1): Internal error
```

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

To avoid paying the overhead of using TLS in a single-threaded application, we use run-time check `if(is_threaded)`, similar to the macros in `_THREAD_CS_ENTER/EXIT`. However, in the tls case, when the `is_theaded` flag change between calls (during init-time), inconsistency may arise. 

While we could patch the usage on a case-by-case basis, it adds fragile dependency between different components (deciding thread model inside device and tls initialization in various components). 

Option 1: remove runtime check and always pay the TLS overhead (undesirable, since single-threaded app still dominates)

Option 2: Make `is_threaded` static global inside `mpl_thread.c` and guard against multiple updates.

EDIT: The scope of this PR has been extended:
* refactored TLS macros configuration. Added assertions to guard against inconsistent usages.
* refactored thread initialization order
  ** set `MPIR_ThreadInfo.thread_provided` early so the rest of the component initializations can check thread-level consistently.
  ** added `MPIR_THREAD_CS_ENTER/EXIT` for use in `Init/Finalize`, remove the dependency of all other thread CS initialization/finalizations.
  ** set `MPIR_ThreadInfo.isThreaded` to `0` in `Init/Finalize` to disable all other mutex usages since they may not be initialized yet.
* fixed test suite build so argobots tests can be run

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
       Fixes #4192
* [ ] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [x] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by hzhou** [comment]
test:jenkins/custom
config=argobots

**Comment by hzhou** [comment]
test:jenkins/custom
config=argobots

**Comment by hzhou** [comment]
test:jenkins/custom
config=argobots

**Comment by hzhou** [comment]
test:jenkins/custom
config=argobots

**Comment by hzhou** [comment]
test:jenkins/custom
config=argobots

**Comment by hzhou** [comment]
test:jenkins/custom
config=argobots

**Comment by hzhou** [comment]
@shintaro-iwasaki Would you like to give this PR a review?

The jenkins tests fails at some configure issues that I am still debugging.

File: src/mpl/include/mpl_thread.h [hunk 1]
```diff
@@ -12,11 +12,13 @@
...
-#define MPL_THREAD_PACKAGE_WIN     4
-#define MPL_THREAD_PACKAGE_UTI     5
-#define MPL_THREAD_PACKAGE_ARGOBOTS 6
+#define MPL_THREAD_PACKAGE_YES     2    /* marker: thread is supported */
+#define MPL_THREAD_PACKAGE_POSIX   3
+#define MPL_THREAD_PACKAGE_SOLARIS 4
+#define MPL_THREAD_PACKAGE_WIN     5
+#define MPL_THREAD_PACKAGE_NON_NATIVE 6 /* marker: no native compiler tls support */
+#define MPL_THREAD_PACKAGE_UTI      7
+#define MPL_THREAD_PACKAGE_ARGOBOTS 8
```
Comment (shintaro-iwasaki) [inline src/mpl/include/mpl_thread.h]: It is extremely hard to understand (e.g., the meaning of `MPL_THREAD_PACKAGE_NAME < MPL_THREAD_PACKAGE_YES`).

File: src/mpl/include/mpl_thread_priv.h [hunk 2]
```diff
@@ -7,7 +7,21 @@
...
+/* No thread package, no need for tls */
+#undef MPL_TLS
+#define MPL_TLS
+
+#elif MPL_THREAD_PACKAGE_NAME > MPL_THREAD_PACKAGE_NON_NATIVE
+/* compiler tls won't work in this case */
+#undef MPL_TLS
+
+#endif
+
```
Comment (shintaro-iwasaki) [inline src/mpl/include/mpl_thread_priv.h]: Is it possible to define `MPL_TLS` etc in `mpl_thread_xxx.h` instead? I don't think this comparison-based detection is clean.

File: src/mpl/src/thread/mpl_thread.c [hunk 3]
```diff
@@ -6,7 +6,13 @@
...
 #include "mpl.h"
 
-MPL_SUPPRESS_OSX_HAS_NO_SYMBOLS_WARNING;
+int MPL_is_threaded = -1;
+
+void MPL_set_threaded(int isThreaded)
+{
+    assert(MPL_is_threaded == -1);
+    MPL_is_threaded = isThreaded;
+}
```
Comment (shintaro-iwasaki) [inline src/mpl/src/thread/mpl_thread.c]: I haven't run it, but does this logic work if I repeat `{MPI_Init_thread(); MPI_Finalize();}`?

File: src/mpi/init/finalize.c [hunk 4]
```diff
@@ -56,8 +56,8 @@ void MPIR_Add_finalize(int (*f) (void *), void *extra_data, int priority)
          * MPIR_Process.mpich_state to decide how to signal the error */
         (void) MPL_internal_error_printf("overflow in finalize stack! "
                                          "Is MAX_FINALIZE_FUNC too small?\n");
-        if (OPA_load_int(&MPIR_Process.mpich_state) == MPICH_MPI_STATE__IN_INIT ||
-            OPA_load_int(&MPIR_Process.mpich_state) == MPICH_MPI_STATE__POST_INIT) {
+        if (OPA_load_int(&MPIR_Process.mpich_state) > MPICH_MPI_STATE__PRE_INIT &&
+            OPA_load_int(&MPIR_Process.mpich_state) < MPICH_MPI_STATE__POST_FINALIZED) {
```
Comment (shintaro-iwasaki) [inline src/mpi/init/finalize.c]: `state >= MPICH_MPI_STATE__IN_INIT_1 && state <= MPICH_MPI_STATE__POST_INIT` looks easier to understand for me.

File: src/mpl/include/mpl_thread.h (hunk 1 above)
Comment (hzhou) [reply src/mpl/include/mpl_thread.h]: Do you like the previous alternative better? Which is to explicitly compare individual enum values. 

I find it equally obscure and also not scalable. I.e. every time we add or change supported thread-package, we need re-evaluate every such condition or we risk missing things.

File: src/mpl/include/mpl_thread_priv.h (hunk 2 above)
Comment (hzhou) [reply src/mpl/include/mpl_thread_priv.h]: My reasoning is to let `configure` do feature detection and only feature detection. So it detects whether compiler support TLS keyword and defines `MPL_TLS`. That is why that is defined in `mplconfig.h`. 

It is a hack to simplify logic. I agree it is less desirable. How about I create a new macros, e.g. `MPL_TLS_DIRECT` instead of hacking `MPL_TLS`?

File: src/mpi/init/init_thread_cs.c [hunk 5]
```diff
@@ -28,24 +28,26 @@ void MPII_init_thread_and_enter_cs(int thread_required)
...
-    MPIR_ThreadInfo.isThreaded = required_is_threaded;
+    MPIR_ThreadInfo.isThreaded = (thread_required == MPI_THREAD_MULTIPLE);
+    required_is_threaded = MPIR_ThreadInfo.isThreaded;
+
     MPID_THREAD_CS_ENTER(GLOBAL, MPIR_THREAD_GLOBAL_ALLFUNC_MUTEX);
     MPID_THREAD_CS_ENTER(VCI, MPIR_THREAD_GLOBAL_ALLFUNC_MUTEX);
+    /* Reset isThreaded during init to disable all other mutexes.
+     * One, they may not have been initialized.
+     * Two, there is no need for additional mutex locks during init.
+     */
```
Comment (shintaro-iwasaki) [inline src/mpi/init/init_thread_cs.c]: I am not sure if this logic is really correct. In my understanding, if we set `MPIR_ThreadInfo.isThreaded = 0;` here, any other threads that try to take `MPIR_THREAD_GLOBAL_ALLFUNC_MUTEX` will ignore a mutex in `MPID_THREAD_CS_ENTER`. Is this behavior okay?

File: src/mpl/src/thread/mpl_thread.c (hunk 3 above)
Comment (hzhou) [reply src/mpl/src/thread/mpl_thread.c]: MPI standards does not allow such. :)

File: src/mpi/init/finalize.c (hunk 4 above)
Comment (hzhou) [reply src/mpi/init/finalize.c]: My reasoning is to minimize the exposure of `MPICH_MPI_STATE__IN_INIT_x` since they are init-only internal stages.

Comment (shintaro-iwasaki) [reply src/mpi/init/finalize.c]: Then, `state > MPICH_MPI_STATE__PRE_INIT && state <= MPICH_MPI_STATE__POST_INIT` should be better. At least I don't know what `state < MPICH_MPI_STATE__POST_FINALIZED` means.

File: src/mpi/init/init_thread_cs.c (hunk 5 above)
Comment (hzhou) [reply src/mpi/init/init_thread_cs.c]: The entire init code is already locked under `MPIR_THREAD_GLOBAL_ALLFUNC_MUTEX`. MPI standards forbids most MPI calls before `MPI_Init` or `MPI_Finalize`, other than trivial ones such as `MPI_Initialized` and `MPI_Finalized`.

Comment (hzhou) [reply src/mpi/init/init_thread_cs.c]: In another word, if user tried to run `MPI_Send` in another thread before `MPI_init` finish, it is a user error.

File: src/mpl/include/mpl_thread_priv.h (hunk 2 above)
Comment (shintaro-iwasaki) [reply src/mpl/include/mpl_thread_priv.h]: https://github.com/pmodels/mpich/blob/master/src/mpl/include/mpl_thread.h includes `mpl_thread_priv.h` after `mpl_thread_xxx.h` (e.g., `mpl_thread_posix.h` and `mpl_thread_argobots.h`). Can't we put this logic in these `mpl_thread_xxx.h` headers? If so, we can remove comparison against `MPL_THREAD_PACKAGE_NON_NATIVE` etc.

Changing the name (`MPL_TLS_DIRECT` or `MPL_COMPILER_TLS_SUPPORT`) looks good to me.

File: src/mpl/src/thread/mpl_thread.c (hunk 3 above)
Comment (shintaro-iwasaki) [reply src/mpl/src/thread/mpl_thread.c]: Wow. I didn't know that. Thanks! Then there's no problem.

File: src/mpi/init/init_thread_cs.c (hunk 5 above)
Comment (shintaro-iwasaki) [reply src/mpi/init/init_thread_cs.c]: I see, then do we need to take a lock here (MPIR_THREAD_GLOBAL_ALLFUNC_MUTEX)?
Because  `MPIR_ThreadInfo.isThreaded` is set to 0, this lock does not protect anything.

Comment (hzhou) [reply src/mpi/init/init_thread_cs.c]: On second thought, you are right. It essentially voids the lock in `MPI_Init` itself. I'll work out another strategy.

**Comment by hzhou** [comment]
@shintaro-iwasaki Could you take a look at the last two commits?

File: src/mpl/include/mpl_thread.h [hunk 6]
```diff
@@ -21,15 +21,24 @@
...
+#endif
+
 #if defined(MPL_THREAD_PACKAGE_NAME) && (MPL_THREAD_PACKAGE_NAME == MPL_THREAD_PACKAGE_POSIX || MPL_THREAD_PACKAGE_NAME == MPL_THREAD_PACKAGE_UTI)
 #include "mpl_thread_posix.h"
 #elif defined(MPL_THREAD_PACKAGE_NAME) && (MPL_THREAD_PACKAGE_NAME == MPL_THREAD_PACKAGE_SOLARIS)
 #include "mpl_thread_solaris.h"
 #elif defined(MPL_THREAD_PACKAGE_NAME) && (MPL_THREAD_PACKAGE_NAME == MPL_THREAD_PACKAGE_WIN)
 #include "mpl_thread_win.h"
 #elif defined(MPL_THREAD_PACKAGE_NAME) && (MPL_THREAD_PACKAGE_NAME == MPL_THREAD_PACKAGE_ARGOBOTS)
+#undef MPL_TLS  /* compiler tls cannot be used */
```
Comment (shintaro-iwasaki) [inline src/mpl/include/mpl_thread.h]: Let's define it in `mpl_thread_argobots.h`.

File: src/mpi/init/init_thread_cs.c [hunk 7]
```diff
@@ -8,14 +8,40 @@
...
+ * Idealy, we should have these in mpir_thread.h so other non-performance-
+ * critical paths may use these macros to stablize from the complicated and
+ * evolving threading experiments. However, its dependency on MPIDU_macros
+ * makes it complicated.
+ */
+#if defined(MPICH_IS_THREADED)
+#define MPIR_THREAD_CS_ENTER(mutex) \
+    do { \
+        int err_ = 0; \
+        MPIDU_Thread_mutex_lock(&mutex, &err_, MPL_THREAD_PRIO_HIGH); \
```
Comment (shintaro-iwasaki) [inline src/mpi/init/init_thread_cs.c]: I don't know the naming convention in MPICH, but I think it should use `MPID_Thread_mutex_lock` instead of `MPIDU_Thread_mutex_lock` (as `MPID_Thread_mutex_create` is used in the same function).

File: src/mpi/init/init_thread_cs.c [hunk 8]
```diff
@@ -28,25 +54,15 @@ void MPII_init_thread_and_enter_cs(int thread_required)
     MPID_Thread_mutex_create(&MPIR_THREAD_GLOBAL_ALLFUNC_MUTEX, &err);
     MPIR_Assert(err == 0);
 
-    MPIR_ThreadInfo.isThreaded = (thread_required == MPI_THREAD_MULTIPLE);
-    required_is_threaded = MPIR_ThreadInfo.isThreaded;
+    MPIR_THREAD_CS_ENTER(MPIR_THREAD_GLOBAL_ALLFUNC_MUTEX);
```
Comment (shintaro-iwasaki) [inline src/mpi/init/init_thread_cs.c]: Overall, does it solve the problem? I think the fundamental issue is what this mutex intends to protect.
This unconditional `CS_ENTER` and `CS_EXIT` can only protect `MPII_init` and `MPII_finalize` functions since other attempts to take this mutex (at other places) will check `MPIR_ThreadInfo.isThreaded` and they ignore this mutex because it is temporarily set to 0.

If this mutex only needs to protect `MPII_init` and `MPII_finalize`, this fix should work.

File: src/mpl/include/mpl_thread_priv.h [hunk 9]
```diff
@@ -10,7 +10,7 @@
 extern int MPL_is_threaded;
 void MPL_set_threaded(int isThreaded);
 
-#if MPL_THREAD_PACKAGE_NAME != MPL_THREAD_PACKAGE_NONE && !defined(MPL_TLS)
+#if !defined(MPL_TLS)
```
Comment (shintaro-iwasaki) [inline src/mpl/include/mpl_thread_priv.h]: I believe the logic is changed here.
When  `MPL_THREAD_PACKAGE_NAME != MPL_THREAD_PACKAGE_NONE` holds,  the `threadpriv` version is chosen in the current one, though neither is activated previously.

File: src/mpl/include/mpl_thread.h (hunk 6 above)
Comment (hzhou) [reply src/mpl/include/mpl_thread.h]: Don't think it is better not to spread the logic component across multiple files?

File: src/mpi/init/init_thread_cs.c (hunk 7 above)
Comment (hzhou) [reply src/mpi/init/init_thread_cs.c]: Yes, you are right. My negligence during copy-pasting.

File: src/mpi/init/init_thread_cs.c (hunk 8 above)
Comment (hzhou) [reply src/mpi/init/init_thread_cs.c]: It only protects `MPI_Init/Finalize` from itself. Even if we remove the lock, it is still correct per MPI standards -- attributing to user errors. But as implementation, we try to be nicer when we can.

File: src/mpl/include/mpl_thread_priv.h (hunk 9 above)
Comment (shintaro-iwasaki) [reply src/mpl/include/mpl_thread_priv.h]: I misunderstand something critical. It looks okay to me.

File: src/mpl/include/mpl_thread.h (hunk 6 above)
Comment (hzhou) [reply src/mpl/include/mpl_thread.h]: Updated.

File: src/mpi/init/init_thread_cs.c (hunk 7 above)
Comment (hzhou) [reply src/mpi/init/init_thread_cs.c]: Corrected.

File: src/mpl/include/mpl_thread.h (hunk 6 above)
Comment (shintaro-iwasaki) [reply src/mpl/include/mpl_thread.h]: Looks good to me!

File: src/mpl/include/mpl_thread.h (hunk 1 above)
Comment (shintaro-iwasaki) [reply src/mpl/include/mpl_thread.h]: It is solved.

**Comment by hzhou** [comment]
test:jenkins/custom
config=argobots

**Comment by hzhou** [comment]
test:jenkins/custom
config=argobots

**Comment by hzhou** [comment]
test:mpich/quick --with-thread-package=abt --with-argobots=/var/lib/jenkins-slave/software/argobots

**Comment by hzhou** [comment]
test:mpich/quick --with-thread-package=abt --with-argobots=$PMRS/opt/argobots
skip_test: 1

**Comment by hzhou** [comment]
test:mpich/quick --with-thread-package=abt --with-argobots=$PMRS/opt/argobots
skip_test: 1

**Comment by hzhou** [comment]
test:jenkins/custom
config=argobots

**Comment by hzhou** [comment]
test:mpich/quick --with-thread-package=abt --with-argobots=$PMRS/opt/argobots
skip_test: 1

**Comment by hzhou** [comment]
test:mpich/quick --with-thread-package=abt --with-argobots=$PMRS/opt/argobots
skip_test: 1

**Comment by hzhou** [comment]
test:mpich/quick --with-thread-package=abt --with-argobots=$PMRS/opt/argobots
skip_test: 1

**Comment by hzhou** [comment]
test:mpich/quick --with-thread-package=abt --with-argobots=$PMRS/opt/argobots
compiler: gcc-8
skip_test: 1

File: src/mpi/init/finalize.c (hunk 4 above)
Comment (shintaro-iwasaki) [reply src/mpi/init/finalize.c]: If you don't strongly oppose, let's change it to `<= MPICH_MPI_STATE__POST_INIT`. `state < MPICH_MPI_STATE__POST_FINALIZED` implies existence of `MPICH_MPI_STATE__PRE_FINALIZED`, which does not exist.

**Comment by shintaro-iwasaki** [comment]
I recognize that some tests fail with Argobots. I will take a look at it, but it should be done separately.
Overall, this PR looks good to me.

**Comment by hzhou** [comment]
> I recognize that some tests fail with Argobots. I will take a look at it, but it should be done separately.
> Overall, this PR looks good to me.

Thanks @shintaro-iwasaki . I agree the bug fixes should be separate PRs (multiple if necessary). I just opened issue #4204 tracking it.

**Comment by hzhou** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:jenkins/ch4/ucx

**Comment by hzhou** [comment]
test:jenkins/ch3/most

**Comment by hzhou** [comment]
test:jenkins/custom
config=argobots

test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:jenkins/ch4/ucx

File: src/mpi/init/init_dbg_logging.c [hunk 10]
```diff
@@ -42,7 +42,7 @@ void MPII_init_dbg_logging(void)
 #ifdef MPICH_IS_THREADED
     MPL_dbg_init(NULL, NULL, TRUE, TRUE,
                  MPIR_Process.comm_parent != NULL, MPIR_Process.comm_world->rank,
-                 MPIR_ThreadInfo.isThreaded);
+                 MPIR_ThreadInfo.thread_provided == MPI_THREAD_MULTIPLE);
```
Comment (raffenet) [inline src/mpi/init/init_dbg_logging.c]: Since `MPIR_ThreadInfo.thread_provided` is always defined, can we remove the preprocessor guards?

File: src/mpi/init/initthread.c [hunk 11]
```diff
@@ -122,8 +140,8 @@ int MPIR_Init_thread(int *argc, char ***argv, int required, int *provided)
     mpi_errno = MPIR_Datatype_init_predefined();
     MPIR_ERR_CHECK(mpi_errno);
 
-    int thread_provided = 0;
-    mpi_errno = MPID_Init(argc, argv, required, &thread_provided);
+    /* **** */
```
Comment (raffenet) [inline src/mpi/init/initthread.c]: Was there intention to add some comment here?

File: src/mpi/init/mpi_init.h [hunk 12]
```diff
@@ -75,7 +75,8 @@ static inline void MPII_post_init_memory_tracing(void)
 {
 #ifdef USE_MEMORY_TRACING
 #ifdef MPICH_IS_THREADED
-    MPL_trconfig(MPIR_Process.comm_world->rank, MPIR_ThreadInfo.isThreaded);
+    MPL_trconfig(MPIR_Process.comm_world->rank,
+                 MPIR_ThreadInfo.thread_provided == MPI_THREAD_MULTIPLE);
```
Comment (raffenet) [inline src/mpi/init/mpi_init.h]: Remove preprocessor guards here, too?

File: test/mpi/Makefile.mtest [hunk 13]
```diff
@@ -20,7 +20,7 @@ LDADD = $(top_builddir)/util/mtest.$(OBJEXT) $(top_builddir)/util/mtest_common.$
 
 # Add libdtpools support
 AM_CPPFLAGS += -I$(top_srcdir)/dtpools/include
-LDADD += $(top_builddir)/dtpools/src/libdtpools.la
+LDADD += $(top_builddir)/dtpools/src/libdtpools.la @threadlib@
```
Comment (raffenet) [inline test/mpi/Makefile.mtest]: We have this already in `Makefile_threads.mtest`, so I'm a little confused about adding it here. Do all tests depend on Argobots in this scenario? I.e. not just the tests that create threads?

Comment (hzhou) [reply test/mpi/Makefile.mtest]: Good question. I'll investigate more.

File: src/mpi/init/init_dbg_logging.c (hunk 10 above)
Comment (hzhou) [reply src/mpi/init/init_dbg_logging.c]: I like the suggestion.

File: src/mpi/init/initthread.c (hunk 11 above)
Comment (hzhou) [reply src/mpi/init/initthread.c]: I just felt like it needs a divider marker.

Comment (raffenet) [reply src/mpi/init/initthread.c]: OK, got it. Is there some high-level phase change here we could possibly note? Like we are transitioning from device-independent, local init -> device-specific, non-local init.

File: src/mpi/init/mpi_init.h (hunk 12 above)
Comment (hzhou) [reply src/mpi/init/mpi_init.h]: Updated in commit https://github.com/pmodels/mpich/pull/4199/commits/96594d579ca73407a6d63443266acc731e1bc8b5

File: src/mpi/init/init_dbg_logging.c (hunk 10 above)
Comment (hzhou) [reply src/mpi/init/init_dbg_logging.c]: Updated in commit https://github.com/pmodels/mpich/pull/4199/commits/96594d579ca73407a6d63443266acc731e1bc8b5

File: test/mpi/Makefile.mtest (hunk 13 above)
Comment (hzhou) [reply test/mpi/Makefile.mtest]: Yes. All tests depend on argonbots when the configure options is passed in, due to these lines in `mtest.c`: https://github.com/pmodels/mpich/blob/cb944baeb07061759f7c22d85704cc9c673056f9/test/mpi/util/mtest.c#L72

File: src/mpi/init/initthread.c [hunk 14]
```diff
@@ -122,8 +140,8 @@ int MPIR_Init_thread(int *argc, char ***argv, int required, int *provided)
     mpi_errno = MPIR_Datatype_init_predefined();
     MPIR_ERR_CHECK(mpi_errno);
 
-    int thread_provided = 0;
-    mpi_errno = MPID_Init(argc, argv, required, &thread_provided);
+    /* Device init */
```
Comment (hzhou) [inline src/mpi/init/initthread.c]: updated.

**Comment by hzhou** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:jenkins/custom
config=argobots

**Comment by hzhou** [comment]
test:jenkins/custom
config=argobots

**Comment by hzhou** [comment]
test:jenkins/custom
config=argobots

**Comment by hzhou** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test again for cleaner results:

test:jenkins/ch3/sock

**Comment by hzhou** [comment]
Solaris is inconsistently failing:

test:jenkins/ch3/sock

File: src/mpid/ch3/src/mpid_init.c [hunk 15]
```diff
@@ -86,7 +86,16 @@ static int set_eager_threshold(MPIR_Comm *comm_ptr, MPIR_Info *info, void *state
 }
 
 
-int MPID_Init(int *argc, char ***argv, int requested, int *provided)
+int MPID_Init_thread_level(int *argc, char ***argv, int requested, int *provided)
```
Comment (raffenet) [inline src/mpid/ch3/src/mpid_init.c]: Adding a new ADI function is not a refactor. This change should be split out and reviewed on its own.

File: test/mpi/util/mtest_f90.f90 [hunk 16]
```diff
@@ -0,0 +1,150 @@
+! This file created from f77/util/mtestf.f with f77tof90
```
Comment (raffenet) [inline test/mpi/util/mtest_f90.f90]: Should we remove this line about how the file was created? How is this version modified from the old generated version?

**Comment by wesbland** [comment]
cc: @sagarth

**Comment by hzhou** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

File: src/mpi/init/mpi_init.h [hunk 17]
```diff
@@ -74,12 +74,8 @@ static inline void MPII_pre_init_memory_tracing(void)
 static inline void MPII_post_init_memory_tracing(void)
 {
 #ifdef USE_MEMORY_TRACING
-#ifdef MPICH_IS_THREADED
```
Comment (raffenet) [inline src/mpi/init/mpi_init.h]: Commit message refers to some comment change, but it doesn't appear to be here.
