### PR TITLE
ch4/cma: check ptrace_scope at init

### LINKED ISSUE #7653: mpi4py: Regression after MPICH enabled CMA by default
After merging #7639 which enables CMA by default, one of mpi4py tests no longer passes [logs](https://github.com/mpi4py/mpi4py-testing/actions/runs/18960289823/job/54145964888#step:20:3668)
Of course, the problem is not in PR #7639 itself, but rather in the underlying shm/CMA code.

From the logs:
```
Traceback (most recent call last):
  File "/home/runner/work/mpi4py-testing/mpi4py-testing/test/test_util_pkl5.py", line 901, in testBigMPI
    rmess = comm.sendrecv(
        smess,
    ...<5 lines>...
        status,
    )
  File "src/mpi4py/MPI.src/Comm.pyx", line 2015, in mpi4py.MPI.Comm.sendrecv
    return PyMPI_sendrecv(sendobj, dest,   sendtag,
  File "src/mpi4py/MPI.src/msgpickle.pxi", line 468, in mpi4py.MPI.PyMPI_sendrecv
    robj = PyMPI_recv (robj, source, recvtag, comm, status)
  File "src/mpi4py/MPI.src/msgpickle.pxi", line 377, in mpi4py.MPI.PyMPI_recv
    return PyMPI_recv_match(obj, source, tag, comm, status)
  File "src/mpi4py/MPI.src/asbuffer.pxi", line 337, in mpi4py.MPI.asbuffer
    buf = getbuffer(ob, ro, 0)
mpi4py.MPI.Exception: Other MPI error, error stack:
internal_Mrecv_c(301)..: MPI_Mrecv_c(buf=0x564fea350620, count=8348, MPI_BYTE, message=0x7fff24d127d0, status=0x7ff239779ed0) failed
internal_Mrecv_c(264)..: 
MPIR_Wait(745).........: 
MPIDI_IPC_rndv_cb(172).: 
MPIDI_CMA_copy_data(54): 
copy_iovs(201).........: process_vm_readv failed (errno 1)
```

Could this somehow be related to MPIR_CVAR_CH4_IPC_CMA_P2P_THRESHOLD being lowered from 16384 to 8192, and this is not triggering a previously hidden issue/bug in MPICH?

cc @yfguo

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
Users may not have ptrace_scope permission set. Check it at init and turn MPIR_CVAR_CH4_CMA_ENABLE off if we don't have the permission.

Fixes #7653
[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch4/most

File: src/mpid/ch4/shm/ipc/cma/cma_init.c [hunk 1]
```diff
@@ -12,6 +12,28 @@ int MPIDI_CMA_init_local(void)
...
 
+    bool cma_happy = false;
+
+    /* check ptrace permission */
+    int fd = open("/proc/sys/kernel/yama/ptrace_scope", O_RDONLY);
+    char buffer = '0';
+    if (fd >= 0) {
+        int ret = read(fd, &buffer, 1);
+        if (ret >= 0) {
+            if (buffer != '0') {
```
Comment (dalcinl) [inline src/mpid/ch4/shm/ipc/cma/cma_init.c:23]: @hzhou I was not aware of this PR until you merged it. 

I believe this is not correct.  It is actually the opposite. If `ptrace_scope=0`, then you ptrace is enabled and you can do CMA. If it is different than `0`, then you could  attempt to enable it with `prctl(...)` (you will need a configure test for that API)  or bail out, just like Open MPI does.

https://www.kernel.org/doc/Documentation/security/Yama.txt
>> 0 - classic ptrace permissions: a process can PTRACE_ATTACH to any other
    process running under the same uid, as long as it is dumpable (i.e.
    did not transition uids, start privileged, or have called
    prctl(PR_SET_DUMPABLE...) already). Similarly, PTRACE_TRACEME is
    unchanged.

Am I getting it wrong?

Comment (hzhou) [reply src/mpid/ch4/shm/ipc/cma/cma_init.c:23]: You probably is right -- I am not myself lately 😫 Let me try again.
