### PR TITLE
coll: fix the case type_size greater than chunk size

### LINKED ISSUE #6239: bug: MPI_Reduce for large derived datatype causes FPE exception
We've been trying to test ScaLAPACK 2.2.0 and ScaLAPACK  2.1.0  https://netlib.org/scalapack and we found out that BLACS tests crash with MPICH 4.0.2. Our investigation showed that seg faults happen while calling MPI_reduce for  MPI_DOUBLE_COMPLEX  for computing max or min absolute value of a double complex precision.  Here are steps to reproduce: 
1. Download ScaLAPACK 2.2.0 or ScaLAPACK 2.1.0
2.  Unpack and build it (cd scalapack-2.2.0/;  cp SLmake.inc.example SLmake.inc and type make)
3.  Then cd BLACS/TESTING and try to execute xCbtest  or xFbtest by the command:
   $mpiexec -n 4 ./xCbtest  
  On our system we always got:
....
 DOUBLE COMPLEX AMX TESTS: BEGIN.
 
Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
 
We've been using MPICH 4.0.2  
$ mpiexec --version
HYDRA build details:
    Version:                                 4.0.2
    Release Date:                            Thu Apr  7 12:34:45 CDT 2022
    CC:                              gcc      
    Configure options:                       '--disable-option-checking' '--prefix=/export/users/skuznets/mpich402' '--cache-file=/dev/null' '--srcdir=.' 'CC=gcc' 'CFLAGS= ' 'LDFLAGS=' 'LIBS=' 'CPPFLAGS= '
    Process Manager:                         pmi
    Launchers available:                     ssh rsh fork slurm ll lsf sge manual persist
    Topology libraries available:            hwloc
    Resource management kernels available:   user slurm ll lsf sge pbs cobalt
    Demux engines available:                 poll select

where 
]$ gcc --version
gcc (GCC) 8.3.1 20190507 (Red Hat 8.3.1-4)

was used for building MPICH 4.0.2 and ScaLAPACK 2.1.0 -2.2.0

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
It is missing check when type_size is bigger than chunk_size, which will result pipelining of zero-sized chunks, end up with divide-by-zero FPE.

Add a test that reproduces the bug.

Fixes #6239 
[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Review by raffenet — APPROVED** [review]

File: src/mpid/ch4/src/ch4_coll.h [hunk 1]
```diff
@@ -408,6 +408,13 @@ MPL_STATIC_INLINE_PREFIX int MPID_Allreduce(const void *sendbuf, void *recvbuf,
 
     is_commutative = MPIR_Op_is_commutative(op);
 
+    MPI_Aint dt_size;
+    MPIR_Datatype_get_size_macro(datatype, dt_size);
+    if (dt_size >=
+        MPIR_CVAR_REDUCE_INTRANODE_BUFFER_TOTAL_SIZE / MPIR_CVAR_REDUCE_INTRANODE_NUM_CELLS) {
+        goto fallback;
```
Comment (zhenggb72) [inline src/mpid/ch4/src/ch4_coll.h:415]: Not sure if this is correct,  Not all composition algorithms do pipelining I think. Maybe this check should go one level down to the alpha, beta gamma functions?

**Comment by hzhou** [comment]
> Is [d5fdf75](https://github.com/pmodels/mpich/commit/d5fdf754a8799b301ee7bb2dbacaa6261bb050d6) enough to fix the user reported issue? Or is the ch4/coll patch also needed? Just trying to decide if I should include this fix in 4.0.3...

The ch4/coll fallback is also needed. The release gather uses fixed shm chunks, so if the type_sz is too big, it won't fit and will result in segfault or corruptions.

@zhenggb72 Can we merge this patch for now? I won't have time to figure out which lower path is affected and which path is still capable of falling back. All release gather algorithms uses shm segments are affected. For those not using release gather, I believe it is equivalent to fallback in the current code. We can always improve the solution with future PRs.

File: src/mpid/ch4/src/ch4_coll.h (hunk 1 above)
Comment (raffenet) [reply src/mpid/ch4/src/ch4_coll.h:415]: That might be an improvement, but will take some time to investigate. I'm tempted to pick this patch as-is for 4.0.x and ship since it fixes a user-reported bug. I guess we have a little extra time to get it right for 4.1.

@hzhou the commit message mentions MPID_Bcast, but this patch only modified reduce and allreduce. Is there a missing piece?

Comment (hzhou) [reply src/mpid/ch4/src/ch4_coll.h:415]: I originally thought bcast was susceptible, but it turns out bcast can simply break down to basic elements, so the outmost type size is irrelevant. Only reduce and allreduce are affected. Let me update the commit message...

**Comment by zhenggb72** [comment]
ok. I guess this is a fix for corner case anyway?

**Review by zhenggb72 — APPROVED** [review]
